---
title: "Cellranger count split"
namespace: "Mapping"
description: "Split 10x Cell Ranger output directory into separate output fields."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `cellranger_count_split`  
Namespace: `mapping`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/0.9.0/./src/mapping/cellranger_count_split){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.9.0 -latest \
  -main-script target/nextflow/mapping/cellranger_count_split/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input_dir"
# filtered_h5: "$id.$key.filtered_h5.h5"
# metrics_summary: "$id.$key.metrics_summary.csv"
# molecule_info: "$id.$key.molecule_info.h5"
# bam: "$id.$key.bam.bam"
# bai: "$id.$key.bai.bai"
# raw_h5: "$id.$key.raw_h5.h5"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.9.0 -latest \
  -profile docker \
  -main-script target/nextflow/mapping/cellranger_count_split/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                |Description                                    |Attributes                                         |
|:-------------------|:----------------------------------------------|:--------------------------------------------------|
|`--input`           |Output directory from a Cell Ranger count run. |`file`, required, example: `"input_dir"`           |
|`--filtered_h5`     |                                               |`file`, example: `"filtered_feature_bc_matrix.h5"` |
|`--metrics_summary` |                                               |`file`, example: `"metrics_summary.csv"`           |
|`--molecule_info`   |                                               |`file`, example: `"molecule_info.h5"`              |
|`--bam`             |                                               |`file`, example: `"possorted_genome_bam.bam"`      |
|`--bai`             |                                               |`file`, example: `"possorted_genome_bam.bam.bai"`  |
|`--raw_h5`          |                                               |`file`, example: `"raw_feature_bc_matrix.h5"`      |

## Authors


  * Angela Oliveira Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) [{{< fa brands linkedin >}}](https://linkedin.com/in/aopisco) (author)

  * Samuel D'Souza [{{< fa brands github >}}](https://github.com/srdsam) [{{< fa brands linkedin >}}](https://linkedin.com/in/samuel-d-souza-887023150/) (author)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author, maintainer)
