---
title: "Htseq count to h5mu"
namespace: "Mapping"
description: "Convert the htseq table to a h5mu"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `htseq_count_to_h5mu`  
Namespace: `mapping`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/0.9.0/src/mapping/htseq_count_to_h5mu){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.9.0 -latest \
  -main-script target/nextflow/mapping/htseq_count_to_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Input
input_id: # please fill in - example: ["foo"]
input_counts: # please fill in - example: ["counts.tsv"]
reference: # please fill in - example: "gencode_v41_star"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.9.0 -latest \
  -profile docker \
  -main-script target/nextflow/mapping/htseq_count_to_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Input

|Name             |Description                                  |Attributes                                      |
|:----------------|:--------------------------------------------|:-----------------------------------------------|
|`--input_id`     |The obs index for the counts                 |`string`, required, example: `"foo"`            |
|`--input_counts` |The counts as a TSV file as output by HTSeq. |`file`, required, example: `"counts.tsv"`       |
|`--reference`    |The GTF file.                                |`file`, required, example: `"gencode_v41_star"` |


### Outputs

|Name                   |Description                                                  |Attributes                                 |
|:----------------------|:------------------------------------------------------------|:------------------------------------------|
|`--output`             |Output h5mu file.                                            |`file`, required, example: `"output.h5mu"` |
|`--output_compression` |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                |

## Authors


  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author, maintainer)

  * Angela Oliveira Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) [{{< fa brands linkedin >}}](https://linkedin.com/in/aopisco) (author)
