---
title: "Multi star to h5mu"
namespace: "Mapping"
description: "Convert the output of `multi_star` to a h5mu"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `multi_star_to_h5mu`  
Namespace: `mapping`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/0.12.5/./src/mapping/multi_star_to_h5mu){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.12.5 -latest \
  -main-script target/nextflow/mapping/multi_star_to_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "/path/to/foo"
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.12.5 -latest \
  -profile docker \
  -main-script target/nextflow/mapping/multi_star_to_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                  |Attributes                                  |
|:----------------------|:------------------------------------------------------------|:-------------------------------------------|
|`--input`              |The directory created by `multi_star`                        |`file`, required, example: `"/path/to/foo"` |
|`--output`             |Output h5mu file.                                            |`file`, required, example: `"output.h5mu"`  |
|`--output_compression` |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                 |

## Authors


  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author, maintainer)

  * Angela Oliveira Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) [{{< fa brands linkedin >}}](https://linkedin.com/in/aopisco) (author)
