---
title: "Lianapy"
namespace: "Interpret"
description: "Performs LIANA integration based as described in https://github.com/saezlab/liana-py"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `lianapy`  
Namespace: `interpret`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.1/./src/interpret/lianapy){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -main-script target/nextflow/interpret/lianapy/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "path/to/file"
# output: "$id.$key.output.output"
output_compression: "gzip"
modality: "rna"
# layer: "foo"
groupby: "bulk_labels"
resource_name: "consensus"
gene_symbol: "gene_symbol"
expr_prop: 0.1
min_cells: 5
aggregate_method: "rra"
return_all_lrs: false
n_perms: 100

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/interpret/lianapy/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                                                                                                                                                                                        |Attributes                         |
|:----------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------|
|`--input`              |Input h5mu file                                                                                                                                                                                                                    |`file`, required                   |
|`--output`             |Output h5mu file.                                                                                                                                                                                                                  |`file`, required                   |
|`--output_compression` |                                                                                                                                                                                                                                   |`string`, default: `"gzip"`        |
|`--modality`           |                                                                                                                                                                                                                                   |`string`, default: `"rna"`         |
|`--layer`              |Layer in anndata.AnnData.layers to use. If None, use mudata.mod[modality].X.                                                                                                                                                       |`string`                           |
|`--groupby`            |The key of the observations grouping to consider.                                                                                                                                                                                  |`string`, default: `"bulk_labels"` |
|`--resource_name`      |Name of the resource to be loaded and use for ligand-receptor inference.                                                                                                                                                           |`string`, default: `"consensus"`   |
|`--gene_symbol`        |Column name in var DataFrame in which gene symbol are stored.                                                                                                                                                                      |`string`, default: `"gene_symbol"` |
|`--expr_prop`          |Minimum expression proportion for the ligands/receptors (and their subunits) in the corresponding cell identities. Set to '0', to return unfiltered results.                                                                       |`double`, default: `0.1`           |
|`--min_cells`          |Minimum cells per cell identity ('groupby') to be considered for downstream analysis.                                                                                                                                              |`integer`, default: `5`            |
|`--aggregate_method`   |Method aggregation approach, one of ['mean', 'rra'], where 'mean' represents the mean rank, while 'rra' is the RobustRankAggregate (Kolde et al., 2014) of the interactions.                                                       |`string`, default: `"rra"`         |
|`--return_all_lrs`     |Bool whether to return all LRs, or only those that surpass the 'expr_prop' threshold. Those interactions that do not pass the 'expr_prop' threshold will be assigned to the *worst* score of the ones that do. 'False' by default. |`boolean`, default: `FALSE`        |
|`--n_perms`            |Number of permutations for the permutation test. Note that this is relevant only for permutation-based methods - e.g. 'CellPhoneDB                                                                                                 |`integer`, default: `100`          |

## Authors


  * Mauro Saporita [{{< fa brands github >}}](https://github.com/mauro-saporita) [{{< fa brands linkedin >}}](https://linkedin.com/in/mauro-saporita-930b06a5) (author)

  * Povilas Gibas [{{< fa brands github >}}](https://github.com/PoGibas) [{{< fa brands linkedin >}}](https://linkedin.com/in/povilas-gibas) (author)
