---
title: "Viash configs to qmd"
namespace: "Quarto"
description: "Generates .qmd files for documentating viash components and workflows"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `viash_configs_to_qmd`  
Namespace: `quarto`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/experiment_website_push/viash_tools/src/quarto/viash_configs_to_qmd){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r experiment_website_push -latest \
  -main-script target/nextflow/quarto/viash_configs_to_qmd/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r experiment_website_push -latest \
  -profile docker \
  -main-script target/nextflow/quarto/viash_configs_to_qmd/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name          |Description                                                                        |Attributes                                |
|:-------------|:----------------------------------------------------------------------------------|:-----------------------------------------|
|`--input`     |yaml file from `viash ns list`                                                     |`file`, required, example: `"input.yaml"` |
|`--output`    |Output directory                                                                   |`file`, required                          |
|`--build_dir` |Output location of build viash components, relative to the root of the repository. |`string`, default: `"target/nextflow/"`   |
|`--git_tag`   |Overwrite git tag                                                                  |`string`                                  |

## Authors

  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) (maintainer)
