---
title: Requirements
---

Openpipelines is being developed in Viash and Nextflow. If you are unfamiliar with either one of these platforms, you can check out their respective documentations [here](https://viash.io/guides/getting_started/introduction/) and [here](https://www.nextflow.io/docs/latest/index.html). To start contributing to openpipelines, you will need at least a working version of Java 11, OpenJDK 11, or a later version (up to Java 18). Additionally, by using [Docker](https://www.docker.com/), you can build and test pipeline components and pipelines without needing to manually install dependencies for these components on your machine.

Viash and Nextflow can be installed by following the guides in the documentation for both of these tools. However, openpipelines provides a setup script that downloads the binaries for the versions that openpipelines is currently using. First, fork the openpipelines GitHub repository [here](https://github.com/openpipelines-bio/openpipeline/fork). If you are unfamiliar with this process, please check out the corresponding [Github documentation](https://docs.github.com/en/github/getting-started-with-github/quickstart/fork-a-repo). Next, you can clone your fork and install Viash and Nextflow in the `bin` folder.

```bash
git clone https://github.com/YOUR-USER-NAME/openpipeline.git
cd openpipeline
./bin/init
```