---
title: "Demux"
namespace: "Ingestion"
description: "A generic pipeline for running bcl2fastq, bcl-convert or Cell Ranger mkfastq."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `demux`  
Namespace: `ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main_build/openpipelines/workflows/ingestion/demux){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Convert `.bcl` files to `.fastq` files using bcl2fastq, bcl-convert or Cell Ranger mkfastq.


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script openpipelines/workflows/ingestion/demux/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
id: # please fill in - example: "foo"
input: # please fill in - example: "bcl_dir"
sample_sheet: # please fill in - example: "bcl_dir"
demultiplexer: "bcl2fastq"
# ignore_missing: true

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script openpipelines/workflows/ingestion/demux/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name               |Description                                                    |Attributes                             |
|:------------------|:--------------------------------------------------------------|:--------------------------------------|
|`--id`             |ID of the sample.                                              |`string`, required, example: `"foo"`   |
|`--input`          |Input run directory                                            |`file`, required, example: `"bcl_dir"` |
|`--sample_sheet`   |Pointer to the sample sheet                                    |`file`, required, example: `"bcl_dir"` |
|`--demultiplexer`  |The multiplexer to use, one of bclconvert or mkfastq           |`string`, default: `"bcl2fastq"`       |
|`--ignore_missing` |Should the demultiplexer ignore missing entities (filter, ...) |`boolean`                              |

## Authors

  * Toni Verbeiren [{{< fa brands github >}}](https://github.com/tverbeiren) (author, maintainer)
  * Marijke Van Moerbeke [{{< fa brands orcid >}}](https://orcid.org/0000-0002-3097-5621) (author)
  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Samuel D'Souza [{{< fa brands github >}}](https://github.com/srdsam) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p2(toSortedList)
    p4(flatMap)
    p5(filter)
    p13(join)
    p11(cellranger_mkfastq)
    p35(mix)
    p15(filter)
    p23(join)
    p21(bcl_convert)
    p25(filter)
    p33(join)
    p31(bcl2fastq)
    p44(join)
    p42(fastqc)
    p46(Output)
    p48(toSortedList)
    p57(join)
    p55(multiqc)
    p59(Output)
    p63(Output)
    p4-->p5
    p4-->p15
    p4-->p25
    p0-->p2
    p2-->p4
    p5-->p13
    p5-->p11
    p11-->p13
    p13-->p35
    p15-->p23
    p15-->p21
    p21-->p23
    p23-->p35
    p25-->p33
    p25-->p31
    p31-->p33
    p33-->p35
    p35-->p44
    p35-->p42
    p42-->p44
    p44-->p46
    p35-->p48
    p48-->p57
    p48-->p55
    p55-->p57
    p57-->p59
    p35-->p63

```
