---
title: "Make reference"
namespace: "Ingestion"
description: "Build a transcriptomics reference into one of many formats"
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `make_reference`  
Namespace: `ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/experiment_website_push/workflows/ingestion/make_reference){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r experiment_website_push -latest \
  -main-script workflows/ingestion/make_reference/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r experiment_website_push -latest \
  -profile docker \
  -main-script workflows/ingestion/make_reference/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name                  |Description                         |Attributes                                                                                                                              |
|:---------------------|:-----------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------|
|`--id`                |ID of the reference.                |`string`, required, example: `"foo"`                                                                                                    |
|`--genome_fasta`      |Reference genome fasta.             |`file`, required, example: `"https:/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh38.primary_assembly.genome.fa.gz"` |
|`--transcriptome_gtf` |Reference transcriptome annotation. |`file`, required, example: `"https:/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz"`        |
|`--ercc`              |ERCC sequence and annotation file.  |`file`, example: `"https:/assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip"`                                                   |


### Outputs

|Name                   |Description                          |Attributes                                           |
|:----------------------|:------------------------------------|:----------------------------------------------------|
|`--target`             |Which reference indices to generate. |`string`, default: `"star"`                          |
|`--output_fasta`       |Output genome sequence fasta.        |`file`, example: `"genome_sequence.fa.gz"`           |
|`--output_gtf`         |Output transcriptome annotation gtf. |`file`, example: `"transcriptome_annotation.gtf.gz"` |
|`--output_cellranger`  |Output index                         |`file`, example: `"cellranger_index.tar.gz"`         |
|`--output_bd_rhapsody` |Output index                         |`file`, example: `"bdrhap_index.tar.gz"`             |
|`--output_star`        |Output index                         |`file`, example: `"star_index.tar.gz"`               |


### Arguments

|Name             |Description                                                  |Attributes                                    |
|:----------------|:------------------------------------------------------------|:---------------------------------------------|
|`--subset_regex` |Will subset the reference chromosomes using the given regex. |`string`, example: `"(ERCC-00002&#124;chr1)"` |

## Authors

  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p2(toSortedList)
    p4(flatMap)
    p14(join)
    p12(make_reference)
    p17(filter)
    p25(join)
    p23(build_cellranger_reference)
    p54(join)
    p29(filter)
    p37(join)
    p35(build_bdrhap_reference)
    p55(join)
    p41(filter)
    p49(join)
    p47(star_build_reference)
    p56(join)
    p57(join)
    p62(Output)
    p54-->p55
    p55-->p56
    p56-->p57
    p0-->p2
    p2-->p4
    p4-->p14
    p4-->p12
    p12-->p14
    p14-->p17
    p17-->p25
    p17-->p23
    p23-->p25
    p25-->p54
    p14-->p29
    p29-->p37
    p29-->p35
    p35-->p37
    p37-->p55
    p14-->p41
    p41-->p49
    p41-->p47
    p47-->p49
    p49-->p56
    p0-->p57
    p14-->p54
    p57-->p62

```
