---
title: "Harmony integration followed by KNN label transfer"
namespace: "Workflows/annotation"
description: "Cell type annotation workflow by performing harmony integration of reference and query dataset followed by KNN label transfer."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `harmony_knn`  
Namespace: `workflows/annotation`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.1.1/src/workflows/annotation/harmony_knn/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -main-script target/nextflow/workflows/annotation/harmony_knn/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Query Input
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"
modality: "rna"
# input_layer: "foo"
input_obs_batch_label: # please fill in - example: "sample"
# input_var_gene_names: "foo"
input_reference_gene_overlap: 100
overwrite_existing_key: false

# Reference input
reference: # please fill in - example: "reference.h5mu"
# reference_layer: "foo"
reference_obs_target: # please fill in - example: "cell_type"
# reference_var_gene_names: "foo"
reference_obs_batch_label: # please fill in - example: "sample"

# HVG subset arguments
n_hvg: 2000

# PCA options
# pca_num_components: 25

# Harmony integration options
harmony_theta: [2.0]

# Leiden clustering options
leiden_resolution: [1.0]

# Neighbor classifier arguments
knn_weights: "uniform"
knn_n_neighbors: 15

# Outputs
# output: "$id.$key.output.h5mu"
# output_obs_predictions: ["foo"]
# output_obs_probability: ["foo"]
output_obsm_integrated: "X_integrated_harmony"
# output_compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/annotation/harmony_knn/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Query Input

|Name                             |Description                                                                                                                                 |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`                           |ID of the sample.                                                                                                                           |`string`, required, example: `"foo"`      |
|`--input`                        |Input dataset consisting of the (unlabeled) query observations. The dataset is expected to be pre-processed in the same way as --reference. |`file`, required, example: `"input.h5mu"` |
|`--modality`                     |Which modality to process. Should match the modality of the --reference dataset.                                                            |`string`, default: `"rna"`                |
|`--input_layer`                  |The layer of the input dataset to process if .X is not to be used. Should contain log normalized counts.                                    |`string`                                  |
|`--input_obs_batch_label`        |The .obs field in the input (query) dataset containing the batch labels.                                                                    |`string`, required, example: `"sample"`   |
|`--input_var_gene_names`         |The .var field in the input (query) dataset containing gene names; if not provided, the .var index will be used.                            |`string`                                  |
|`--input_reference_gene_overlap` |The minimum number of genes present in both the reference and query datasets.                                                               |`integer`, default: `100`                 |
|`--overwrite_existing_key`       |If provided, will overwrite existing fields in the input dataset when data are copied during the reference alignment process.               |`boolean_true`                            |


### Reference input

|Name                          |Description                                                                                                                                                                        |Attributes                                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--reference`                 |Reference dataset consisting of the labeled observations to train the KNN classifier on. The dataset is expected to be pre-processed in the same way as the --input query dataset. |`file`, required, example: `"reference.h5mu"` |
|`--reference_layer`           |The layer of the reference dataset to process if .X is not to be used. Should contain log normalized counts.                                                                       |`string`                                      |
|`--reference_obs_target`      |The `.obs` key of the target cell type labels to transfer.                                                                                                                         |`string`, required, example: `"cell_type"`    |
|`--reference_var_gene_names`  |The .var field in the reference dataset containing gene names; if not provided, the .var index will be used.                                                                       |`string`                                      |
|`--reference_obs_batch_label` |The .obs field in the reference dataset containing the batch labels.                                                                                                               |`string`, required, example: `"sample"`       |


### HVG subset arguments

|Name      |Description                                    |Attributes                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--n_hvg` |Number of highly variable genes to subset for. |`integer`, default: `2000` |


### PCA options

|Name                   |Description                                                                                                          |Attributes               |
|:----------|:--------------------------------------------------|:--------------------|
|`--pca_num_components` |Number of principal components to compute. Defaults to 50, or 1 - minimum dimension size of selected representation. |`integer`, example: `25` |


### Harmony integration options

|Name              |Description                                                                                                                                                                                                                                                                                           |Attributes                                          |
|:----------|:--------------------------------------------------|:--------------------|
|`--harmony_theta` |Diversity clustering penalty parameter. Can be set as a single value for all batch observations or as multiple values, one for each observation in the batches defined by --input_obs_batch_label. theta=0 does not encourage any diversity. Larger values of theta result in more diverse clusters." |List of `double`, default: `2`, multiple_sep: `";"` |


### Leiden clustering options

|Name                  |Description                                                                    |Attributes                                          |
|:----------|:--------------------------------------------------|:--------------------|
|`--leiden_resolution` |Control the coarseness of the clustering. Higher values lead to more clusters. |List of `double`, default: `1`, multiple_sep: `";"` |


### Neighbor classifier arguments

|Name                |Description                                                                                                                                                                                                                  |Attributes                     |
|:----------|:--------------------------------------------------|:--------------------|
|`--knn_weights`     |Weight function used in prediction. Possible values are: `uniform` (all points in each neighborhood are weighted equally) or  `distance` (weight points by the inverse of their distance)                                    |`string`, default: `"uniform"` |
|`--knn_n_neighbors` |The number of neighbors to use in k-neighbor graph structure used for fast approximate nearest neighbor search with PyNNDescent.  Larger values will result in more accurate search results at the cost of computation time. |`integer`, default: `15`       |


### Outputs

|Name                       |Description                                                                                                                                                                                                                              |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`                 |The annotated output .h5mu file.                                                                                                                                                                                                         |`file`, required, example: `"output.h5mu"`  |
|`--output_obs_predictions` |In which `.obs` slots to store the predicted cell labels. If provided, must have the same length as `--reference_obs_targets`. If empty, will default to the `reference_obs_targets` combined with the `"_pred"` suffix.                 |List of `string`, multiple_sep: `";"`       |
|`--output_obs_probability` |In which `.obs` slots to store the probability of the predictions. If provided, must have the same length as `--reference_obs_targets`. If empty, will default to the `reference_obs_targets` combined with the `"_probability"` suffix. |List of `string`, multiple_sep: `";"`       |
|`--output_obsm_integrated` |In which .obsm slot to store the integrated embedding.                                                                                                                                                                                   |`string`, default: `"X_integrated_harmony"` |
|`--output_compression`     |The compression format to be used on the output h5mu object.                                                                                                                                                                             |`string`, example: `"gzip"`                 |

## Authors


  * Dorien Roosen [{{< fa brands github >}}](https://github.com/dorien-er) [{{< fa brands linkedin >}}](https://linkedin.com/in/dorien-roosen) (author, maintainer)

  * Weiwei Schultz (contributor)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v10(filter)
    v18(align_query_reference)
    v25(cross)
    v35(cross)
    v41(filter)
    v52(filter)
    v64(cross)
    v74(cross)
    v84(concat)
    v91(cross)
    v101(cross)
    v107(flatMap)
    v111(filter)
    v119(concatenate_h5mu)
    v126(cross)
    v136(cross)
    v143(filter)
    v151(highly_variable_features_scanpy)
    v158(cross)
    v168(cross)
    v174(filter)
    v182(pca)
    v189(cross)
    v199(cross)
    v205(filter)
    v213(delete_aligned_lognormalized_counts_layer)
    v220(cross)
    v230(cross)
    v236(filter)
    v248(branch)
    v275(concat)
    v260(cross)
    v270(cross)
    v276(filter)
    v291(cross)
    v301(cross)
    v307(filter)
    v316(filter)
    v331(cross)
    v341(cross)
    v350(branch)
    v377(concat)
    v362(cross)
    v372(cross)
    v381(branch)
    v408(concat)
    v393(cross)
    v403(cross)
    v412(branch)
    v439(concat)
    v424(cross)
    v434(cross)
    v446(cross)
    v456(cross)
    v465(branch)
    v492(concat)
    v477(cross)
    v487(cross)
    v496(branch)
    v523(concat)
    v508(cross)
    v518(cross)
    v530(cross)
    v540(cross)
    v547(filter)
    v558(filter)
    v570(cross)
    v580(cross)
    v590(concat)
    v597(cross)
    v607(cross)
    v616(filter)
    v624(knn)
    v631(cross)
    v641(cross)
    v649(mix)
    v652(filter)
    v682(concat)
    v660(merge)
    v667(cross)
    v677(cross)
    v689(cross)
    v696(cross)
    v708(cross)
    v715(cross)
    v719(Output)
    subgraph group_split_modalities [split_modalities]
        v57(split_modalities_component)
    end
    subgraph group_harmony_leiden_workflow [harmony_leiden_workflow]
        v253(from_tiledb_to_h5mu)
        v284(harmonypy)
        v324(find_neighbors)
        v355(leiden)
        v386(move_obsm_to_obs)
        v417(umap)
        v470(move_mudata_obsm_to_tiledb)
        v501(move_mudata_obs_to_tiledb)
    end
    subgraph group_split_h5mu [split_h5mu]
        v563(split_h5mu_component)
    end
    v248-->v275
    v275-->v276
    v350-->v377
    v381-->v408
    v412-->v439
    v465-->v492
    v496-->v523
    v0-->v2
    v2-->v10
    v10-->v18
    v18-->v25
    v10-->v25
    v10-->v35
    v52-->v57
    v57-->v64
    v52-->v64
    v52-->v74
    v84-->v91
    v41-->v91
    v41-->v101
    v111-->v119
    v119-->v126
    v111-->v126
    v111-->v136
    v143-->v151
    v151-->v158
    v143-->v158
    v143-->v168
    v174-->v182
    v182-->v189
    v174-->v189
    v174-->v199
    v205-->v213
    v213-->v220
    v205-->v220
    v205-->v230
    v248-->v253
    v253-->v260
    v248-->v260
    v248-->v270
    v270-->v275
    v276-->v284
    v284-->v291
    v276-->v291
    v276-->v301
    v307-->v316
    v316-->v324
    v324-->v331
    v316-->v331
    v316-->v341
    v350-->v355
    v355-->v362
    v350-->v362
    v350-->v372
    v372-->v377
    v381-->v386
    v386-->v393
    v381-->v393
    v381-->v403
    v403-->v408
    v412-->v417
    v417-->v424
    v412-->v424
    v412-->v434
    v434-->v439
    v439-->v446
    v307-->v446
    v307-->v456
    v465-->v470
    v470-->v477
    v465-->v477
    v465-->v487
    v487-->v492
    v496-->v501
    v501-->v508
    v496-->v508
    v496-->v518
    v518-->v523
    v523-->v530
    v236-->v530
    v236-->v540
    v558-->v563
    v563-->v570
    v558-->v570
    v558-->v580
    v590-->v597
    v547-->v597
    v547-->v607
    v616-->v624
    v624-->v631
    v616-->v631
    v616-->v641
    v652-->v660
    v660-->v667
    v652-->v667
    v652-->v677
    v677-->v682
    v682-->v689
    v2-->v689
    v689-->v696
    v2-->v696
    v2-->v708
    v708-->v715
    v2-->v715
    v715-->v719
    v35-->v41
    v18-->v35
    v101-->v107
    v41-->v52
    v74-->v84
    v57-->v74
    v84-->v101
    v107-->v111
    v136-->v143
    v119-->v136
    v168-->v174
    v151-->v168
    v199-->v205
    v182-->v199
    v230-->v236
    v213-->v230
    v540-->v547
    v236-->v248
    v253-->v270
    v301-->v307
    v284-->v301
    v324-->v341
    v341-->v350
    v355-->v372
    v377-->v381
    v386-->v403
    v408-->v412
    v417-->v434
    v439-->v456
    v456-->v465
    v470-->v487
    v492-->v496
    v501-->v518
    v523-->v540
    v607-->v616
    v547-->v558
    v580-->v590
    v563-->v580
    v590-->v607
    v641-->v649
    v624-->v641
    v107-->v649
    v649-->v652
    v660-->v677
    v682-->v708
    style group_split_modalities fill:#F0F0F0,stroke:#969696;
    style group_harmony_leiden_workflow fill:#F0F0F0,stroke:#969696;
    style group_split_h5mu fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v10 fill:#e3dcea,stroke:#7a4baa;
    style v18 fill:#e3dcea,stroke:#7a4baa;
    style v25 fill:#e3dcea,stroke:#7a4baa;
    style v35 fill:#e3dcea,stroke:#7a4baa;
    style v41 fill:#e3dcea,stroke:#7a4baa;
    style v52 fill:#e3dcea,stroke:#7a4baa;
    style v57 fill:#e3dcea,stroke:#7a4baa;
    style v64 fill:#e3dcea,stroke:#7a4baa;
    style v74 fill:#e3dcea,stroke:#7a4baa;
    style v84 fill:#e3dcea,stroke:#7a4baa;
    style v91 fill:#e3dcea,stroke:#7a4baa;
    style v101 fill:#e3dcea,stroke:#7a4baa;
    style v107 fill:#e3dcea,stroke:#7a4baa;
    style v111 fill:#e3dcea,stroke:#7a4baa;
    style v119 fill:#e3dcea,stroke:#7a4baa;
    style v126 fill:#e3dcea,stroke:#7a4baa;
    style v136 fill:#e3dcea,stroke:#7a4baa;
    style v143 fill:#e3dcea,stroke:#7a4baa;
    style v151 fill:#e3dcea,stroke:#7a4baa;
    style v158 fill:#e3dcea,stroke:#7a4baa;
    style v168 fill:#e3dcea,stroke:#7a4baa;
    style v174 fill:#e3dcea,stroke:#7a4baa;
    style v182 fill:#e3dcea,stroke:#7a4baa;
    style v189 fill:#e3dcea,stroke:#7a4baa;
    style v199 fill:#e3dcea,stroke:#7a4baa;
    style v205 fill:#e3dcea,stroke:#7a4baa;
    style v213 fill:#e3dcea,stroke:#7a4baa;
    style v220 fill:#e3dcea,stroke:#7a4baa;
    style v230 fill:#e3dcea,stroke:#7a4baa;
    style v236 fill:#e3dcea,stroke:#7a4baa;
    style v248 fill:#e3dcea,stroke:#7a4baa;
    style v275 fill:#e3dcea,stroke:#7a4baa;
    style v253 fill:#e3dcea,stroke:#7a4baa;
    style v260 fill:#e3dcea,stroke:#7a4baa;
    style v270 fill:#e3dcea,stroke:#7a4baa;
    style v276 fill:#e3dcea,stroke:#7a4baa;
    style v284 fill:#e3dcea,stroke:#7a4baa;
    style v291 fill:#e3dcea,stroke:#7a4baa;
    style v301 fill:#e3dcea,stroke:#7a4baa;
    style v307 fill:#e3dcea,stroke:#7a4baa;
    style v316 fill:#e3dcea,stroke:#7a4baa;
    style v324 fill:#e3dcea,stroke:#7a4baa;
    style v331 fill:#e3dcea,stroke:#7a4baa;
    style v341 fill:#e3dcea,stroke:#7a4baa;
    style v350 fill:#e3dcea,stroke:#7a4baa;
    style v377 fill:#e3dcea,stroke:#7a4baa;
    style v355 fill:#e3dcea,stroke:#7a4baa;
    style v362 fill:#e3dcea,stroke:#7a4baa;
    style v372 fill:#e3dcea,stroke:#7a4baa;
    style v381 fill:#e3dcea,stroke:#7a4baa;
    style v408 fill:#e3dcea,stroke:#7a4baa;
    style v386 fill:#e3dcea,stroke:#7a4baa;
    style v393 fill:#e3dcea,stroke:#7a4baa;
    style v403 fill:#e3dcea,stroke:#7a4baa;
    style v412 fill:#e3dcea,stroke:#7a4baa;
    style v439 fill:#e3dcea,stroke:#7a4baa;
    style v417 fill:#e3dcea,stroke:#7a4baa;
    style v424 fill:#e3dcea,stroke:#7a4baa;
    style v434 fill:#e3dcea,stroke:#7a4baa;
    style v446 fill:#e3dcea,stroke:#7a4baa;
    style v456 fill:#e3dcea,stroke:#7a4baa;
    style v465 fill:#e3dcea,stroke:#7a4baa;
    style v492 fill:#e3dcea,stroke:#7a4baa;
    style v470 fill:#e3dcea,stroke:#7a4baa;
    style v477 fill:#e3dcea,stroke:#7a4baa;
    style v487 fill:#e3dcea,stroke:#7a4baa;
    style v496 fill:#e3dcea,stroke:#7a4baa;
    style v523 fill:#e3dcea,stroke:#7a4baa;
    style v501 fill:#e3dcea,stroke:#7a4baa;
    style v508 fill:#e3dcea,stroke:#7a4baa;
    style v518 fill:#e3dcea,stroke:#7a4baa;
    style v530 fill:#e3dcea,stroke:#7a4baa;
    style v540 fill:#e3dcea,stroke:#7a4baa;
    style v547 fill:#e3dcea,stroke:#7a4baa;
    style v558 fill:#e3dcea,stroke:#7a4baa;
    style v563 fill:#e3dcea,stroke:#7a4baa;
    style v570 fill:#e3dcea,stroke:#7a4baa;
    style v580 fill:#e3dcea,stroke:#7a4baa;
    style v590 fill:#e3dcea,stroke:#7a4baa;
    style v597 fill:#e3dcea,stroke:#7a4baa;
    style v607 fill:#e3dcea,stroke:#7a4baa;
    style v616 fill:#e3dcea,stroke:#7a4baa;
    style v624 fill:#e3dcea,stroke:#7a4baa;
    style v631 fill:#e3dcea,stroke:#7a4baa;
    style v641 fill:#e3dcea,stroke:#7a4baa;
    style v649 fill:#e3dcea,stroke:#7a4baa;
    style v652 fill:#e3dcea,stroke:#7a4baa;
    style v682 fill:#e3dcea,stroke:#7a4baa;
    style v660 fill:#e3dcea,stroke:#7a4baa;
    style v667 fill:#e3dcea,stroke:#7a4baa;
    style v677 fill:#e3dcea,stroke:#7a4baa;
    style v689 fill:#e3dcea,stroke:#7a4baa;
    style v696 fill:#e3dcea,stroke:#7a4baa;
    style v708 fill:#e3dcea,stroke:#7a4baa;
    style v715 fill:#e3dcea,stroke:#7a4baa;
    style v719 fill:#e3dcea,stroke:#7a4baa;

```

