---
title: "scVI Annotation"
namespace: "Workflows/annotation"
description: ""Cell type annotation workflow that performs scVI integration of reference and query dataset followed by KNN label transfer."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `scvi_knn`  
Namespace: `workflows/annotation`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.0.1/src/workflows/annotation/scvi_knn/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::


The query and reference datasets are expected to be pre-processed in the same way, for example with the `process_samples` workflow of OpenPipeline. Note that this workflow will integrate the reference dataset from scratch and integrate the query dataset in the same embedding space. 
The workflow does not currently output the trained SCVI reference model."


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.1 -latest \
  -main-script target/nextflow/workflows/annotation/scvi_knn/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Query Input
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"
modality: "rna"
# input_layer: "counts"
# input_layer_lognormalized: "log_normalized"
input_obs_batch_label: # please fill in - example: "sample"
# input_var_gene_names: "foo"
input_reference_gene_overlap: 100
overwrite_existing_key: false
sanitize_ensembl_ids: true

# Reference input
reference: # please fill in - example: "reference.h5mu"
# reference_layer: "counts"
# reference_layer_lognormalized: "log_normalized"
reference_obs_target: # please fill in - example: "cell_type"
# reference_var_gene_names: "foo"
reference_obs_batch_label: # please fill in - example: "sample"

# HVG subset arguments
n_hvg: 2000

# scVI integration options
# scvi_early_stopping: true
scvi_early_stopping_monitor: "elbo_validation"
scvi_early_stopping_patience: 45
scvi_early_stopping_min_delta: 0.0
# scvi_max_epochs: 123
scvi_reduce_lr_on_plateau: true
scvi_lr_factor: 0.6
scvi_lr_patience: 30.0

# Leiden clustering options
leiden_resolution: [1.0]

# Neighbor classifier arguments
knn_weights: "uniform"
knn_n_neighbors: 15

# Outputs
# output: "$id.$key.output.h5mu"
# output_obs_predictions: ["foo"]
# output_obs_probability: ["foo"]
output_obsm_integrated: "X_integrated_scvi"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/annotation/scvi_knn/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Query Input

|Name                             |Description                                                                                                                   |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`                           |ID of the sample.                                                                                                             |`string`, required, example: `"foo"`      |
|`--input`                        |Input dataset consisting of the (unlabeled) query observations.                                                               |`file`, required, example: `"input.h5mu"` |
|`--modality`                     |Which modality to process. Should match the modality of the --reference dataset.                                              |`string`, default: `"rna"`                |
|`--input_layer`                  |The layer of the input dataset containing the raw counts if .X is not to be used.                                             |`string`, example: `"counts"`             |
|`--input_layer_lognormalized`    |The layer of the input dataset containing the lognormalized counts if .X is not to be used.                                   |`string`, example: `"log_normalized"`     |
|`--input_obs_batch_label`        |The .obs field in the input (query) dataset containing the batch labels.                                                      |`string`, required, example: `"sample"`   |
|`--input_var_gene_names`         |The .var field in the input (query) dataset containing gene names; if not provided, the .var index will be used.              |`string`                                  |
|`--input_reference_gene_overlap` |The minimum number of genes present in both the reference and query datasets.                                                 |`integer`, default: `100`                 |
|`--overwrite_existing_key`       |If provided, will overwrite existing fields in the input dataset when data are copied during the reference alignment process. |`boolean_true`                            |
|`--sanitize_ensembl_ids`         |Whether to sanitize ensembl ids by removing version numbers.                                                                  |`boolean`, default: `TRUE`                |


### Reference input

|Name                              |Description                                                                                                  |Attributes                                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--reference`                     |Reference dataset consisting of the labeled observations.                                                    |`file`, required, example: `"reference.h5mu"` |
|`--reference_layer`               |The layer of the reference dataset containing the raw counts if .X is not to be used.                        |`string`, example: `"counts"`                 |
|`--reference_layer_lognormalized` |The layer of the reference dataset containing the lognormalized counts if .X is not to be used.              |`string`, example: `"log_normalized"`         |
|`--reference_obs_target`          |The `.obs` key(s) of the target labels to transfer.                                                          |`string`, required, example: `"cell_type"`    |
|`--reference_var_gene_names`      |The .var field in the reference dataset containing gene names; if not provided, the .var index will be used. |`string`                                      |
|`--reference_obs_batch_label`     |The .obs field in the reference dataset containing the batch labels.                                         |`string`, required, example: `"sample"`       |


### HVG subset arguments

|Name      |Description                                    |Attributes                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--n_hvg` |Number of highly variable genes to subset for. |`integer`, default: `2000` |


### scVI integration options

|Name                              |Description                                                                                                                                          |Attributes                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--scvi_early_stopping`           |Whether to perform early stopping with respect to the validation set.                                                                                |`boolean`                              |
|`--scvi_early_stopping_monitor`   |Metric logged during validation set epoch.                                                                                                           |`string`, default: `"elbo_validation"` |
|`--scvi_early_stopping_patience`  |Number of validation epochs with no improvement after which training will be stopped.                                                                |`integer`, default: `45`               |
|`--scvi_early_stopping_min_delta` |Minimum change in the monitored quantity to qualify as an improvement, i.e. an absolute change of less than min_delta, will count as no improvement. |`double`, default: `0`                 |
|`--scvi_max_epochs`               |Number of passes through the dataset, defaults to (20000 / number of cells) * 400 or 400; whichever is smallest.                                     |`integer`                              |
|`--scvi_reduce_lr_on_plateau`     |Whether to monitor validation loss and reduce learning rate when validation set `lr_scheduler_metric` plateaus.                                      |`boolean`, default: `TRUE`             |
|`--scvi_lr_factor`                |Factor to reduce learning rate.                                                                                                                      |`double`, default: `0.6`               |
|`--scvi_lr_patience`              |Number of epochs with no improvement after which learning rate will be reduced.                                                                      |`double`, default: `30`                |


### Leiden clustering options

|Name                  |Description                                                                    |Attributes                                          |
|:----------|:--------------------------------------------------|:--------------------|
|`--leiden_resolution` |Control the coarseness of the clustering. Higher values lead to more clusters. |List of `double`, default: `1`, multiple_sep: `";"` |


### Neighbor classifier arguments

|Name                |Description                                                                                                                                                                                                                  |Attributes                     |
|:----------|:--------------------------------------------------|:--------------------|
|`--knn_weights`     |Weight function used in prediction. Possible values are: `uniform` (all points in each neighborhood are weighted equally) or  `distance` (weight points by the inverse of their distance)                                    |`string`, default: `"uniform"` |
|`--knn_n_neighbors` |The number of neighbors to use in k-neighbor graph structure used for fast approximate nearest neighbor search with PyNNDescent.  Larger values will result in more accurate search results at the cost of computation time. |`integer`, default: `15`       |


### Outputs

|Name                       |Description                                                                                                                                                                                                                              |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`                 |The query data in .h5mu format with predicted labels predicted from the classifier trained on the reference.                                                                                                                             |`file`, required, example: `"output.h5mu"` |
|`--output_obs_predictions` |In which `.obs` slots to store the predicted cell labels. If provided, must have the same length as `--reference_obs_targets`. If empty, will default to the `reference_obs_targets` combined with the `"_pred"` suffix.                 |List of `string`, multiple_sep: `";"`      |
|`--output_obs_probability` |In which `.obs` slots to store the probability of the predictions. If provided, must have the same length as `--reference_obs_targets`. If empty, will default to the `reference_obs_targets` combined with the `"_probability"` suffix. |List of `string`, multiple_sep: `";"`      |
|`--output_obsm_integrated` |In which .obsm slot to store the integrated embedding.                                                                                                                                                                                   |`string`, default: `"X_integrated_scvi"`   |

## Authors


  * Dorien Roosen [{{< fa brands github >}}](https://github.com/dorien-er) [{{< fa brands linkedin >}}](https://linkedin.com/in/dorien-roosen) (author, maintainer)

  * Weiwei Schultz (contributor)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v10(filter)
    v18(align_query_reference)
    v25(cross)
    v35(cross)
    v41(filter)
    v52(filter)
    v64(cross)
    v74(cross)
    v84(concat)
    v91(cross)
    v101(cross)
    v107(flatMap)
    v111(filter)
    v119(concatenate_h5mu)
    v126(cross)
    v136(cross)
    v142(filter)
    v150(highly_variable_features_scanpy)
    v157(cross)
    v167(cross)
    v173(filter)
    v181(delete_aligned_lognormalized_counts_layer)
    v188(cross)
    v198(cross)
    v204(filter)
    v216(branch)
    v243(concat)
    v228(cross)
    v238(cross)
    v244(filter)
    v259(cross)
    v269(cross)
    v275(filter)
    v284(filter)
    v299(cross)
    v309(cross)
    v318(branch)
    v345(concat)
    v330(cross)
    v340(cross)
    v349(branch)
    v376(concat)
    v361(cross)
    v371(cross)
    v380(branch)
    v407(concat)
    v392(cross)
    v402(cross)
    v414(cross)
    v424(cross)
    v433(branch)
    v460(concat)
    v445(cross)
    v455(cross)
    v464(branch)
    v491(concat)
    v476(cross)
    v486(cross)
    v498(cross)
    v508(cross)
    v514(filter)
    v522(delete_aligned_counts_layer)
    v529(cross)
    v539(cross)
    v545(filter)
    v556(filter)
    v568(cross)
    v578(cross)
    v588(concat)
    v595(cross)
    v605(cross)
    v613(filter)
    v621(knn)
    v628(cross)
    v638(cross)
    v646(mix)
    v649(filter)
    v679(concat)
    v657(merge)
    v664(cross)
    v674(cross)
    v686(cross)
    v693(cross)
    v705(cross)
    v712(cross)
    v716(Output)
    subgraph group_split_modalities [split_modalities]
        v57(split_modalities_component)
    end
    subgraph group_scvi_leiden_workflow [scvi_leiden_workflow]
        v221(from_tiledb_to_h5mu)
        v252(scvi)
        v292(find_neighbors)
        v323(leiden)
        v354(move_obsm_to_obs)
        v385(umap)
        v438(move_mudata_obsm_to_tiledb)
        v469(move_mudata_obs_to_tiledb)
    end
    subgraph group_split_h5mu [split_h5mu]
        v561(split_h5mu_component)
    end
    v216-->v243
    v243-->v244
    v318-->v345
    v349-->v376
    v380-->v407
    v433-->v460
    v464-->v491
    v0-->v2
    v2-->v10
    v10-->v18
    v18-->v25
    v10-->v25
    v10-->v35
    v52-->v57
    v57-->v64
    v52-->v64
    v52-->v74
    v84-->v91
    v41-->v91
    v41-->v101
    v111-->v119
    v119-->v126
    v111-->v126
    v111-->v136
    v142-->v150
    v150-->v157
    v142-->v157
    v142-->v167
    v173-->v181
    v181-->v188
    v173-->v188
    v173-->v198
    v216-->v221
    v221-->v228
    v216-->v228
    v216-->v238
    v238-->v243
    v244-->v252
    v252-->v259
    v244-->v259
    v244-->v269
    v275-->v284
    v284-->v292
    v292-->v299
    v284-->v299
    v284-->v309
    v318-->v323
    v323-->v330
    v318-->v330
    v318-->v340
    v340-->v345
    v349-->v354
    v354-->v361
    v349-->v361
    v349-->v371
    v371-->v376
    v380-->v385
    v385-->v392
    v380-->v392
    v380-->v402
    v402-->v407
    v407-->v414
    v275-->v414
    v275-->v424
    v433-->v438
    v438-->v445
    v433-->v445
    v433-->v455
    v455-->v460
    v464-->v469
    v469-->v476
    v464-->v476
    v464-->v486
    v486-->v491
    v491-->v498
    v204-->v498
    v204-->v508
    v514-->v522
    v522-->v529
    v514-->v529
    v514-->v539
    v556-->v561
    v561-->v568
    v556-->v568
    v556-->v578
    v588-->v595
    v545-->v595
    v545-->v605
    v613-->v621
    v621-->v628
    v613-->v628
    v613-->v638
    v649-->v657
    v657-->v664
    v649-->v664
    v649-->v674
    v674-->v679
    v679-->v686
    v2-->v686
    v686-->v693
    v2-->v693
    v2-->v705
    v705-->v712
    v2-->v712
    v712-->v716
    v35-->v41
    v18-->v35
    v101-->v107
    v41-->v52
    v74-->v84
    v57-->v74
    v84-->v101
    v107-->v111
    v136-->v142
    v119-->v136
    v167-->v173
    v150-->v167
    v198-->v204
    v181-->v198
    v508-->v514
    v204-->v216
    v221-->v238
    v269-->v275
    v252-->v269
    v292-->v309
    v309-->v318
    v323-->v340
    v345-->v349
    v354-->v371
    v376-->v380
    v385-->v402
    v407-->v424
    v424-->v433
    v438-->v455
    v460-->v464
    v469-->v486
    v491-->v508
    v539-->v545
    v522-->v539
    v605-->v613
    v545-->v556
    v578-->v588
    v561-->v578
    v588-->v605
    v638-->v646
    v621-->v638
    v107-->v646
    v646-->v649
    v657-->v674
    v679-->v705
    style group_split_modalities fill:#F0F0F0,stroke:#969696;
    style group_scvi_leiden_workflow fill:#F0F0F0,stroke:#969696;
    style group_split_h5mu fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v10 fill:#e3dcea,stroke:#7a4baa;
    style v18 fill:#e3dcea,stroke:#7a4baa;
    style v25 fill:#e3dcea,stroke:#7a4baa;
    style v35 fill:#e3dcea,stroke:#7a4baa;
    style v41 fill:#e3dcea,stroke:#7a4baa;
    style v52 fill:#e3dcea,stroke:#7a4baa;
    style v57 fill:#e3dcea,stroke:#7a4baa;
    style v64 fill:#e3dcea,stroke:#7a4baa;
    style v74 fill:#e3dcea,stroke:#7a4baa;
    style v84 fill:#e3dcea,stroke:#7a4baa;
    style v91 fill:#e3dcea,stroke:#7a4baa;
    style v101 fill:#e3dcea,stroke:#7a4baa;
    style v107 fill:#e3dcea,stroke:#7a4baa;
    style v111 fill:#e3dcea,stroke:#7a4baa;
    style v119 fill:#e3dcea,stroke:#7a4baa;
    style v126 fill:#e3dcea,stroke:#7a4baa;
    style v136 fill:#e3dcea,stroke:#7a4baa;
    style v142 fill:#e3dcea,stroke:#7a4baa;
    style v150 fill:#e3dcea,stroke:#7a4baa;
    style v157 fill:#e3dcea,stroke:#7a4baa;
    style v167 fill:#e3dcea,stroke:#7a4baa;
    style v173 fill:#e3dcea,stroke:#7a4baa;
    style v181 fill:#e3dcea,stroke:#7a4baa;
    style v188 fill:#e3dcea,stroke:#7a4baa;
    style v198 fill:#e3dcea,stroke:#7a4baa;
    style v204 fill:#e3dcea,stroke:#7a4baa;
    style v216 fill:#e3dcea,stroke:#7a4baa;
    style v243 fill:#e3dcea,stroke:#7a4baa;
    style v221 fill:#e3dcea,stroke:#7a4baa;
    style v228 fill:#e3dcea,stroke:#7a4baa;
    style v238 fill:#e3dcea,stroke:#7a4baa;
    style v244 fill:#e3dcea,stroke:#7a4baa;
    style v252 fill:#e3dcea,stroke:#7a4baa;
    style v259 fill:#e3dcea,stroke:#7a4baa;
    style v269 fill:#e3dcea,stroke:#7a4baa;
    style v275 fill:#e3dcea,stroke:#7a4baa;
    style v284 fill:#e3dcea,stroke:#7a4baa;
    style v292 fill:#e3dcea,stroke:#7a4baa;
    style v299 fill:#e3dcea,stroke:#7a4baa;
    style v309 fill:#e3dcea,stroke:#7a4baa;
    style v318 fill:#e3dcea,stroke:#7a4baa;
    style v345 fill:#e3dcea,stroke:#7a4baa;
    style v323 fill:#e3dcea,stroke:#7a4baa;
    style v330 fill:#e3dcea,stroke:#7a4baa;
    style v340 fill:#e3dcea,stroke:#7a4baa;
    style v349 fill:#e3dcea,stroke:#7a4baa;
    style v376 fill:#e3dcea,stroke:#7a4baa;
    style v354 fill:#e3dcea,stroke:#7a4baa;
    style v361 fill:#e3dcea,stroke:#7a4baa;
    style v371 fill:#e3dcea,stroke:#7a4baa;
    style v380 fill:#e3dcea,stroke:#7a4baa;
    style v407 fill:#e3dcea,stroke:#7a4baa;
    style v385 fill:#e3dcea,stroke:#7a4baa;
    style v392 fill:#e3dcea,stroke:#7a4baa;
    style v402 fill:#e3dcea,stroke:#7a4baa;
    style v414 fill:#e3dcea,stroke:#7a4baa;
    style v424 fill:#e3dcea,stroke:#7a4baa;
    style v433 fill:#e3dcea,stroke:#7a4baa;
    style v460 fill:#e3dcea,stroke:#7a4baa;
    style v438 fill:#e3dcea,stroke:#7a4baa;
    style v445 fill:#e3dcea,stroke:#7a4baa;
    style v455 fill:#e3dcea,stroke:#7a4baa;
    style v464 fill:#e3dcea,stroke:#7a4baa;
    style v491 fill:#e3dcea,stroke:#7a4baa;
    style v469 fill:#e3dcea,stroke:#7a4baa;
    style v476 fill:#e3dcea,stroke:#7a4baa;
    style v486 fill:#e3dcea,stroke:#7a4baa;
    style v498 fill:#e3dcea,stroke:#7a4baa;
    style v508 fill:#e3dcea,stroke:#7a4baa;
    style v514 fill:#e3dcea,stroke:#7a4baa;
    style v522 fill:#e3dcea,stroke:#7a4baa;
    style v529 fill:#e3dcea,stroke:#7a4baa;
    style v539 fill:#e3dcea,stroke:#7a4baa;
    style v545 fill:#e3dcea,stroke:#7a4baa;
    style v556 fill:#e3dcea,stroke:#7a4baa;
    style v561 fill:#e3dcea,stroke:#7a4baa;
    style v568 fill:#e3dcea,stroke:#7a4baa;
    style v578 fill:#e3dcea,stroke:#7a4baa;
    style v588 fill:#e3dcea,stroke:#7a4baa;
    style v595 fill:#e3dcea,stroke:#7a4baa;
    style v605 fill:#e3dcea,stroke:#7a4baa;
    style v613 fill:#e3dcea,stroke:#7a4baa;
    style v621 fill:#e3dcea,stroke:#7a4baa;
    style v628 fill:#e3dcea,stroke:#7a4baa;
    style v638 fill:#e3dcea,stroke:#7a4baa;
    style v646 fill:#e3dcea,stroke:#7a4baa;
    style v649 fill:#e3dcea,stroke:#7a4baa;
    style v679 fill:#e3dcea,stroke:#7a4baa;
    style v657 fill:#e3dcea,stroke:#7a4baa;
    style v664 fill:#e3dcea,stroke:#7a4baa;
    style v674 fill:#e3dcea,stroke:#7a4baa;
    style v686 fill:#e3dcea,stroke:#7a4baa;
    style v693 fill:#e3dcea,stroke:#7a4baa;
    style v705 fill:#e3dcea,stroke:#7a4baa;
    style v712 fill:#e3dcea,stroke:#7a4baa;
    style v716 fill:#e3dcea,stroke:#7a4baa;

```

