---
title: "Bcl convert"
namespace: "Demux"
description: "Convert bcl files to fastq files using bcl-convert."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `bcl_convert`  
Namespace: `demux`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/0.10.2/./src/demux/bcl_convert){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Information about upgrading from bcl2fastq via
https://emea.support.illumina.com/bulletins/2020/10/upgrading-from-bcl2fastq-to-bcl-convert.html
and https://support.illumina.com/sequencing/sequencing_software/bcl-convert/compatibility.html


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.10.2 -latest \
  -main-script target/nextflow/demux/bcl_convert/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "bcl_dir"
sample_sheet: # please fill in - example: "bcl_dir"
# output: "$id.$key.output.output"
# reports: "$id.$key.reports.reports"
test_mode: false

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.10.2 -latest \
  -profile docker \
  -main-script target/nextflow/demux/bcl_convert/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name             |Description                                                       |Attributes                               |
|:----------------|:-----------------------------------------------------------------|:----------------------------------------|
|`--input`        |Input run directory                                               |`file`, required, example: `"bcl_dir"`   |
|`--sample_sheet` |Pointer to the sample sheet                                       |`file`, required, example: `"bcl_dir"`   |
|`--output`       |Output directory containig fastq files                            |`file`, required, example: `"fastq_dir"` |
|`--reports`      |Reports directory                                                 |`file`, example: `"reports_dir"`         |
|`--test_mode`    |Should bcl-convert be run in test mode (using --first-tile-only)? |`boolean`, default: `FALSE`              |

## Authors


  * Toni Verbeiren [{{< fa brands github >}}](https://github.com/tverbeiren) [{{< fa brands linkedin >}}](https://linkedin.com/in/verbeiren) (author, maintainer)

  * Marijke Van Moerbeke [{{< fa brands github >}}](https://github.com/mvanmoerbeke) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-3097-5621) [{{< fa brands linkedin >}}](https://linkedin.com/in/marijke-van-moerbeke-84303a34) (author)
