---
title: "Log normalize"
namespace: "Workflows/rna"
description: "Performs normalization and subsequent log-transformation of raw count data."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `log_normalize`  
Namespace: `workflows/rna`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.0.2/src/workflows/rna/log_normalize/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.2 -latest \
  -main-script target/_private/nextflow/workflows/rna/log_normalize/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.2 -latest \
  -profile docker \
  -main-script target/_private/nextflow/workflows/rna/log_normalize/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name         |Description                                                      |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`    |MuData file to transform.                                        |`file`, required, example: `"dataset.h5mu"` |
|`--modality` |Modality to process.                                             |`string`, default: `"rna"`                  |
|`--layer`    |Input layer containing raw counts. If not specified, .X is used. |`string`                                    |


### Transormation options

|Name           |Description                                                                                                                                                                                                         |Attributes |
|:----------|:--------------------------------------------------|:--------------------|
|`--target_sum` |Normalize total counts to the specified amount. If not set, after normalization each observation (cell)  will have a total count equal to the median of total counts for observations (cells) before normalization. |`integer`  |


### Output slots

|Name             |Description                                   |Attributes         |
|:----------|:--------------------------------------------------|:--------------------|
|`--output_layer` |Layer to write the log-transformed counts to. |`string`, required |


### Output

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v9(filter)
    v17(normalize_total)
    v24(cross)
    v34(cross)
    v40(filter)
    v48(log1p)
    v55(cross)
    v65(cross)
    v71(filter)
    v101(concat)
    v79(delete_layer)
    v86(cross)
    v96(cross)
    v108(cross)
    v115(cross)
    v127(cross)
    v134(cross)
    v138(Output)
    v0-->v2
    v2-->v9
    v9-->v17
    v17-->v24
    v9-->v24
    v9-->v34
    v40-->v48
    v48-->v55
    v40-->v55
    v40-->v65
    v71-->v79
    v79-->v86
    v71-->v86
    v71-->v96
    v96-->v101
    v101-->v108
    v2-->v108
    v108-->v115
    v2-->v115
    v2-->v127
    v127-->v134
    v2-->v134
    v134-->v138
    v34-->v40
    v17-->v34
    v65-->v71
    v48-->v65
    v79-->v96
    v101-->v127
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v9 fill:#e3dcea,stroke:#7a4baa;
    style v17 fill:#e3dcea,stroke:#7a4baa;
    style v24 fill:#e3dcea,stroke:#7a4baa;
    style v34 fill:#e3dcea,stroke:#7a4baa;
    style v40 fill:#e3dcea,stroke:#7a4baa;
    style v48 fill:#e3dcea,stroke:#7a4baa;
    style v55 fill:#e3dcea,stroke:#7a4baa;
    style v65 fill:#e3dcea,stroke:#7a4baa;
    style v71 fill:#e3dcea,stroke:#7a4baa;
    style v101 fill:#e3dcea,stroke:#7a4baa;
    style v79 fill:#e3dcea,stroke:#7a4baa;
    style v86 fill:#e3dcea,stroke:#7a4baa;
    style v96 fill:#e3dcea,stroke:#7a4baa;
    style v108 fill:#e3dcea,stroke:#7a4baa;
    style v115 fill:#e3dcea,stroke:#7a4baa;
    style v127 fill:#e3dcea,stroke:#7a4baa;
    style v134 fill:#e3dcea,stroke:#7a4baa;
    style v138 fill:#e3dcea,stroke:#7a4baa;

```

