---
title: "Rna multisample"
namespace: "Workflows/rna"
description: "Processing unimodal multi-sample RNA transcriptomics data."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `rna_multisample`  
Namespace: `workflows/rna`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.0.3/src/workflows/rna/rna_multisample/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.3 -latest \
  -main-script target/nextflow/workflows/rna/rna_multisample/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "concatenated"
input: # please fill in - example: "dataset.h5mu"
modality: "rna"
# layer: "foo"

# Output
# output: "$id.$key.output.h5mu"

# Filtering highly variable features
highly_variable_features_var_output: "filter_with_hvg"
highly_variable_features_obs_batch_key: "sample_id"
highly_variable_features_flavor: "seurat"
# highly_variable_features_n_top_features: 123

# QC metrics calculation options
var_qc_metrics: ["filter_with_hvg"]
top_n_vars: [50, 100, 200, 500]
output_obs_num_nonzero_vars: "num_nonzero_vars"
output_obs_total_counts_vars: "total_counts"
output_var_num_nonzero_obs: "num_nonzero_obs"
output_var_total_counts_obs: "total_counts"
output_var_obs_mean: "obs_mean"
output_var_pct_dropout: "pct_dropout"

# RNA Scaling options
enable_scaling: false
scaling_output_layer: "scaled"
# scaling_max_value: 123.0
scaling_zero_center: true

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.0.3 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/rna/rna_multisample/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name         |Description                                       |Attributes                                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`       |ID of the concatenated file                       |`string`, required, example: `"concatenated"` |
|`--input`    |Path to the samples.                              |`file`, required, example: `"dataset.h5mu"`   |
|`--modality` |Modality to process.                              |`string`, default: `"rna"`                    |
|`--layer`    |Input layer to use. If not specified, .X is used. |`string`                                      |


### Output

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### Filtering highly variable features

|Name                                        |Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |Attributes                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--highly_variable_features_var_output`     |In which .var slot to store a boolean array corresponding to the highly variable features.                                                                                                                                                                                                                                                                                                                                                                                                                    |`string`, default: `"filter_with_hvg"` |
|`--highly_variable_features_obs_batch_key`  |If specified, highly-variable features are selected within each batch separately and merged. This simple  process avoids the selection of batch-specific features and acts as a lightweight batch correction method.  For all flavors, featues are first sorted by how many batches they are highly variable. For dispersion-based flavors  ties are broken by normalized dispersion. If flavor = 'seurat_v3', ties are broken by the median (across batches) rank based on within-batch normalized variance. |`string`, default: `"sample_id"`       |
|`--highly_variable_features_flavor`         |Choose the flavor for identifying highly variable features. For the dispersion based methods in their default workflows, Seurat passes the cutoffs whereas Cell Ranger passes n_top_features.                                                                                                                                                                                                                                                                                                                 |`string`, default: `"seurat"`          |
|`--highly_variable_features_n_top_features` |Number of highly-variable features to keep. Mandatory if filter_with_hvg_flavor is set to 'seurat_v3'.                                                                                                                                                                                                                                                                                                                                                                                                        |`integer`                              |


### QC metrics calculation options

|Name                             |Description                                                                                                                                                                                                                    |Attributes                                                                                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--var_qc_metrics`               |Keys to select a boolean (containing only True or False) column from .var. For each cell, calculate the proportion of total values for genes which are labeled 'True',  compared to the total sum of the values for all genes. |List of `string`, default: `"filter_with_hvg"`, example: `"ercc,highly_variable"`, multiple_sep: `","` |
|`--top_n_vars`                   |Number of top vars to be used to calculate cumulative proportions. If not specified, proportions are not calculated. `--top_n_vars 20,50` finds cumulative proportion to the 20th and 50th most expressed vars.                |List of `integer`, default: `50, 100, 200, 500`, multiple_sep: `","`                                   |
|`--output_obs_num_nonzero_vars`  |Name of column in .obs describing, for each observation, the number of stored values (including explicit zeroes). In other words, the name of the column that counts for each row the number of columns that contain data.     |`string`, default: `"num_nonzero_vars"`                                                                |
|`--output_obs_total_counts_vars` |Name of the column for .obs describing, for each observation (row), the sum of the stored values in the columns.                                                                                                               |`string`, default: `"total_counts"`                                                                    |
|`--output_var_num_nonzero_obs`   |Name of column describing, for each feature, the number of stored values (including explicit zeroes). In other words, the name of the column that counts for each column the number of rows that contain data.                 |`string`, default: `"num_nonzero_obs"`                                                                 |
|`--output_var_total_counts_obs`  |Name of the column in .var describing, for each feature (column), the sum of the stored values in the rows.                                                                                                                    |`string`, default: `"total_counts"`                                                                    |
|`--output_var_obs_mean`          |Name of the column in .obs providing the mean of the values in each row.                                                                                                                                                       |`string`, default: `"obs_mean"`                                                                        |
|`--output_var_pct_dropout`       |Name of the column in .obs providing for each feature the percentage of observations the feature does not appear on (i.e. is missing). Same as `--num_nonzero_obs` but percentage based.                                       |`string`, default: `"pct_dropout"`                                                                     |


### RNA Scaling options

Options for enabling scaling of the log-normalized data to unit variance and zero mean.
The scaled data will be output a different layer and representation with reduced dimensions
will be created and stored in addition to the non-scaled data.



|Name                     |Description                                                                              |Attributes                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--enable_scaling`       |Enable scaling for the RNA modality.                                                     |`boolean_true`                |
|`--scaling_output_layer` |Output layer where the scaled log-normalized data will be stored.                        |`string`, default: `"scaled"` |
|`--scaling_max_value`    |Clip (truncate) data to this value after scaling. If not specified, do not clip.         |`double`                      |
|`--scaling_zero_center`  |If set, omit zero-centering variables, which allows to handle sparse input efficiently." |`boolean_false`               |

## Authors


  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-de-maeyer-b46a814) (author)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author, maintainer)

  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v10(filter)
    v17(filter)
    v32(cross)
    v42(cross)
    v109(concat)
    v116(cross)
    v126(cross)
    v135(branch)
    v162(concat)
    v140(scale)
    v147(cross)
    v157(cross)
    v163(filter)
    v171(highly_variable_features_scanpy)
    v178(cross)
    v188(cross)
    v194(filter)
    v317(concat)
    v206(branch)
    v233(concat)
    v218(cross)
    v228(cross)
    v237(branch)
    v264(concat)
    v249(cross)
    v259(cross)
    v265(filter)
    v295(concat)
    v280(cross)
    v290(cross)
    v302(cross)
    v312(cross)
    v324(cross)
    v331(cross)
    v343(cross)
    v350(cross)
    v354(Output)
    subgraph group_log_normalize [log_normalize]
        v25(normalize_total)
        v48(filter)
        v56(log1p)
        v63(cross)
        v73(cross)
        v79(filter)
        v87(delete_layer)
        v94(cross)
        v104(cross)
    end
    subgraph group_rna_qc [rna_qc]
        v211(grep_mitochondrial_genes)
        v242(grep_ribosomal_genes)
        v273(calculate_qc_metrics)
    end
    v135-->v162
    v162-->v163
    v206-->v233
    v237-->v264
    v264-->v265
    v0-->v2
    v2-->v10
    v10-->v17
    v17-->v25
    v25-->v32
    v17-->v32
    v17-->v42
    v48-->v56
    v56-->v63
    v48-->v63
    v48-->v73
    v79-->v87
    v87-->v94
    v79-->v94
    v79-->v104
    v104-->v109
    v109-->v116
    v10-->v116
    v10-->v126
    v135-->v140
    v140-->v147
    v135-->v147
    v135-->v157
    v157-->v162
    v163-->v171
    v171-->v178
    v163-->v178
    v163-->v188
    v206-->v211
    v211-->v218
    v206-->v218
    v206-->v228
    v228-->v233
    v237-->v242
    v242-->v249
    v237-->v249
    v237-->v259
    v259-->v264
    v265-->v273
    v273-->v280
    v265-->v280
    v265-->v290
    v290-->v295
    v295-->v302
    v194-->v302
    v194-->v312
    v312-->v317
    v317-->v324
    v2-->v324
    v324-->v331
    v2-->v331
    v2-->v343
    v343-->v350
    v2-->v350
    v350-->v354
    v42-->v48
    v25-->v42
    v73-->v79
    v56-->v73
    v87-->v104
    v109-->v126
    v126-->v135
    v140-->v157
    v188-->v194
    v171-->v188
    v194-->v206
    v211-->v228
    v233-->v237
    v242-->v259
    v273-->v290
    v295-->v312
    v317-->v343
    style group_log_normalize fill:#F0F0F0,stroke:#969696;
    style group_rna_qc fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v10 fill:#e3dcea,stroke:#7a4baa;
    style v17 fill:#e3dcea,stroke:#7a4baa;
    style v25 fill:#e3dcea,stroke:#7a4baa;
    style v32 fill:#e3dcea,stroke:#7a4baa;
    style v42 fill:#e3dcea,stroke:#7a4baa;
    style v48 fill:#e3dcea,stroke:#7a4baa;
    style v56 fill:#e3dcea,stroke:#7a4baa;
    style v63 fill:#e3dcea,stroke:#7a4baa;
    style v73 fill:#e3dcea,stroke:#7a4baa;
    style v79 fill:#e3dcea,stroke:#7a4baa;
    style v109 fill:#e3dcea,stroke:#7a4baa;
    style v87 fill:#e3dcea,stroke:#7a4baa;
    style v94 fill:#e3dcea,stroke:#7a4baa;
    style v104 fill:#e3dcea,stroke:#7a4baa;
    style v116 fill:#e3dcea,stroke:#7a4baa;
    style v126 fill:#e3dcea,stroke:#7a4baa;
    style v135 fill:#e3dcea,stroke:#7a4baa;
    style v162 fill:#e3dcea,stroke:#7a4baa;
    style v140 fill:#e3dcea,stroke:#7a4baa;
    style v147 fill:#e3dcea,stroke:#7a4baa;
    style v157 fill:#e3dcea,stroke:#7a4baa;
    style v163 fill:#e3dcea,stroke:#7a4baa;
    style v171 fill:#e3dcea,stroke:#7a4baa;
    style v178 fill:#e3dcea,stroke:#7a4baa;
    style v188 fill:#e3dcea,stroke:#7a4baa;
    style v194 fill:#e3dcea,stroke:#7a4baa;
    style v317 fill:#e3dcea,stroke:#7a4baa;
    style v206 fill:#e3dcea,stroke:#7a4baa;
    style v233 fill:#e3dcea,stroke:#7a4baa;
    style v211 fill:#e3dcea,stroke:#7a4baa;
    style v218 fill:#e3dcea,stroke:#7a4baa;
    style v228 fill:#e3dcea,stroke:#7a4baa;
    style v237 fill:#e3dcea,stroke:#7a4baa;
    style v264 fill:#e3dcea,stroke:#7a4baa;
    style v242 fill:#e3dcea,stroke:#7a4baa;
    style v249 fill:#e3dcea,stroke:#7a4baa;
    style v259 fill:#e3dcea,stroke:#7a4baa;
    style v265 fill:#e3dcea,stroke:#7a4baa;
    style v295 fill:#e3dcea,stroke:#7a4baa;
    style v273 fill:#e3dcea,stroke:#7a4baa;
    style v280 fill:#e3dcea,stroke:#7a4baa;
    style v290 fill:#e3dcea,stroke:#7a4baa;
    style v302 fill:#e3dcea,stroke:#7a4baa;
    style v312 fill:#e3dcea,stroke:#7a4baa;
    style v324 fill:#e3dcea,stroke:#7a4baa;
    style v331 fill:#e3dcea,stroke:#7a4baa;
    style v343 fill:#e3dcea,stroke:#7a4baa;
    style v350 fill:#e3dcea,stroke:#7a4baa;
    style v354 fill:#e3dcea,stroke:#7a4baa;

```

