---
title: "From bdrhap to h5mu"
namespace: "Convert"
description: "Convert the output of a BD Rhapsody pipeline v2.x to a MuData h5 file"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `from_bdrhap_to_h5mu`  
Namespace: `convert`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v2.1.0-rc.2/src/convert/from_bdrhap_to_h5mu/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v2.1.0-rc.2 -latest \
  -main-script target/nextflow/convert/from_bdrhap_to_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "my_id"
input: # please fill in - example: "sample.h5mu"

# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v2.1.0-rc.2 -latest \
  -profile docker \
  -main-script target/nextflow/convert/from_bdrhap_to_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`    |A sample ID.                               |`string`, required, example: `"my_id"`     |
|`--input` |The output h5mu of a BD Rhapsody workflow. |`file`, required, example: `"sample.h5mu"` |


### Outputs

|Name                   |Description       |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`             |Output h5mu file. |`file`, required, example: `"output.h5mu"` |
|`--output_compression` |                  |`string`, example: `"gzip"`                |

## Authors


  * Dorien Roosen [{{< fa brands github >}}](https://github.com/dorien-er) [{{< fa brands linkedin >}}](https://linkedin.com/in/dorien-roosen) (author, maintainer)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author)

