---
title: "Mermaid"
namespace: "Report"
description: "Generates a network from mermaid code"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `mermaid`  
Namespace: `report`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.0-rc3/./src/report/mermaid){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc3 -latest \
  -main-script target/nextflow/report/mermaid/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "path/to/file"
# output: "$id.$key.output.output"
# output_format: "foo"
width: 800
height: 600
background_color: "white"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc3 -latest \
  -profile docker \
  -main-script target/nextflow/report/mermaid/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                 |Description                                                                                                                 |Attributes                                         |
|:--------------------|:---------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------|
|`--input`            |Input directory                                                                                                             |`file`, required                                   |
|`--output`           |Generated network as output.                                                                                                |`file`, required                                   |
|`--output_format`    |Output format for the generated image. By default will be inferred from the extension  of the file specified with --output. |`string`                                           |
|`--width`            |Width of the page                                                                                                           |`integer`, default: `800`                          |
|`--height`           |Height of the page                                                                                                          |`integer`, default: `600`                          |
|`--background_color` |Background color for pngs/svgs (not pdfs)                                                                                   |`string`, default: `"white"`, example: `"#F0F0F0"` |

## Authors


  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-de-maeyer-b46a814) (maintainer)
