
---
title: "filter_with_counts"
---

## Pipeline arguments

nextflow run \
https://github.com/openpipelines-bio/openpipeline.git -r main_build \
-main-script target/nextflow/filter/filter_with_counts/main.nf \
--help

## Table of arguments

| name                 | type         | description                                                                                        |
|:---------------------|:-------------|:---------------------------------------------------------------------------------------------------|
| --input              | file         | Input h5mu file                                                                                    |
| --modality           | string       |                                                                                                    |
| --output             | file         | Output h5mu file.                                                                                  |
| --do_subset          | boolean_true | Whether to subset before storing the output.                                                       |
| --obs_name_filter    | string       | In which .obs slot to store a boolean array corresponding to which observations should be removed. |
| --var_name_filter    | string       | In which .var slot to store a boolean array corresponding to which variables should be removed.    |
| --min_counts         | integer      | Minimum number of counts captured per cell.                                                        |
| --max_counts         | integer      | Maximum number of counts captured per cell.                                                        |
| --min_genes_per_cell | integer      | Minimum of non-zero values per cell.                                                               |
| --max_genes_per_cell | integer      | Maximum of non-zero values per cell.                                                               |
| --min_cells_per_gene | integer      | Minimum of non-zero values per gene.                                                               |
| --min_fraction_mito  | double       | Minimum fraction of UMIs that are mitochondrial.                                                   |
| --max_fraction_mito  | double       | Maximum fraction of UMIs that are mitochondrial.                                                   |