
---
title: "filter_with_hvg"
---

## Pipeline arguments

nextflow run \
https://github.com/openpipelines-bio/openpipeline.git -r main_build \
-main-script target/nextflow/filter/filter_with_hvg/main.nf \
--help

## Table of arguments

| name              | type         | description                                                                                                                                                                                      |
|:------------------|:-------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| --input           | file         | Input h5mu file                                                                                                                                                                                  |
| --modality        | string       |                                                                                                                                                                                                  |
| --layer           | string       | use adata.layers[layer] for expression values instead of adata.X.                                                                                                                                |
| --output          | file         | Output h5mu file.                                                                                                                                                                                |
| --var_name_filter | string       | In which .var slot to store a boolean array corresponding to which observations should be filtered out.                                                                                          |
| --varm_name       | string       | In which .varm slot to store additional metadata.                                                                                                                                                |
| --do_subset       | boolean_true | Whether to subset before storing the output.                                                                                                                                                     |
| --flavor          | string       | Choose the flavor for identifying highly variable genes. For the dispersion based methods in their default workflows, Seurat passes the cutoffs whereas Cell Ranger passes n_top_genes.          |
| --n_top_genes     | integer      | Number of highly-variable genes to keep. Mandatory if flavor='seurat_v3'.                                                                                                                        |
| --min_mean        | double       | If n_top_genes is defined, this and all other cutoffs for the means and the normalized dispersions are ignored. Ignored if flavor='seurat_v3'.                                                   |
| --max_mean        | double       | If n_top_genes is defined, this and all other cutoffs for the means and the normalized dispersions are ignored. Ignored if flavor='seurat_v3'.                                                   |
| --min_disp        | double       | If n_top_genes is defined, this and all other cutoffs for the means and the normalized dispersions are ignored. Ignored if flavor='seurat_v3'.                                                   |
| --max_disp        | double       | If n_top_genes is defined, this and all other cutoffs for the means and the normalized dispersions are ignored. Ignored if flavor='seurat_v3'. Default is +inf.                                  |
| --span            | double       | The fraction of the data (cells) used when estimating the variance in the loess model fit if flavor='seurat_v3'.                                                                                 |
| --n_bins          | integer      | Number of bins for binning the mean gene expression. Normalization is done with respect to each bin. If just a single gene falls into a bin, the normalized dispersion is artificially set to 1. |
| --obs_batch_key   | string       | If specified, highly-variable genes are selected within each batch separately and merged. This simple                                                                                            |
|                   |              | process avoids the selection of batch-specific genes and acts as a lightweight batch correction method.                                                                                          |
|                   |              | For all flavors, genes are first sorted by how many batches they are a HVG. For dispersion-based flavors                                                                                         |
|                   |              | ties are broken by normalized dispersion. If flavor = 'seurat_v3', ties are broken by the median (across                                                                                         |
|                   |              | batches) rank based on within-batch normalized variance.                                                                                                                                         |