---
title: Filter with counts
toc: false
---

::: {.column-margin}

### Info

ID: `filter_with_counts`  
Namespace: `filter`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/filter/filter_with_counts/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/filter/filter_with_counts){.btn-action .btn-sm .btn-info .btn role="button"}
:::

Filter scRNA-seq data based on the primary QC metrics. 
This is based on both the UMI counts, the gene counts 
and the mitochondrial genes (genes starting with mt/MT).


## Argument group

### Arguments



|Name                   |Description                                                                                        |Attributes                              |
|:----------------------|:--------------------------------------------------------------------------------------------------|:---------------------------------------|
|`--input`              |Input h5mu file                                                                                    |`file`, required, example: "input.h5mu" |
|`--output`             |Output h5mu file.                                                                                  |`file`, example: "output.h5mu"          |
|`--do_subset`          |Whether to subset before storing the output.                                                       |`boolean_true`                          |
|`--obs_name_filter`    |In which .obs slot to store a boolean array corresponding to which observations should be removed. |`string`, default: "filter_with_counts" |
|`--var_name_filter`    |In which .var slot to store a boolean array corresponding to which variables should be removed.    |`string`, default: "filter_with_counts" |
|`--min_counts`         |Minimum number of counts captured per cell.                                                        |`integer`, example: 200                 |
|`--max_counts`         |Maximum number of counts captured per cell.                                                        |`integer`, example: 5000000             |
|`--min_genes_per_cell` |Minimum of non-zero values per cell.                                                               |`integer`, example: 200                 |
|`--max_genes_per_cell` |Maximum of non-zero values per cell.                                                               |`integer`, example: 1500000             |
|`--min_cells_per_gene` |Minimum of non-zero values per gene.                                                               |`integer`, example: 3                   |
|`--min_fraction_mito`  |Minimum fraction of UMIs that are mitochondrial.                                                   |`double`, example: 0                    |
|`--max_fraction_mito`  |Maximum fraction of UMIs that are mitochondrial.                                                   |`double`, example: 0.2                  |

## Authors

 * Dries De Maeyer  (contributor)
 * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (maintainer, contributor)

