---
title: From h5mu to seurat
toc: false
---

::: {.column-margin}

### Info

ID: `from_h5mu_to_seurat`  
Namespace: `convert`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/convert/from_h5mu_to_seurat/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/convert/from_h5mu_to_seurat){.btn-action .btn-sm .btn-info .btn role="button"}
:::

Converts an h5mu file into a Seurat file.

Restrictions:
  - Only the intersection of cells is currently loaded into the Seurat object due to the object structure limitation.
  - Multimodal embeddings (global .obsm slot) are loaded with the assay.used field set to the default assay.
  - Embeddings names are changed in order to comply with R & Seurat requirements and conventions.
  - Feature names with underscores ('_') are automatically replaced with dashes ('-')
  - Seurat does not support global variables metadata /var.


## Argument group

### Arguments



|Name       |Description        |Attributes                              |
|:----------|:------------------|:---------------------------------------|
|`--input`  |Input h5mu file    |`file`, required, example: "input.h5mu" |
|`--output` |Output Seurat file |`file`, required, example: "output.rds" |

## Authors

 * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)
