---
title: Concat
toc: false
---

::: {.column-margin}

### Info

ID: `concat`  
Namespace: `integrate`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/integrate/concat/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/integrate/concat){.btn-action .btn-sm .btn-info .btn role="button"}
:::

Concatenates several uni-modal samples in .h5mu files into a single file.


## Argument group

### Arguments



|Name                |Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |Attributes                                  |
|:-------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------|
|`--input`           |Paths to the different samples to be concatenated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |`file`, required, example: "sample_paths"   |
|`--sample_names`    |Names of the different samples that have to be concatenated. Must be of same length as `--input`.                                                                                                                                                                                                                                                                                                                                                                                                                                 |`string`, required, example: "sample_names" |
|`--obs_sample_name` |Name of the .obs key under which to add the sample names.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |`string`, default: "sample_id"              |
|`--compression`     |The compression format to be used on the final h5mu object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |`string`, default: "gzip"                   |
|`--other_axis_mode` |How to handle the merging of other axis (var, obs, ...).  - None: keep no data  - same: only keep elements of the matrices which are the same in each of the samples  - unique: only keep elements for which there is only 1 possible value (1 value that can occur in multiple samples)  - first: keep the annotation from the first sample  - only: keep elements that show up in only one of the objects (1 unique element in only 1 sample)  - move: identical to 'same', but moving the conflicting values to .varm or .obsm |`string`, default: "move"                   |

## Authors

 * Dries Schaumont  (maintainer)

