---
title: "From 10xh5 to h5mu"
toc: false
---

::: {.column-margin}

### Info

ID: `from_10xh5_to_h5mu`  
Namespace: `convert`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/convert/from_10xh5_to_h5mu/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/convert/from_10xh5_to_h5mu){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Converts a 10x h5 into an h5mu file.


## Argument groups

### Inputs

|Name                      |Description                                             |Attributes                                            |
|:-------------------------|:-------------------------------------------------------|:-----------------------------------------------------|
|`--sample_id`             |Sample ID to be stored in an obs column.                |`string`, example: "my_sample"                        |
|`--input`                 |A 10x h5 file as generated by Cell Ranger.              |`file`, required, example: "raw_feature_bc_matrix.h5" |
|`--input_metrics_summary` |A metrics summary csv file as generated by Cell Ranger. |`file`, example: "metrics_cellranger.h5"              |


### Outputs

|Name            |Description                                               |Attributes                              |
|:---------------|:---------------------------------------------------------|:---------------------------------------|
|`--output`      |Output h5mu file.                                         |`file`, example: "output.h5mu"          |
|`--uns_metrics` |Name of the .uns slot under which to QC metrics (if any). |`string`, default: "metrics_cellranger" |


### Arguments

|Name           |Description                                                              |Attributes               |
|:--------------|:------------------------------------------------------------------------|:------------------------|
|`--min_genes`  |Minimum number of counts required for a cell to pass filtering.          |`integer`, example: 100  |
|`--min_counts` |Minimum number of genes expressed required for a cell to pass filtering. |`integer`, example: 1000 |

## Authors

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (maintainer)
