---
title: "Add metadata"
toc: false
---

::: {.column-margin}

### Info

ID: `add_metadata`  
Namespace: `integrate`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/integrate/add_metadata/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/integrate/add_metadata){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Add a csv containing metadata to the .obs or .var field of a mudata file.

## Argument groups

### MuData Input

|Name        |Description                                                                                                                                                                                |Attributes       |
|:-----------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------|
|`--input`   |Input h5mu file                                                                                                                                                                            |`file`, required |
|`--obs_key` |Obs column name where the sample id can be found for each observation to join on. Usefull when adding metadata to concatenated samples. Mutually exclusive with --var_key and --sample_id  |`string`         |
|`--var_key` |Var column name where the sample id can be found for each observation to join on. Usefull when adding metadata to concatenated samples. Mutually exclusive with --var_key and --sample_id. |`string`         |


### MuData Output

|Name       |Description       |Attributes       |
|:----------|:-----------------|:----------------|
|`--output` |Output h5mu file. |`file`, required |


### Metadata Input

|Name          |Description                                              |Attributes              |
|:-------------|:--------------------------------------------------------|:-----------------------|
|`--input_csv` |.csv file containing metadata"                           |`file`                  |
|`--csv_key`   |column of the the csv that corresponds to the sample id. |`string`, default: "id" |

## Authors

  * Dries Schaumont [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (author)
