---
title: Cellranger count
toc: false
---

::: {.column-margin}

### Info

ID: `cellranger_count`  
Namespace: `mapping`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/mapping/cellranger_count/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/mapping/cellranger_count){.btn-action .btn-sm .btn-info .btn role="button"}
:::

Align fastq files using Cell Ranger count.

## Argument group

### Arguments



:::{.column-body-outset}
|Name                   |Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |Attributes                                   |
|:----------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------|
|`--input`              |The folder with fastq.gz files to align.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |`file`, required                             |
|`--reference`          |The path to reference tar.gz file.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |`file`, required                             |
|`--output`             |The folder to store the alignment results.                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |`file`, required, example: "/path/to/output" |
|`--expect_cells`       |Expected number of recovered cells, used as input to cell calling algorithm.                                                                                                                                                                                                                                                                                                                                                                                                                                      |`integer`, example: 3000                     |
|`--chemistry`          |Assay configuration. - auto: autodetect mode - threeprime: Single Cell 3' - fiveprime: Single Cell 5' - SC3Pv1: Single Cell 3' v1 - SC3Pv2: Single Cell 3' v2 - SC3Pv3: Single Cell 3' v3 - SC3Pv3LT: Single Cell 3' v3 LT - SC3Pv3HT: Single Cell 3' v3 HT - SC5P-PE: Single Cell 5' paired-end - SC5P-R2: Single Cell 5' R2-only - SC-FB: Single Cell Antibody-only 3' v2 or 5' See https://kb.10xgenomics.com/hc/en-us/articles/115003764132-How-does-Cell-Ranger-auto-detect-chemistry- for more information. |`string`, default: "auto"                    |
|`--secondary_analysis` |Whether or not to run the secondary analysis e.g. clustering.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |`boolean`, default: FALSE                    |
|`--generate_bam`       |Whether to generate a BAM file.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |`boolean`, default: TRUE                     |
|`--include_introns`    |Include intronic reads in count (default=true unless --target-panel is specified in which case default=false)                                                                                                                                                                                                                                                                                                                                                                                                     |`boolean`, default: TRUE                     |
:::

## Authors

 * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
 * Samuel D'Souza [{{< fa brands github >}}](https://github.com/srdsam) (author)
 * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)
