---
title: "Cellbender remove background"
toc: false
---

::: {.column-margin}

### Info

ID: `cellbender_remove_background`  
Namespace: `correction`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/correction/cellbender_remove_background/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/correction/cellbender_remove_background){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Eliminating technical artifacts from high-throughput single-cell RNA sequencing data.

This module removes counts due to ambient RNA molecules and random barcode swapping from (raw) UMI-based scRNA-seq count matrices. 
At the moment, only the count matrices produced by the CellRanger count pipeline is supported. Support for additional tools and protocols 
will be added in the future. A quick start tutorial can be found here.

 Fleming et al. 2022, bioRxiv.


## Argument groups

### Inputs

|Name      |Description |Attributes                            |
|:---------|:-----------|:-------------------------------------|
|`--input` |Input file. |`file`, required, example: "input.h5" |


### Outputs

|Name                     |Description                                                                                                                                                                                                                                                                                                                    |Attributes                                      |
|:------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------|
|`--output`               |Full count matrix as an h5 file, with background RNA removed. This file contains all the original droplet barcodes.                                                                                                                                                                                                            |`file`, required, example: "output.h5"          |
|`--output_filtered`      |Filtered count matrix as an h5 file, with background RNA removed. The word "filtered" means that this file contains only the droplets which were determined to have a > 50% posterior probability of containing cells.                                                                                                         |`file`, required, example: "output_filtered.h5" |
|`--output_report`        |PDF file that provides a standard graphical summary of the inference procedure.                                                                                                                                                                                                                                                |`file`, example: "report.pdf"                   |
|`--output_cell_barcodes` |CSV file containing all the droplet barcodes which were determined to have a > 50% posterior probability of containing cells. Barcodes are written in plain text. This information is also contained in each of the above outputs, but is included as a separate output for convenient use in certain downstream applications. |`file`, example: "output.csv"                   |


### Arguments

|Name                         |Description                                                                                                                                                                                                                                                                                                                                                               |Attributes                |
|:----------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------|
|`--model`                    |Which model is being used for count data. 'simple' does not model either ambient RNA or random barcode swapping (for debugging purposes -- not recommended). 'ambient' assumes background RNA is incorporated into droplets. 'swapping' assumes background RNA comes from random barcode swapping. 'full' uses a combined ambient and swapping model. Defaults to 'full'. |`string`                  |
|`--total_droplets_included`  |The number of droplets from the rank-ordered UMI plot that will be analyzed. The largest 'total_droplets' droplets will have their cell probabilities inferred as an output.                                                                                                                                                                                              |`integer`, example: 50000 |
|`--epochs`                   |Number of epochs to train                                                                                                                                                                                                                                                                                                                                                 |`integer`, example: 150   |
|`--fpr`                      |Target false positive rate in (0, 1). A false positive is a true signal count that is erroneously removed. More background removal is accompanied by more signal removal at high values of FPR. You can specify multiple values, which will create multiple output files.                                                                                                 |`double`, example: 0.01   |
|`--exclude_antibody_capture` |Including the flag --exclude-antibody-capture will cause remove-background to operate on gene counts only, ignoring other features.                                                                                                                                                                                                                                       |`boolean_true`            |
|`--learning_rate`            |Training detail: lower learning rate for inference. A OneCycle learning rate schedule is used, where the upper learning rate is ten times this value. (For this value, probably do not exceed 1e-3).                                                                                                                                                                      |`double`, example: 1e-04  |
|`--cuda`                     |Including the flag --cuda will run the inference on a GPU.                                                                                                                                                                                                                                                                                                                |`boolean_true`            |

## Authors

