---
title: Make reference
toc: false
---

::: {.column-margin}

### Info

ID: `make_reference`  
Namespace: `reference`

### Command

```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/reference/make_reference/main.nf --help
```

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/reference/make_reference){.btn-action .btn-sm .btn-info .btn role="button"}
:::

Make a reference build.

## Argument group

### Arguments



:::{.column-body-outset}
|Name                  |Description                                                  |Attributes                                                                                                                               |
|:---------------------|:------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------|
|`--genome_fasta`      |Reference genome fasta.                                      |`string`, required, example: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh38.primary_assembly.genome.fa.gz" |
|`--transcriptome_gtf` |Reference transcriptome annotation.                          |`string`, required, example: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz"        |
|`--ercc`              |ERCC sequence and annotation file.                           |`string`, example: "https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip"                                                   |
|`--subset_regex`      |Will subset the reference chromosomes using the given regex. |`string`, example: "(ERCC-00002&#124;chr1)"                                                                                              |
|`--output_fasta`      |Output genome sequence fasta.                                |`file`, required, example: "genome_sequence.fa.gz"                                                                                       |
|`--output_gtf`        |Output transcriptome annotation gtf.                         |`file`, required, example: "transcriptome_annotation.tar.gz"                                                                             |
:::

## Authors

 * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
 * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)
