
---
title: "normalize_total"
---

## Pipeline arguments

nextflow run \
https://github.com/openpipelines-bio/openpipeline.git -r main_build \
-main-script target/nextflow/transform/normalize_total/main.nf \
--help

## Table of arguments

| name                       | type         | description                                                                                                                                                                                                                                                                            |
|:---------------------------|:-------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| --input                    | file         | Input h5mu file                                                                                                                                                                                                                                                                        |
| --modality                 | string       |                                                                                                                                                                                                                                                                                        |
| --input_layer              | string       | Input layer to use. By default, X is normalized                                                                                                                                                                                                                                        |
| --output                   | file         | Output h5mu file.                                                                                                                                                                                                                                                                      |
| --output_layer             | string       | Output layer to use. By default, use X.                                                                                                                                                                                                                                                |
| --target_sum               | integer      | If None, after normalization, each observation (cell) has a total count equal to the median of total counts for observations (cells) before normalization.                                                                                                                             |
| --exclude_highly_expressed | boolean_true | Exclude (very) highly expressed genes for the computation of the normalization factor (size factor) for each cell. A gene is considered highly expressed, if it has more than max_fraction of the total counts in at least one cell. The not-excluded genes will sum up to target_sum. |