
---
title: "scvelo"
---

## Pipeline arguments

nextflow run \
https://github.com/openpipelines-bio/openpipeline.git -r main_build \
-main-script target/nextflow/velocity/scvelo/main.nf \
--help

## Table of arguments

| name    | type   | description         |
|:--------|:-------|:--------------------|
| --input | file   | Velocyto loom file. |
| name     | type   | description                                              |
|:---------|:-------|:---------------------------------------------------------|
| --output | file   | Output directory. If it does not exist, will be created. |
| name                | type    | description                                                                    |
|:--------------------|:--------|:-------------------------------------------------------------------------------|
| --min_counts        | integer | Minimum number of counts required for a gene to pass filtering (spliced).      |
| --min_counts_u      | integer | Minimum number of counts required for a gene to pass filtering (unspliced).    |
| --min_cells         | integer | Minimum number of cells expressed required to pass filtering (spliced).        |
| --min_cells_u       | integer | Minimum number of cells expressed required to pass filtering (unspliced).      |
| --min_shared_counts | integer | Minimum number of counts (both unspliced and spliced) required for a gene.     |
| --min_shared_cells  | integer | Minimum number of cells required to be expressed (both unspliced and spliced). |
| --n_top_genes       | integer | Number of genes to keep.                                                       |
| --log_transform     | boolean | Do not log transform counts.                                                   |
| name                     | type    | description                                                                  |
|:-------------------------|:--------|:-----------------------------------------------------------------------------|
| --n_principal_components | integer | Number of principal components to use for calculating moments.               |
| --n_neighbors            | integer | Number of neighbors to use. First/second-order moments are computed for each |
|                          |         | cell across its nearest neighbors, where the neighbor graph is obtained from |
|                          |         | euclidean distances in PCA space.                                            |