
---
title: "umap"
---

## Pipeline arguments

nextflow run \
https://github.com/openpipelines-bio/openpipeline.git -r main_build \
-main-script target/nextflow/dimred/umap/main.nf \
--help

## Table of arguments

| name                   | type    | description                                                                                                                                                                                                                                                                                                                                                                               |
|:-----------------------|:--------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| --input                | file    | Input h5mu file                                                                                                                                                                                                                                                                                                                                                                           |
| --modality             | string  |                                                                                                                                                                                                                                                                                                                                                                                           |
| --uns_neighbors        | string  | The .uns neighbors slot as output by the `find_neighbors` component.                                                                                                                                                                                                                                                                                                                      |
| --output               | file    | Output h5mu file.                                                                                                                                                                                                                                                                                                                                                                         |
| --output_key           | string  | The pre/postfix under which to store the UMAP results.                                                                                                                                                                                                                                                                                                                                    |
| --min_dist             | double  | The effective minimum distance between embedded points. Smaller values will result in a more clustered/clumped embedding where nearby points on the manifold are drawn closer together, while larger values will result on a more even dispersal of points. The value should be set relative to the spread value, which determines the scale at which embedded points will be spread out. |
| --spread               | double  | The effective scale of embedded points. In combination with min_dist this determines how clustered/clumped the embedded points are.                                                                                                                                                                                                                                                       |
| --num_components       | integer | The number of dimensions of the embedding.                                                                                                                                                                                                                                                                                                                                                |
| --max_iter             | integer | The number of iterations (epochs) of the optimization.                                                                                                                                                                                                                                                                                                                                    |
| --alpha                | double  | The initial learning rate for the embedding optimization.                                                                                                                                                                                                                                                                                                                                 |
| --gamma                | double  | Weighting applied to negative samples in low dimensional embedding optimization. Values higher than one will result in greater weight being given to negative samples.                                                                                                                                                                                                                    |
| --negative_sample_rate | integer | The number of negative edge/1-simplex samples to use per positive edge/1-simplex sample in optimizing the low dimensional embedding.                                                                                                                                                                                                                                                      |
| --init_pos             | string  | How to initialize the low dimensional embedding. Called init in the original UMAP. Options are paga, spectral and random.                                                                                                                                                                                                                                                                 |