---
title: "Full pipeline"
toc: false
---

::: {.column-margin}

### Info

ID: `full_pipeline`  
Namespace: `multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/workflows/multiomics/full_pipeline){.btn-action .btn-sm .btn-info .btn role="button"}

:::

A pipeline to analyse multiple multiomics samples.

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script workflows/multiomics/full_pipeline/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: ["foo"]
input: # please fill in - example: ["input.h5mu"]
obs_covariates: # please fill in - example: ["batch", "sample"]

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script workflows/multiomics/full_pipeline/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Inputs

|Name               |Description                                                    |Attributes                                                  |
|:------------------|:--------------------------------------------------------------|:-----------------------------------------------------------|
|`--id`             |ID of the sample.                                              |`string`, required, example: `"foo"`                        |
|`--input`          |Path to the sample.                                            |`file`, required, example: `"input.h5mu"`                   |
|`--obs_covariates` |The .obs field(s) that define the covariate(s) to regress out. |`string`, required, example: `"batch"`, example: `"sample"` |

## Authors

  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (author, maintainer)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p2(flatMap)
    p10(split_modalities)
    p19(filter_with_counts)
    p26(do_filter)
    p34(filter_with_scrublet)
    p38(toSortedList)
    p46(concat)
    p53(normalize_total)
    p60(log1p)
    p67(delete_layer)
    p75(filter_with_hvg)
    p89(concat)
    p80(toSortedList)
    p86(concat)
    p90(toSortedList)
    p96(merge)
    p106(pca)
    p114(harmonypy)
    p122(find_neighbors)
    p130(leiden)
    p138(umap)
    p143(toSortedList)
    p145(Output)
    p89-->p90
    p0-->p2
    p2-->p10
    p10-->p19
    p19-->p26
    p26-->p34
    p34-->p38
    p38-->p46
    p46-->p53
    p53-->p60
    p60-->p67
    p67-->p75
    p75-->p89
    p10-->p80
    p80-->p86
    p86-->p89
    p90-->p96
    p96-->p106
    p106-->p114
    p114-->p122
    p122-->p130
    p130-->p138
    p138-->p143
    p143-->p145

```
