---
title: "Add id"
namespace: "Metadata"
description: "Add id of .obs."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `add_id`  
Namespace: `metadata`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.0-rc6/./src/metadata/add_id){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Also allows to make .obs_names (the .obs index) unique 
by prefixing the values with an unique id per .h5mu file

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc6 -latest \
  -main-script target/nextflow/metadata/add_id/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "sample_path"
input_id: # please fill in - example: "foo"
obs_output: "sample_id"
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"
make_observation_keys_unique: false

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc6 -latest \
  -profile docker \
  -main-script target/nextflow/metadata/add_id/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                             |Description                                                  |Attributes                                 |
|:--------------------------------|:------------------------------------------------------------|:------------------------------------------|
|`--input`                        |Path to the input .h5mu.                                     |`file`, required, example: `"sample_path"` |
|`--input_id`                     |The input id.                                                |`string`, required                         |
|`--obs_output`                   |Name of the .obs column where to store the id.               |`string`, default: `"sample_id"`           |
|`--output`                       |                                                             |`file`, example: `"output.h5mu"`           |
|`--output_compression`           |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                |
|`--make_observation_keys_unique` |Join the id to the .obs index (.obs_names).                  |`boolean_true`                             |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)
