---
title: "Grep annotation column"
namespace: "Metadata"
description: "Perform a regex lookup on a column from the annotation matrices .obs or .var."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `grep_annotation_column`  
Namespace: `metadata`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.0-rc2/./src/metadata/grep_annotation_column){.btn-action .btn-sm .btn-info .btn role="button"}

:::

The annotation matrix can originate from either a modality, or all modalities (global .var or .obs)

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc2 -latest \
  -main-script target/nextflow/metadata/grep_annotation_column/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
input: # please fill in - example: "sample_path"
# input_column: "foo"
# input_layer: "foo"
modality: # please fill in - example: "rna"
# matrix: "var"

# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"
output_match_column: # please fill in - example: "foo"
# output_fraction_column: "foo"

# Query options
regex_pattern: # please fill in - example: "^[mM][tT]-"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc2 -latest \
  -profile docker \
  -main-script target/nextflow/metadata/grep_annotation_column/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

Arguments related to the input dataset.


|Name             |Description                                                                                                                                                                |Attributes                                 |
|:----------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------|
|`--input`        |Path to the input .h5mu.                                                                                                                                                   |`file`, required, example: `"sample_path"` |
|`--input_column` |Column to query. If not specified, use .var_names or .obs_names, depending on the value of --matrix                                                                        |`string`                                   |
|`--input_layer`  |Input data to use when calculating fraction of observations that match with the query.  Only used when --output_fraction_column is provided. If not specified, .X is used. |`string`                                   |
|`--modality`     |Which modality to get the annotation matrix from.                                                                                                                          |`string`, required, example: `"rna"`       |
|`--matrix`       |Matrix to fetch the column from that will be searched.                                                                                                                     |`string`, example: `"var"`                 |


### Outputs

Arguments related to how the output will be written.


|Name                       |Description                                                                                                   |Attributes                       |
|:--------------------------|:-------------------------------------------------------------------------------------------------------------|:--------------------------------|
|`--output`                 |                                                                                                              |`file`, example: `"output.h5mu"` |
|`--output_compression`     |The compression format to be used on the output h5mu object.                                                  |`string`, example: `"gzip"`      |
|`--output_match_column`    |Name of the column to write the result to.                                                                    |`string`, required               |
|`--output_fraction_column` |For the opposite axis, name of the column to write the fraction of  observations that matches to the pattern. |`string`                         |


### Query options

Options related to the query


|Name              |Description                                  |Attributes                                  |
|:-----------------|:--------------------------------------------|:-------------------------------------------|
|`--regex_pattern` |Regex to use to match with the input column. |`string`, required, example: `"^[mM][tT]-"` |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)
