---
title: "Join csv"
namespace: "Metadata"
description: "Join a csv containing metadata to the .obs or .var field of a mudata file."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `join_csv`  
Namespace: `metadata`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.1/src/metadata/join_csv/config.vsh.yml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -main-script target/nextflow/metadata/join_csv/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# MuData Input
input: # please fill in - example: "input.h5mu"
modality: "rna"
# obs_key: "foo"
# var_key: "foo"

# MuData Output
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Metadata Input
input_csv: # please fill in - example: "metadata.csv"
csv_key: "id"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/metadata/join_csv/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### MuData Input

|Name         |Description                                                                                                                                                                  |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`    |Input h5mu file                                                                                                                                                              |`file`, required, example: `"input.h5mu"` |
|`--modality` |                                                                                                                                                                             |`string`, default: `"rna"`                |
|`--obs_key`  |Obs column name where the sample id can be found for each observation to join on. Useful when adding metadata to concatenated samples. Mutually exclusive with `--var_key`." |`string`                                  |
|`--var_key`  |Var column name where the sample id can be found for each variable to join on. Mutually exclusive with `--obs_key`."                                                         |`string`                                  |


### MuData Output

|Name                   |Description                                                  |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`             |Output h5mu file.                                            |`file`, required, example: `"output.h5mu"` |
|`--output_compression` |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                |


### Metadata Input

|Name          |Description                                              |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--input_csv` |.csv file containing metadata                            |`file`, required, example: `"metadata.csv"` |
|`--csv_key`   |column of the the csv that corresponds to the sample id. |`string`, default: `"id"`                   |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author)

