---
title: "Generate documentation qmd"
namespace: "Quarto"
description: "Generates .qmd files for documentating viash components and workflows"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `generate_documentation_qmd`  
Namespace: `quarto`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/0.8.0/viash_tools/src/quarto/generate_documentation_qmd){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.8.0 -latest \
  -main-script target/nextflow/quarto/generate_documentation_qmd/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.8.0 -latest \
  -profile docker \
  -main-script target/nextflow/quarto/generate_documentation_qmd/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name         |Description                                                                                         |Attributes                                         |
|:------------|:---------------------------------------------------------------------------------------------------|:--------------------------------------------------|
|`--input`    |Input project                                                                                       |`file`, required, example: `"/path/to/my_project"` |
|`--template` |"Jinja template that can be used to customize the .qmd. By default will use the included template." |`file`                                             |


### Outputs

|Name          |Description               |Attributes                                            |
|:-------------|:-------------------------|:-----------------------------------------------------|
|`--output`    |Output website            |`file`, required, example: `"/path/to/my_website"`    |
|`--dest_path` |Template for output paths |`string`, default: `"{type}s/{namespace}/{name}.qmd"` |


### Arguments

|Name               |Description                                     |Attributes         |
|:------------------|:-----------------------------------------------|:------------------|
|`--clean`          |Whether or not to start from a clean directory. |`boolean_true`     |
|`--write_index`    |Whether or not to also create an index file.    |`boolean_true`     |
|`--git_repo`       |Git repo                                        |`string`, required |
|`--git_tag`        |Git tag                                         |`string`, required |
|`--git_browse_url` |The base url for browsing a file.               |`string`           |

## Authors

