---
title: "Do filter"
namespace: "Filter"
description: "Remove observations and variables based on specified .obs and .var columns"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `do_filter`  
Namespace: `filter`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.0-rc4/./src/filter/do_filter){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc4 -latest \
  -main-script target/nextflow/filter/do_filter/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input.h5mu"
modality: "rna"
# obs_filter: ["filter_with_x"]
# var_filter: ["filter_with_x"]
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc4 -latest \
  -profile docker \
  -main-script target/nextflow/filter/do_filter/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                  |Attributes                                                        |
|:----------------------|:------------------------------------------------------------|:-----------------------------------------------------------------|
|`--input`              |Input h5mu file                                              |`file`, required, example: `"input.h5mu"`                         |
|`--modality`           |                                                             |`string`, default: `"rna"`                                        |
|`--obs_filter`         |Which .obs columns to use to filter the observations by.     |List of `string`, example: `"filter_with_x"`, multiple_sep: `";"` |
|`--var_filter`         |Which .var columns to use to filter the observations by.     |List of `string`, example: `"filter_with_x"`, multiple_sep: `";"` |
|`--output`             |Output h5mu file.                                            |`file`, example: `"output.h5mu"`                                  |
|`--output_compression` |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                                       |

## Authors


  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (maintainer, contributor)
