---
title: "Intersect obs"
namespace: "Filter"
description: "Create an intersection between two or more modalities."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `intersect_obs`  
Namespace: `filter`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.0-rc4/./src/filter/intersect_obs){.btn-action .btn-sm .btn-info .btn role="button"}

:::

This component removes any observations which are not present in all modalities.


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc4 -latest \
  -main-script target/nextflow/filter/intersect_obs/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input.h5mu"
modalities: # please fill in - example: ["rna", "prot"]
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.0-rc4 -latest \
  -profile docker \
  -main-script target/nextflow/filter/intersect_obs/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                  |Attributes                                                                |
|:----------------------|:------------------------------------------------------------|:-------------------------------------------------------------------------|
|`--input`              |Input h5mu file                                              |`file`, required, example: `"input.h5mu"`                                 |
|`--modalities`         |                                                             |List of `string`, required, example: `"rna", "prot"`, multiple_sep: `";"` |
|`--output`             |Output h5mu file.                                            |`file`, example: `"output.h5mu"`                                          |
|`--output_compression` |The compression format to be used on the output h5mu object. |`string`, example: `"gzip"`                                               |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (maintainer)

  * Isabelle Bergiers [{{< fa brands github >}}](https://github.com/Isabelle-b) [{{< fa brands orcid >}}](https://orcid.org/0000-0001-9622-7960) (contributor)
