---
title: Workflows
---

## Workflows

|Namespace   |Name                   |Author(s)                                       |
|:-----------|:----------------------|:-----------------------------------------------|
|ingestion   |[bd_rhapsody](workflow_ingestion_bd_rhapsody.qmd)|Robrecht Cannoodt                               |
|ingestion   |[cellranger_demux](workflow_ingestion_cellranger_demux.qmd)|Angela Pisco, Samuel D'Souza, Robrecht Cannoodt |
|ingestion   |[cellranger_mapping](workflow_ingestion_cellranger_mapping.qmd)|Angela Pisco, Samuel D'Souza, Robrecht Cannoodt |
|ingestion   |[demux](workflow_ingestion_demux.qmd)|Toni Verbeiren, Marijke Van Moerbeke            |
|integration |[multimodal_integration](workflow_integration_multimodal_integration.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|integration |[multiomics](workflow_integration_multiomics.qmd)|Dries Schaumont                                 |
|process_rna |[multisample](workflow_process_rna_multisample.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|process_rna |[singlesample](workflow_process_rna_singlesample.qmd)|Dries De Maeyer, Robrecht Cannoodt              |

## Components
|Namespace     |Name                                  |Author(s)                                       |
|:-------------|:-------------------------------------|:-----------------------------------------------|
|cluster       |[leiden](module_cluster_leiden.qmd)   |Dries De Maeyer                                 |
|compression   |[tar_extract](module_compression_tar_extract.qmd)|                                                |
|convert       |[from_10xh5_to_h5mu](module_convert_from_10xh5_to_h5mu.qmd)|Robrecht Cannoodt                               |
|convert       |[from_10xmtx_to_h5mu](module_convert_from_10xmtx_to_h5mu.qmd)|Robrecht Cannoodt                               |
|convert       |[from_bd_to_10x_molecular_barcode_tags](module_convert_from_bd_to_10x_molecular_barcode_tags.qmd)|Dries Schaumont                                 |
|convert       |[from_bdrhap_to_h5mu](module_convert_from_bdrhap_to_h5mu.qmd)|Robrecht Cannoodt                               |
|convert       |[from_h5ad_to_h5mu](module_convert_from_h5ad_to_h5mu.qmd)|Dries De Maeyer                                 |
|convert       |[from_h5mu_to_seurat](module_convert_from_h5mu_to_seurat.qmd)|Robrecht Cannoodt                               |
|convert       |[from_velocyto_to_h5mu](module_convert_from_velocyto_to_h5mu.qmd)|Dries Schaumont                                 |
|demux         |[bcl_convert](module_demux_bcl_convert.qmd)|Toni Verbeiren, Marijke Van moerbeke            |
|demux         |[bcl2fastq](module_demux_bcl2fastq.qmd)|Toni Verbeiren                                  |
|demux         |[cellranger_mkfastq](module_demux_cellranger_mkfastq.qmd)|Angela Pisco, Samuel D'Souza, Robrecht Cannoodt |
|dimred        |[pca](module_dimred_pca.qmd)          |Dries De Maeyer                                 |
|dimred        |[umap](module_dimred_umap.qmd)        |Dries De Maeyer                                 |
|download      |[download_file](module_download_download_file.qmd)|Robrecht Cannoodt                               |
|download      |[sync_test_resources](module_download_sync_test_resources.qmd)|Robrecht Cannoodt                               |
|files         |[make_params](module_files_make_params.qmd)|Angela Pisco, Robrecht Cannoodt                 |
|filter        |[do_filter](module_filter_do_filter.qmd)|Robrecht Cannoodt                               |
|filter        |[filter_with_counts](module_filter_filter_with_counts.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|filter        |[filter_with_hvg](module_filter_filter_with_hvg.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|filter        |[filter_with_scrublet](module_filter_filter_with_scrublet.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|filter        |[subset_h5mu](module_filter_subset_h5mu.qmd)|Dries Schaumont                                 |
|integrate     |[concat](module_integrate_concat.qmd) |Dries Schaumont                                 |
|integrate     |[harmony](module_integrate_harmony.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|integrate     |[harmonypy](module_integrate_harmonypy.qmd)|Dries Schaumont, Robrecht Cannoodt              |
|integrate     |[merge](module_integrate_merge.qmd)   |Dries Schaumont                                 |
|integrate     |[scanorama](module_integrate_scanorama.qmd)|Dries De Maeyer, Dries Schaumont                |
|interactive   |[run_cellxgene](module_interactive_run_cellxgene.qmd)|                                                |
|interactive   |[run_cirrocumulus](module_interactive_run_cirrocumulus.qmd)|                                                |
|mapping       |[bd_rhapsody](module_mapping_bd_rhapsody.qmd)|Robrecht Cannoodt                               |
|mapping       |[cellranger_count_split](module_mapping_cellranger_count_split.qmd)|Angela Pisco, Samuel D'Souza, Robrecht Cannoodt |
|mapping       |[cellranger_count](module_mapping_cellranger_count.qmd)|Angela Pisco, Samuel D'Souza, Robrecht Cannoodt |
|neighbors     |[bbknn](module_neighbors_bbknn.qmd)   |Dries De Maeyer, Dries Schaumont                |
|neighbors     |[find_neighbors](module_neighbors_find_neighbors.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|process_10xh5 |[filter_10xh5](module_process_10xh5_filter_10xh5.qmd)|Robrecht Cannoodt                               |
|qc            |[fastqc](module_qc_fastqc.qmd)        |                                                |
|qc            |[multiqc](module_qc_multiqc.qmd)      |                                                |
|reference     |[build_bdrhap_reference](module_reference_build_bdrhap_reference.qmd)|Angela Pisco, Robrecht Cannoodt                 |
|reference     |[build_cellranger_reference](module_reference_build_cellranger_reference.qmd)|Angela Pisco, Robrecht Cannoodt                 |
|reference     |[make_reference](module_reference_make_reference.qmd)|Angela Pisco, Robrecht Cannoodt                 |
|report        |[mermaid](module_report_mermaid.qmd)  |Dries De Maeyer                                 |
|split         |[split_modalities](module_split_split_modalities.qmd)|Dries Schaumont                                 |
|transfer      |[publish](module_transfer_publish.qmd)|Toni Verbeiren                                  |
|transform     |[delete_layer](module_transform_delete_layer.qmd)|Dries Schaumont                                 |
|transform     |[log1p](module_transform_log1p.qmd)   |Dries De Maeyer, Robrecht Cannoodt              |
|transform     |[normalize_total](module_transform_normalize_total.qmd)|Dries De Maeyer, Robrecht Cannoodt              |
|transform     |[regress_out](module_transform_regress_out.qmd)|Robrecht Cannoodt                               |
|transform     |[scale](module_transform_scale.qmd)   |Dries Schaumont                                 |
|velocity      |[scvelo](module_velocity_scvelo.qmd)  |Dries Schaumont                                 |
|velocity      |[velocyto](module_velocity_velocyto.qmd)|Robrecht Cannoodt                               |

