---
title: sync_test_resources
---

Synchronise the test resources from s3://openpipelines-data to resources_test

## Argument help

Run the following command to view the module's help page:
```bash
nextflow run openpipelines-bio/openpipeline -r main_build -main-script target/nextflow/download/sync_test_resources/main.nf --help
```

### Arguments



:::{.column-body-outset}
|Name        |Description                                                                                                |Attributes                                 |
|:-----------|:----------------------------------------------------------------------------------------------------------|:------------------------------------------|
|`--input`   |Path to the S3 bucket to sync from.                                                                        |string, default: "s3://openpipelines-data" |
|`--output`  |Path to the test resource directory.                                                                       |file, default: "resources_test"            |
|`--quiet`   |Displays the operations that would be performed using the specified command without actually running them. |boolean_true                               |
|`--dryrun`  |Does not display the operations performed from the specified command.                                      |boolean_true                               |
|`--delete`  |Files that exist in the destination but not in the source are deleted during sync.                         |boolean_true                               |
|`--exclude` |Exclude all files or objects from the command that matches the specified pattern.                          |string                                     |
:::

## Authors

 * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (maintainer)
