---
title: "Harmony leiden"
namespace: "Workflows/integration"
description: "Run harmony integration followed by neighbour calculations, leiden clustering and run umap on the result."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `harmony_leiden`  
Namespace: `workflows/integration`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.1.1/src/workflows/integration/harmony_leiden/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -main-script target/nextflow/workflows/integration/harmony_leiden/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
# input: "dataset.h5mu"
# tiledb_input_uri: "s3://bucket/path"
# tiledb_s3_region: "us-west-2"
# tiledb_endpoint: "foo"
tiledb_s3_no_sign_request: false

# Input slots
layer: "log_normalized"
modality: "rna"

# Outputs
# output: "$id.$key.output.h5mu"
# output_tiledb: "$id.$key.output_tiledb"

# Neighbour calculation
uns_neighbors: "harmonypy_integration_neighbors"
obsp_neighbor_distances: "harmonypy_integration_distances"
obsp_neighbor_connectivities: "harmonypy_integration_connectivities"

# Harmony integration options
embedding: "X_pca"
obsm_integrated: "X_pca_integrated"
obs_covariates: # please fill in - example: ["batch", "sample"]
theta: [2.0]

# Clustering options
obs_cluster: "harmony_integration_leiden"
leiden_resolution: [1.0]

# Umap options
obsm_umap: "X_leiden_harmony_umap"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/integration/harmony_leiden/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name                          |Description                                                                             |Attributes                              |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`                     |Path to the sample. Mutually exclusive with the 'input_uri' argument.                   |`file`, example: `"dataset.h5mu"`       |
|`--tiledb_input_uri`          |A URI containing the TileDB-SOMA objects. Mutually exclusive with the 'input' argument. |`string`, example: `"s3://bucket/path"` |
|`--tiledb_s3_region`          |Region where the TileDB-SOMA database is hosted.                                        |`string`, example: `"us-west-2"`        |
|`--tiledb_endpoint`           |Custom endpoint to use to connect to S3                                                 |`string`                                |
|`--tiledb_s3_no_sign_request` |Do not sign S3 requests. Credentials will not be loaded if this argument is provided.   |`boolean`, default: `FALSE`             |


### Input slots

|Name         |Description                                                                           |Attributes                            |
|:----------|:--------------------------------------------------|:--------------------|
|`--layer`    |use specified layer for expression values instead of the .X object from the modality. |`string`, default: `"log_normalized"` |
|`--modality` |Which modality to process.                                                            |`string`, default: `"rna"`            |


### Outputs

|Name              |Description                                                                                          |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`        |Destination path to the output.                                                                      |`file`, required, example: `"output.h5mu"` |
|`--output_tiledb` |Output the TileDB database to the specified directory instead of adding it to the existing database. |`file`                                     |


### Neighbour calculation

|Name                             |Description                                                                             |Attributes                                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--uns_neighbors`                |In which .uns slot to store various neighbor output objects.                            |`string`, default: `"harmonypy_integration_neighbors"`      |
|`--obsp_neighbor_distances`      |In which .obsp slot to store the distance matrix between the resulting neighbors.       |`string`, default: `"harmonypy_integration_distances"`      |
|`--obsp_neighbor_connectivities` |In which .obsp slot to store the connectivities matrix between the resulting neighbors. |`string`, default: `"harmonypy_integration_connectivities"` |


### Harmony integration options

|Name                |Description                                                                                                                                                                                                                                                                                    |Attributes                                                                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--embedding`       |Embedding to use as input                                                                                                                                                                                                                                                                      |`string`, default: `"X_pca"`                                                  |
|`--obsm_integrated` |In which .obsm slot to store the resulting integrated embedding.                                                                                                                                                                                                                               |`string`, default: `"X_pca_integrated"`                                       |
|`--obs_covariates`  |The .obs field(s) that define the covariate(s) to regress out.                                                                                                                                                                                                                                 |List of `string`, required, example: `"batch", "sample"`, multiple_sep: `";"` |
|`--theta`           |Diversity clustering penalty parameter. Can be set as a single value for all batch observations or as multiple values, one for each observation in the batches defined by --obs_covariates. theta=0 does not encourage any diversity. Larger values of theta result in more diverse clusters." |List of `double`, default: `2`, multiple_sep: `";"`                           |


### Clustering options

|Name                  |Description                                                                                                                                                                                                                                                        |Attributes                                          |
|:----------|:--------------------------------------------------|:--------------------|
|`--obs_cluster`       |Prefix for the .obs keys under which to add the cluster labels. Newly created columns in .obs will  be created from the specified value for '--obs_cluster' suffixed with an underscore and one of the resolutions resolutions specified in '--leiden_resolution'. |`string`, default: `"harmony_integration_leiden"`   |
|`--leiden_resolution` |Control the coarseness of the clustering. Higher values lead to more clusters.                                                                                                                                                                                     |List of `double`, default: `1`, multiple_sep: `";"` |


### Umap options

|Name          |Description                                                |Attributes                                   |
|:----------|:--------------------------------------------------|:--------------------|
|`--obsm_umap` |In which .obsm slot to store the resulting UMAP embedding. |`string`, default: `"X_leiden_harmony_umap"` |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v14(branch)
    v41(concat)
    v19(from_tiledb_to_h5mu)
    v26(cross)
    v36(cross)
    v42(filter)
    v50(harmonypy)
    v57(cross)
    v67(cross)
    v73(filter)
    v82(filter)
    v97(cross)
    v107(cross)
    v116(branch)
    v143(concat)
    v128(cross)
    v138(cross)
    v147(branch)
    v174(concat)
    v159(cross)
    v169(cross)
    v178(branch)
    v205(concat)
    v190(cross)
    v200(cross)
    v212(cross)
    v222(cross)
    v231(branch)
    v258(concat)
    v236(move_mudata_obsm_to_tiledb)
    v243(cross)
    v253(cross)
    v262(branch)
    v289(concat)
    v267(move_mudata_obs_to_tiledb)
    v274(cross)
    v284(cross)
    v296(cross)
    v303(cross)
    v315(cross)
    v322(cross)
    v326(Output)
    subgraph group_neighbors_leiden_umap [neighbors_leiden_umap]
        v90(find_neighbors)
        v121(leiden)
        v152(move_obsm_to_obs)
        v183(umap)
    end
    v14-->v41
    v41-->v42
    v116-->v143
    v147-->v174
    v178-->v205
    v231-->v258
    v262-->v289
    v0-->v2
    v14-->v19
    v19-->v26
    v14-->v26
    v14-->v36
    v36-->v41
    v42-->v50
    v50-->v57
    v42-->v57
    v42-->v67
    v73-->v82
    v82-->v90
    v90-->v97
    v82-->v97
    v82-->v107
    v116-->v121
    v121-->v128
    v116-->v128
    v116-->v138
    v138-->v143
    v147-->v152
    v152-->v159
    v147-->v159
    v147-->v169
    v169-->v174
    v178-->v183
    v183-->v190
    v178-->v190
    v178-->v200
    v200-->v205
    v205-->v212
    v73-->v212
    v73-->v222
    v231-->v236
    v236-->v243
    v231-->v243
    v231-->v253
    v253-->v258
    v262-->v267
    v267-->v274
    v262-->v274
    v262-->v284
    v284-->v289
    v289-->v296
    v2-->v296
    v296-->v303
    v2-->v303
    v2-->v315
    v315-->v322
    v2-->v322
    v322-->v326
    v2-->v14
    v19-->v36
    v67-->v73
    v50-->v67
    v90-->v107
    v107-->v116
    v121-->v138
    v143-->v147
    v152-->v169
    v174-->v178
    v183-->v200
    v205-->v222
    v222-->v231
    v236-->v253
    v258-->v262
    v267-->v284
    v289-->v315
    style group_neighbors_leiden_umap fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v14 fill:#e3dcea,stroke:#7a4baa;
    style v41 fill:#e3dcea,stroke:#7a4baa;
    style v19 fill:#e3dcea,stroke:#7a4baa;
    style v26 fill:#e3dcea,stroke:#7a4baa;
    style v36 fill:#e3dcea,stroke:#7a4baa;
    style v42 fill:#e3dcea,stroke:#7a4baa;
    style v50 fill:#e3dcea,stroke:#7a4baa;
    style v57 fill:#e3dcea,stroke:#7a4baa;
    style v67 fill:#e3dcea,stroke:#7a4baa;
    style v73 fill:#e3dcea,stroke:#7a4baa;
    style v82 fill:#e3dcea,stroke:#7a4baa;
    style v90 fill:#e3dcea,stroke:#7a4baa;
    style v97 fill:#e3dcea,stroke:#7a4baa;
    style v107 fill:#e3dcea,stroke:#7a4baa;
    style v116 fill:#e3dcea,stroke:#7a4baa;
    style v143 fill:#e3dcea,stroke:#7a4baa;
    style v121 fill:#e3dcea,stroke:#7a4baa;
    style v128 fill:#e3dcea,stroke:#7a4baa;
    style v138 fill:#e3dcea,stroke:#7a4baa;
    style v147 fill:#e3dcea,stroke:#7a4baa;
    style v174 fill:#e3dcea,stroke:#7a4baa;
    style v152 fill:#e3dcea,stroke:#7a4baa;
    style v159 fill:#e3dcea,stroke:#7a4baa;
    style v169 fill:#e3dcea,stroke:#7a4baa;
    style v178 fill:#e3dcea,stroke:#7a4baa;
    style v205 fill:#e3dcea,stroke:#7a4baa;
    style v183 fill:#e3dcea,stroke:#7a4baa;
    style v190 fill:#e3dcea,stroke:#7a4baa;
    style v200 fill:#e3dcea,stroke:#7a4baa;
    style v212 fill:#e3dcea,stroke:#7a4baa;
    style v222 fill:#e3dcea,stroke:#7a4baa;
    style v231 fill:#e3dcea,stroke:#7a4baa;
    style v258 fill:#e3dcea,stroke:#7a4baa;
    style v236 fill:#e3dcea,stroke:#7a4baa;
    style v243 fill:#e3dcea,stroke:#7a4baa;
    style v253 fill:#e3dcea,stroke:#7a4baa;
    style v262 fill:#e3dcea,stroke:#7a4baa;
    style v289 fill:#e3dcea,stroke:#7a4baa;
    style v267 fill:#e3dcea,stroke:#7a4baa;
    style v274 fill:#e3dcea,stroke:#7a4baa;
    style v284 fill:#e3dcea,stroke:#7a4baa;
    style v296 fill:#e3dcea,stroke:#7a4baa;
    style v303 fill:#e3dcea,stroke:#7a4baa;
    style v315 fill:#e3dcea,stroke:#7a4baa;
    style v322 fill:#e3dcea,stroke:#7a4baa;
    style v326 fill:#e3dcea,stroke:#7a4baa;

```

