---
title: "Sync test resources"
namespace: "Download"
description: "Sync test resources to the local filesystem"
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `sync_test_resources`  
Namespace: `download`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/2.1.2/src/download/sync_test_resources/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.2 -latest \
  -main-script target/nextflow/download/sync_test_resources/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
input: "_viash.yaml"

# Outputs
# output: "."

# Arguments
quiet: false
dryrun: false
delete: false
# exclude: ["foo"]

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.2 -latest \
  -profile docker \
  -main-script target/nextflow/download/sync_test_resources/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                         |Attributes                       |
|:----------|:--------------------------------------------------|:--------------------|
|`--input` |Path to the _viash.yaml project configuration file. |`file`, default: `"_viash.yaml"` |


### Outputs

|Name       |Description                                                  |Attributes             |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Path to the directory where the resources will be synced to. |`file`, default: `"."` |


### Arguments

|Name        |Description                                                                                                |Attributes                            |
|:----------|:--------------------------------------------------|:--------------------|
|`--quiet`   |Displays the operations that would be performed using the specified command without actually running them. |`boolean_true`                        |
|`--dryrun`  |Does not display the operations performed from the specified command.                                      |`boolean_true`                        |
|`--delete`  |Files that exist in the destination but not in the source are deleted during sync.                         |`boolean_true`                        |
|`--exclude` |Exclude all files or objects from the command that matches the specified pattern.                          |List of `string`, multiple_sep: `";"` |

## Authors


  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (maintainer)

