---
title: "Regress out"
namespace: "Transform"
description: "Regress out (mostly) unwanted sources of variation."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `regress_out`  
Namespace: `transform`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/2.1.0/src/transform/regress_out/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Uses simple linear regression. This is inspired by Seurat's regressOut function in R [Satija15]. 
Note that this function tends to overcorrect in certain circumstances as described in issue theislab/scanpy#526. See https://github.com/theislab/scanpy/issues/526

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.0 -latest \
  -main-script target/nextflow/transform/regress_out/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input.h5mu"
# output: "output.h5mu"
# output_compression: "gzip"
modality: "rna"
# obs_keys: ["foo"]
# input_layer: "X_normalized"
# output_layer: "X_regressed"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.0 -latest \
  -profile docker \
  -main-script target/nextflow/transform/regress_out/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                   |Description                                                                                                                           |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`              |Input h5mu file                                                                                                                       |`file`, required, example: `"input.h5mu"`  |
|`--output`             |Output h5mu file.                                                                                                                     |`file`, required, default: `"output.h5mu"` |
|`--output_compression` |The compression format to be used on the output h5mu object.                                                                          |`string`, example: `"gzip"`                |
|`--modality`           |Which modality (one or more) to run this component on.                                                                                |`string`, default: `"rna"`                 |
|`--obs_keys`           |Which .obs keys to regress on.                                                                                                        |List of `string`, multiple_sep: `";"`      |
|`--input_layer`        |The layer of the adata object to regress on. If not provided, the X attribute of the adata object will be used.                       |`string`, example: `"X_normalized"`        |
|`--output_layer`       |The layer of the adata object containing the regressed count data. If not provided, the X attribute of the adata object will be used. |`string`, example: `"X_regressed"`         |

## Authors


  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (maintainer, contributor)

