---
title: "Fastqc"
namespace: "Qc"
description: "Fastqc component, please see https://www.bioinformatics.babraham.ac.uk/projects/fastqc/."
type: "module"
toc: false
---

::: {.column-margin}

### Info

ID: `fastqc`  
Namespace: `qc`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/1.0.1/src/qc/fastqc/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::

This component can take one or more files (by means of shell globbing) or a complete directory

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -main-script target/nextflow/qc/fastqc/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
mode: "files"
input: # please fill in - example: "fastq_dir"
# output: "$id.$key.output.output"
# threads: 123

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 1.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/qc/fastqc/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name        |Description                                                                                                         |Attributes                               |
|:----------|:--------------------------------------------------|:--------------------|
|`--mode`    |The mode in which the component works. Can be either files or dir.                                                  |`string`, default: `"files"`             |
|`--input`   |Directory containing input fastq files.                                                                             |`file`, required, example: `"fastq_dir"` |
|`--output`  |Output directory to write reports to.                                                                               |`file`, required, example: `"qc"`        |
|`--threads` |Specifies the number of files which can be processed simultaneously. Each thread will be allocated 250MB of memory. |`integer`                                |

