---
title: "GDO Singlesample"
namespace: "Workflows/gdo"
description: "Processing unimodal single-sample guide-derived oligonucleotide (GDO) data."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `gdo_singlesample`  
Namespace: `workflows/gdo`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/2.1.0/src/workflows/gdo/gdo_singlesample/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.0 -latest \
  -main-script target/nextflow/workflows/gdo/gdo_singlesample/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Input
id: # please fill in - example: "foo"
input: # please fill in - example: "dataset.h5mu"
# layer: "foo"

# Output
# output: "$id.$key.output.h5mu"

# Filtering options
# min_counts: 200
# max_counts: 5000000
# min_guides_per_cell: 200
# max_guides_per_cell: 1500000
# min_cells_per_guide: 3

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.1.0 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/gdo/gdo_singlesample/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Input

|Name      |Description                                             |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`    |ID of the sample.                                       |`string`, required, example: `"foo"`        |
|`--input` |Path to the sample.                                     |`file`, required, example: `"dataset.h5mu"` |
|`--layer` |Input layer to start from. By default, .X will be used. |`string`                                    |


### Output

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### Filtering options

|Name                    |Description                                 |Attributes                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--min_counts`          |Minimum number of counts captured per cell. |`integer`, example: `200`     |
|`--max_counts`          |Maximum number of counts captured per cell. |`integer`, example: `5000000` |
|`--min_guides_per_cell` |Minimum of non-zero values per cell.        |`integer`, example: `200`     |
|`--max_guides_per_cell` |Maximum of non-zero values per cell.        |`integer`, example: `1500000` |
|`--min_cells_per_guide` |Minimum of non-zero values per gene.        |`integer`, example: `3`       |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v10(filter)
    v18(gdo_filter_with_counts)
    v25(cross)
    v35(cross)
    v41(filter)
    v71(concat)
    v49(gdo_do_filter)
    v56(cross)
    v66(cross)
    v78(cross)
    v85(cross)
    v97(cross)
    v104(cross)
    v108(Output)
    v0-->v2
    v2-->v10
    v10-->v18
    v18-->v25
    v10-->v25
    v10-->v35
    v41-->v49
    v49-->v56
    v41-->v56
    v41-->v66
    v66-->v71
    v71-->v78
    v2-->v78
    v78-->v85
    v2-->v85
    v2-->v97
    v97-->v104
    v2-->v104
    v104-->v108
    v35-->v41
    v18-->v35
    v49-->v66
    v71-->v97
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v10 fill:#e3dcea,stroke:#7a4baa;
    style v18 fill:#e3dcea,stroke:#7a4baa;
    style v25 fill:#e3dcea,stroke:#7a4baa;
    style v35 fill:#e3dcea,stroke:#7a4baa;
    style v41 fill:#e3dcea,stroke:#7a4baa;
    style v71 fill:#e3dcea,stroke:#7a4baa;
    style v49 fill:#e3dcea,stroke:#7a4baa;
    style v56 fill:#e3dcea,stroke:#7a4baa;
    style v66 fill:#e3dcea,stroke:#7a4baa;
    style v78 fill:#e3dcea,stroke:#7a4baa;
    style v85 fill:#e3dcea,stroke:#7a4baa;
    style v97 fill:#e3dcea,stroke:#7a4baa;
    style v104 fill:#e3dcea,stroke:#7a4baa;
    style v108 fill:#e3dcea,stroke:#7a4baa;

```

