---
title: "Cell Ranger post-processing"
namespace: "Workflows/ingestion"
description: "Post-processing Cell Ranger datasets."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `cellranger_postprocessing`  
Namespace: `workflows/ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/2.0.1/src/workflows/ingestion/cellranger_postprocessing/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.0.1 -latest \
  -main-script target/nextflow/workflows/ingestion/cellranger_postprocessing/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"

# Outputs
# output: "$id.$key.output"

# Correction arguments
perform_correction: false
cellbender_epochs: 150

# Filtering arguments
# min_genes: 100
# min_counts: 1000

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/ingestion/cellranger_postprocessing/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                                                       |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`    |ID of the sample.                                                                 |`string`, required, example: `"foo"`      |
|`--input` |Input h5mu file created by running Cell Ranger and converting its output to h5mu. |`file`, required, example: `"input.h5mu"` |


### Outputs

|Name       |Description              |Attributes |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |The converted h5mu file. |`file`     |


### Correction arguments

|Name                   |Description                                                   |Attributes                |
|:----------|:--------------------------------------------------|:--------------------|
|`--perform_correction` |Whether or not to run CellBender to perform count correction. |`boolean_true`            |
|`--cellbender_epochs`  |Number of epochs to run CellBender for.                       |`integer`, default: `150` |


### Filtering arguments

|Name           |Description                                                              |Attributes                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--min_genes`  |Minimum number of counts required for a cell to pass filtering.          |`integer`, example: `100`  |
|`--min_counts` |Minimum number of genes expressed required for a cell to pass filtering. |`integer`, example: `1000` |

## Authors


  * Angela Oliveira Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) [{{< fa brands linkedin >}}](https://linkedin.com/in/aopisco) (author)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author, maintainer)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v12(branch)
    v39(concat)
    v17(cellbender_remove_background)
    v24(cross)
    v34(cross)
    v43(branch)
    v70(concat)
    v48(filter_with_counts)
    v55(cross)
    v65(cross)
    v71(filter)
    v101(concat)
    v79(publish)
    v86(cross)
    v96(cross)
    v108(cross)
    v115(cross)
    v127(cross)
    v134(cross)
    v138(Output)
    v12-->v39
    v43-->v70
    v70-->v71
    v0-->v2
    v12-->v17
    v17-->v24
    v12-->v24
    v12-->v34
    v34-->v39
    v43-->v48
    v48-->v55
    v43-->v55
    v43-->v65
    v65-->v70
    v71-->v79
    v79-->v86
    v71-->v86
    v71-->v96
    v96-->v101
    v101-->v108
    v2-->v108
    v108-->v115
    v2-->v115
    v2-->v127
    v127-->v134
    v2-->v134
    v134-->v138
    v2-->v12
    v17-->v34
    v39-->v43
    v48-->v65
    v79-->v96
    v101-->v127
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v12 fill:#e3dcea,stroke:#7a4baa;
    style v39 fill:#e3dcea,stroke:#7a4baa;
    style v17 fill:#e3dcea,stroke:#7a4baa;
    style v24 fill:#e3dcea,stroke:#7a4baa;
    style v34 fill:#e3dcea,stroke:#7a4baa;
    style v43 fill:#e3dcea,stroke:#7a4baa;
    style v70 fill:#e3dcea,stroke:#7a4baa;
    style v48 fill:#e3dcea,stroke:#7a4baa;
    style v55 fill:#e3dcea,stroke:#7a4baa;
    style v65 fill:#e3dcea,stroke:#7a4baa;
    style v71 fill:#e3dcea,stroke:#7a4baa;
    style v101 fill:#e3dcea,stroke:#7a4baa;
    style v79 fill:#e3dcea,stroke:#7a4baa;
    style v86 fill:#e3dcea,stroke:#7a4baa;
    style v96 fill:#e3dcea,stroke:#7a4baa;
    style v108 fill:#e3dcea,stroke:#7a4baa;
    style v115 fill:#e3dcea,stroke:#7a4baa;
    style v127 fill:#e3dcea,stroke:#7a4baa;
    style v134 fill:#e3dcea,stroke:#7a4baa;
    style v138 fill:#e3dcea,stroke:#7a4baa;

```

