---
title: "Demux"
namespace: "Workflows/ingestion"
description: "A generic pipeline for running bcl2fastq, bcl-convert or Cell Ranger mkfastq."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `demux`  
Namespace: `workflows/ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/2.0.1/src/workflows/ingestion/demux/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Convert `.bcl` files to `.fastq` files using bcl2fastq, bcl-convert or Cell Ranger mkfastq.


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.0.1 -latest \
  -main-script target/nextflow/workflows/ingestion/demux/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
id: # please fill in - example: "foo"
input: # please fill in - example: "bcl_dir"
sample_sheet: # please fill in - example: "bcl_dir"
demultiplexer: "bcl2fastq"
# ignore_missing: true
# output_fastq: "$id.$key.output_fastq"
# output_fastqc: "$id.$key.output_fastqc"
# output_multiqc: "$id.$key.output_multiqc"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 2.0.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/ingestion/demux/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name               |Description                                                    |Attributes                               |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`             |ID of the sample.                                              |`string`, required, example: `"foo"`     |
|`--input`          |Input run directory                                            |`file`, required, example: `"bcl_dir"`   |
|`--sample_sheet`   |Pointer to the sample sheet                                    |`file`, required, example: `"bcl_dir"`   |
|`--demultiplexer`  |The multiplexer to use, one of bclconvert or mkfastq           |`string`, default: `"bcl2fastq"`         |
|`--ignore_missing` |Should the demultiplexer ignore missing entities (filter, ...) |`boolean`                                |
|`--output_fastq`   |Output directory containig fastq files                         |`file`, required, example: `"fastq_dir"` |
|`--output_fastqc`  |Reports directory produced by FastQC                           |`file`, example: `"reports_dir"`         |
|`--output_multiqc` |Reports directory produced by MultiQC                          |`file`, example: `"reports_dir"`         |

## Authors


  * Toni Verbeiren [{{< fa brands github >}}](https://github.com/tverbeiren) [{{< fa brands linkedin >}}](https://linkedin.com/in/verbeiren) (author, maintainer)

  * Marijke Van Moerbeke [{{< fa brands github >}}](https://github.com/mvanmoerbeke) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-3097-5621) [{{< fa brands linkedin >}}](https://linkedin.com/in/marijke-van-moerbeke-84303a34) (author)

  * Angela Oliveira Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) [{{< fa brands linkedin >}}](https://linkedin.com/in/aopisco) (author)

  * Samuel D'Souza [{{< fa brands github >}}](https://github.com/srdsam) [{{< fa brands linkedin >}}](https://linkedin.com/in/samuel-d-souza-887023150/) (author)

  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) [{{< fa brands linkedin >}}](https://linkedin.com/in/robrechtcannoodt) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v12(filter)
    v20(cellranger_mkfastq)
    v27(cross)
    v37(cross)
    v117(mix)
    v48(filter)
    v56(bcl_convert)
    v63(cross)
    v73(cross)
    v84(filter)
    v92(bcl2fastq)
    v99(cross)
    v109(cross)
    v118(filter)
    v126(fastqc)
    v133(cross)
    v143(cross)
    v149(filter)
    v179(concat)
    v157(multiqc)
    v164(cross)
    v174(cross)
    v186(cross)
    v193(cross)
    v205(cross)
    v212(cross)
    v216(Output)
    v117-->v118
    v0-->v2
    v12-->v20
    v20-->v27
    v12-->v27
    v12-->v37
    v48-->v56
    v56-->v63
    v48-->v63
    v48-->v73
    v84-->v92
    v92-->v99
    v84-->v99
    v84-->v109
    v118-->v126
    v126-->v133
    v118-->v133
    v118-->v143
    v149-->v157
    v157-->v164
    v149-->v164
    v149-->v174
    v174-->v179
    v179-->v186
    v2-->v186
    v186-->v193
    v2-->v193
    v2-->v205
    v205-->v212
    v2-->v212
    v212-->v216
    v2-->v12
    v37-->v117
    v20-->v37
    v2-->v48
    v73-->v117
    v56-->v73
    v2-->v84
    v109-->v117
    v92-->v109
    v143-->v149
    v126-->v143
    v157-->v174
    v179-->v205
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v12 fill:#e3dcea,stroke:#7a4baa;
    style v20 fill:#e3dcea,stroke:#7a4baa;
    style v27 fill:#e3dcea,stroke:#7a4baa;
    style v37 fill:#e3dcea,stroke:#7a4baa;
    style v117 fill:#e3dcea,stroke:#7a4baa;
    style v48 fill:#e3dcea,stroke:#7a4baa;
    style v56 fill:#e3dcea,stroke:#7a4baa;
    style v63 fill:#e3dcea,stroke:#7a4baa;
    style v73 fill:#e3dcea,stroke:#7a4baa;
    style v84 fill:#e3dcea,stroke:#7a4baa;
    style v92 fill:#e3dcea,stroke:#7a4baa;
    style v99 fill:#e3dcea,stroke:#7a4baa;
    style v109 fill:#e3dcea,stroke:#7a4baa;
    style v118 fill:#e3dcea,stroke:#7a4baa;
    style v126 fill:#e3dcea,stroke:#7a4baa;
    style v133 fill:#e3dcea,stroke:#7a4baa;
    style v143 fill:#e3dcea,stroke:#7a4baa;
    style v149 fill:#e3dcea,stroke:#7a4baa;
    style v179 fill:#e3dcea,stroke:#7a4baa;
    style v157 fill:#e3dcea,stroke:#7a4baa;
    style v164 fill:#e3dcea,stroke:#7a4baa;
    style v174 fill:#e3dcea,stroke:#7a4baa;
    style v186 fill:#e3dcea,stroke:#7a4baa;
    style v193 fill:#e3dcea,stroke:#7a4baa;
    style v205 fill:#e3dcea,stroke:#7a4baa;
    style v212 fill:#e3dcea,stroke:#7a4baa;
    style v216 fill:#e3dcea,stroke:#7a4baa;

```

