---
title: "Integration"
namespace: "Multiomics"
description: "A pipeline for demultiplexing multimodal multi-sample RNA transcriptomics data."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `integration`  
Namespace: `multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/openpipelines/workflows/multiomics/integration){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.7.1 -latest \
  -main-script workflows/multiomics/integration/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.7.1 -latest \
  -profile docker \
  -main-script workflows/multiomics/integration/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                                                           |Attributes                                  |
|:---------|:-------------------------------------------------------------------------------------|:-------------------------------------------|
|`--id`    |ID of the sample.                                                                     |`string`, required, example: `"foo"`        |
|`--input` |Path to the sample.                                                                   |`file`, required, example: `"dataset.h5mu"` |
|`--layer` |use specified layer for expression values instead of the .X object from the modality. |`string`, default: `"log_normalized"`       |


### Outputs

|Name       |Description                     |Attributes                                 |
|:----------|:-------------------------------|:------------------------------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### PCA options

|Name                          |Description                                                                           |Attributes                   |
|:-----------------------------|:-------------------------------------------------------------------------------------|:----------------------------|
|`--obsm_pca`                  |In which .obsm slot to store the resulting PCA embedding.                             |`string`, default: `"X_pca"` |
|`--var_pca_feature_selection` |Column name in .var matrix that will be used to select which genes to run the PCA on. |`string`                     |


### Harmony integration options

|Name                |Description                                                                                                                                                                             |Attributes                                                  |
|:-------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------|
|`--obsm_integrated` |In which .obsm slot to store the resulting integrated embedding.                                                                                                                        |`string`, default: `"X_pca_integrated"`                     |
|`--obs_covariates`  |The .obs field(s) that define the covariate(s) to regress out.                                                                                                                          |`string`, required, example: `"batch"`, example: `"sample"` |
|`--rna_theta`       |Diversity clustering penalty parameter. Specify for each variable in group.by.vars.  theta=0 does not encourage any diversity. Larger values of theta result in more diverse clusters." |`double`, default: `2`                                      |


### Neighbour calculation

|Name                             |Description                                                                             |Attributes                            |
|:--------------------------------|:---------------------------------------------------------------------------------------|:-------------------------------------|
|`--uns_neighbors`                |In which .uns slot to store various neighbor output objects.                            |`string`, default: `"neighbors"`      |
|`--obsp_neighbor_distances`      |In which .obsp slot to store the distance matrix between the resulting neighbors.       |`string`, default: `"distances"`      |
|`--obsp_neighbor_connectivities` |In which .obsp slot to store the connectivities matrix between the resulting neighbors. |`string`, default: `"connectivities"` |


### Clustering options

|Name                  |Description                                                                    |Attributes                    |
|:---------------------|:------------------------------------------------------------------------------|:-----------------------------|
|`--obs_cluster`       |Name of the .obs key under which to add the cluster labels.                    |`string`, default: `"leiden"` |
|`--leiden_resolution` |Control the coarseness of the clustering. Higher values lead to more clusters. |`double`, default: `1`        |


### Umap options

|Name          |Description                                                |Attributes                    |
|:-------------|:----------------------------------------------------------|:-----------------------------|
|`--obsm_umap` |In which .obsm slot to store the resulting UMAP embedding. |`string`, default: `"X_umap"` |

## Authors

  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)
  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (author)
