---
title: "Process singlesample base"
namespace: "Workflows/multiomics"
description: "A pipeline to analyse a single multiomics sample."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `process_singlesample_base`  
Namespace: `workflows/multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.2.0/src/workflows/multiomics/process_singlesample_base/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -main-script target/_private/nextflow/workflows/multiomics/process_singlesample_base/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.2.0 -latest \
  -profile docker \
  -main-script target/_private/nextflow/workflows/multiomics/process_singlesample_base/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Output State

|Name                |Description |Attributes |
|:----------|:--------------------------------------------------|:--------------------|
|`--output_modality` |            |`string`   |


### Inputs

|Name           |Description                                                                                 |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`      |Path to the sample.                                                                         |`file`, required, example: `"input.h5mu"` |
|`--rna_layer`  |Input layer for the gene expression modality. If not specified, .X is used.                 |`string`                                  |
|`--prot_layer` |Input layer for the antibody capture modality. If not specified, .X is used.                |`string`                                  |
|`--gdo_layer`  |Input layer for the guide-derived oligonucleotide (GDO) data. If not specified, .X is used. |`string`                                  |


### Outputs

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### Sample ID options

Options for adding the id to .obs on the MuData object. Having a sample 
id present in a requirement of several components for this pipeline.



|Name                                    |Description                                                                                         |Attributes                       |
|:----------|:--------------------------------------------------|:--------------------|
|`--add_id_to_obs`                       |Add the value passed with --id to .obs.                                                             |`boolean`, default: `TRUE`       |
|`--add_id_obs_output`                   |.Obs column to add the sample IDs to. Required and only used when  --add_id_to_obs is set to 'true' |`string`, default: `"sample_id"` |
|`--add_id_make_observation_keys_unique` |Join the id to the .obs index (.obs_names).  Only used when --add_id_to_obs is set to 'true'.       |`boolean`, default: `TRUE`       |


### RNA filtering options

|Name                                |Description                                                                                                                                                                                                    |Attributes                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--rna_min_counts`                  |Minimum number of counts captured per cell.                                                                                                                                                                    |`integer`, example: `200`     |
|`--rna_max_counts`                  |Maximum number of counts captured per cell.                                                                                                                                                                    |`integer`, example: `5000000` |
|`--rna_min_genes_per_cell`          |Minimum of non-zero values per cell.                                                                                                                                                                           |`integer`, example: `200`     |
|`--rna_max_genes_per_cell`          |Maximum of non-zero values per cell.                                                                                                                                                                           |`integer`, example: `1500000` |
|`--rna_min_cells_per_gene`          |Minimum of non-zero values per gene.                                                                                                                                                                           |`integer`, example: `3`       |
|`--rna_min_fraction_mito`           |Minimum fraction of UMIs that are mitochondrial.                                                                                                                                                               |`double`, example: `0`        |
|`--rna_max_fraction_mito`           |Maximum fraction of UMIs that are mitochondrial.                                                                                                                                                               |`double`, example: `0.2`      |
|`--rna_min_fraction_ribo`           |Minimum fraction of UMIs that are mitochondrial.                                                                                                                                                               |`double`, example: `0`        |
|`--rna_max_fraction_ribo`           |Maximum fraction of UMIs that are mitochondrial.                                                                                                                                                               |`double`, example: `0.2`      |
|`--skip_scrublet_doublet_detection` |Skip the scrublet doublet detection step.                                                                                                                                                                      |`boolean_true`                |
|`--scrublet_score_threshold`        |Manual doublet score threshold passed to filter_with_scrublet. Cells with a doublet score above this value are classified as doublets. If not provided, the threshold is determined automatically by Scrublet. |`double`                      |


### CITE-seq filtering options

|Name                           |Description                             |Attributes                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--prot_min_counts`            |Minimum number of counts per cell.      |`integer`, example: `3`         |
|`--prot_max_counts`            |Minimum number of counts per cell.      |`integer`, example: `5000000`   |
|`--prot_min_proteins_per_cell` |Minimum of non-zero values per cell.    |`integer`, example: `200`       |
|`--prot_max_proteins_per_cell` |Maximum of non-zero values per cell.    |`integer`, example: `100000000` |
|`--prot_min_cells_per_protein` |Minimum of non-zero values per protein. |`integer`, example: `3`         |


### GDO filtering options

|Name                        |Description                           |Attributes                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--gdo_min_counts`          |Minimum number of counts per cell.    |`integer`, example: `3`         |
|`--gdo_max_counts`          |Minimum number of counts per cell.    |`integer`, example: `5000000`   |
|`--gdo_min_guides_per_cell` |Minimum of non-zero values per cell.  |`integer`, example: `200`       |
|`--gdo_max_guides_per_cell` |Maximum of non-zero values per cell.  |`integer`, example: `100000000` |
|`--gdo_min_cells_per_guide` |Minimum of non-zero values per guide. |`integer`, example: `3`         |


### Cross-modality filtering

|Name              |Description                                                                                                                                            |Attributes     |
|:----------|:--------------------------------------------------|:--------------------|
|`--intersect_obs` |After per-modality filtering, remove observations that are not present in all processed modalities so that each modality shares the same set of cells. |`boolean_true` |


### Mitochondrial & Ribosomal Gene Detection

|Name                                |Description                                                                                                                                                                                                                                                                               |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--var_gene_names`                  |.var column name to be used to detect mitochondrial/ribosomal genes instead of .var_names (default if not set). Gene names matching with the regex value from --mitochondrial_gene_regex or --ribosomal_gene_regex will be  identified as mitochondrial or ribosomal genes, respectively. |`string`, example: `"gene_symbol"`          |
|`--var_name_mitochondrial_genes`    |In which .var slot to store a boolean array corresponding the mitochondrial genes.                                                                                                                                                                                                        |`string`                                    |
|`--obs_name_mitochondrial_fraction` |When specified, write the fraction of counts originating from mitochondrial genes  (based on --mitochondrial_gene_regex) to an .obs column with the specified name. Requires --var_name_mitochondrial_genes.                                                                              |`string`                                    |
|`--mitochondrial_gene_regex`        |Regex string that identifies mitochondrial genes from --var_gene_names. By default will detect human and mouse mitochondrial genes from a gene symbol.                                                                                                                                    |`string`, default: `"^[mM][tT]-"`           |
|`--var_name_ribosomal_genes`        |In which .var slot to store a boolean array corresponding the ribosomal genes.                                                                                                                                                                                                            |`string`                                    |
|`--obs_name_ribosomal_fraction`     |When specified, write the fraction of counts originating from ribosomal genes  (based on --ribosomal_gene_regex) to an .obs column with the specified name. Requires --var_name_ribosomal_genes.                                                                                          |`string`                                    |
|`--ribosomal_gene_regex`            |Regex string that identifies ribosomal genes from --var_gene_names. By default will detect human and mouse ribosomal genes from a gene symbol.                                                                                                                                            |`string`, default: `"^[Mm]?[Rr][Pp][LlSs]"` |

## Authors


  * Dorien Roosen [{{< fa brands github >}}](https://github.com/dorien-er) [{{< fa brands linkedin >}}](https://linkedin.com/in/dorien-roosen) (author)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v15(filter)
    v20(add_id)
    v27(cross)
    v37(cross)
    v43(filter)
    v54(filter)
    v66(cross)
    v76(cross)
    v86(concat)
    v93(cross)
    v103(cross)
    v109(flatMap)
    v115(filter)
    v124(filter)
    v136(branch)
    v163(concat)
    v148(cross)
    v158(cross)
    v167(branch)
    v194(concat)
    v179(cross)
    v189(cross)
    v195(filter)
    v225(concat)
    v210(cross)
    v220(cross)
    v232(cross)
    v242(cross)
    v251(branch)
    v278(concat)
    v263(cross)
    v273(cross)
    v282(branch)
    v309(concat)
    v294(cross)
    v304(cross)
    v310(filter)
    v325(cross)
    v335(cross)
    v341(filter)
    v356(cross)
    v366(cross)
    v375(branch)
    v402(concat)
    v387(cross)
    v397(cross)
    v409(cross)
    v419(cross)
    v621(mix)
    v430(filter)
    v438(filter)
    v453(cross)
    v463(cross)
    v469(filter)
    v499(concat)
    v484(cross)
    v494(cross)
    v506(cross)
    v516(cross)
    v527(filter)
    v535(filter)
    v550(cross)
    v560(cross)
    v566(filter)
    v596(concat)
    v581(cross)
    v591(cross)
    v603(cross)
    v613(cross)
    v623(mix)
    v631(cross)
    v638(cross)
    v650(cross)
    v657(cross)
    v661(Output)
    subgraph group_split_modalities_workflow [split_modalities_workflow]
        v59(split_modalities_component)
    end
    subgraph group_rna_singlesample [rna_singlesample]
        v141(grep_mitochondrial_genes)
        v172(grep_ribosomal_genes)
        v203(calculate_qc_metrics)
        v256(delimit_fraction)
        v287(delimit_fraction)
        v318(rna_filter_with_counts)
        v349(rna_do_filter)
        v380(filter_with_scrublet)
    end
    subgraph group_prot_singlesample [prot_singlesample]
        v446(prot_filter_with_counts)
        v477(prot_do_filter)
    end
    subgraph group_gdo_singlesample [gdo_singlesample]
        v543(gdo_filter_with_counts)
        v574(gdo_do_filter)
    end
    v136-->v163
    v167-->v194
    v194-->v195
    v251-->v278
    v282-->v309
    v309-->v310
    v375-->v402
    v621-->v623
    v0-->v2
    v15-->v20
    v20-->v27
    v15-->v27
    v15-->v37
    v54-->v59
    v59-->v66
    v54-->v66
    v54-->v76
    v86-->v93
    v43-->v93
    v43-->v103
    v115-->v124
    v136-->v141
    v141-->v148
    v136-->v148
    v136-->v158
    v158-->v163
    v167-->v172
    v172-->v179
    v167-->v179
    v167-->v189
    v189-->v194
    v195-->v203
    v203-->v210
    v195-->v210
    v195-->v220
    v220-->v225
    v225-->v232
    v124-->v232
    v124-->v242
    v251-->v256
    v256-->v263
    v251-->v263
    v251-->v273
    v273-->v278
    v282-->v287
    v287-->v294
    v282-->v294
    v282-->v304
    v304-->v309
    v310-->v318
    v318-->v325
    v310-->v325
    v310-->v335
    v341-->v349
    v349-->v356
    v341-->v356
    v341-->v366
    v375-->v380
    v380-->v387
    v375-->v387
    v375-->v397
    v397-->v402
    v402-->v409
    v115-->v409
    v115-->v419
    v430-->v438
    v438-->v446
    v446-->v453
    v438-->v453
    v438-->v463
    v469-->v477
    v477-->v484
    v469-->v484
    v469-->v494
    v494-->v499
    v499-->v506
    v430-->v506
    v430-->v516
    v527-->v535
    v535-->v543
    v543-->v550
    v535-->v550
    v535-->v560
    v566-->v574
    v574-->v581
    v566-->v581
    v566-->v591
    v591-->v596
    v596-->v603
    v527-->v603
    v527-->v613
    v623-->v631
    v2-->v631
    v631-->v638
    v2-->v638
    v2-->v650
    v650-->v657
    v2-->v657
    v657-->v661
    v2-->v15
    v37-->v43
    v20-->v37
    v103-->v109
    v43-->v54
    v76-->v86
    v59-->v76
    v86-->v103
    v109-->v115
    v419-->v621
    v124-->v136
    v141-->v158
    v163-->v167
    v172-->v189
    v203-->v220
    v225-->v242
    v242-->v251
    v256-->v273
    v278-->v282
    v287-->v304
    v335-->v341
    v318-->v335
    v349-->v366
    v366-->v375
    v380-->v397
    v402-->v419
    v109-->v430
    v516-->v621
    v463-->v469
    v446-->v463
    v477-->v494
    v499-->v516
    v109-->v527
    v613-->v621
    v560-->v566
    v543-->v560
    v574-->v591
    v596-->v613
    v109-->v623
    v623-->v650
    style group_split_modalities_workflow fill:#F0F0F0,stroke:#969696;
    style group_rna_singlesample fill:#F0F0F0,stroke:#969696;
    style group_prot_singlesample fill:#F0F0F0,stroke:#969696;
    style group_gdo_singlesample fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v15 fill:#e3dcea,stroke:#7a4baa;
    style v20 fill:#e3dcea,stroke:#7a4baa;
    style v27 fill:#e3dcea,stroke:#7a4baa;
    style v37 fill:#e3dcea,stroke:#7a4baa;
    style v43 fill:#e3dcea,stroke:#7a4baa;
    style v54 fill:#e3dcea,stroke:#7a4baa;
    style v59 fill:#e3dcea,stroke:#7a4baa;
    style v66 fill:#e3dcea,stroke:#7a4baa;
    style v76 fill:#e3dcea,stroke:#7a4baa;
    style v86 fill:#e3dcea,stroke:#7a4baa;
    style v93 fill:#e3dcea,stroke:#7a4baa;
    style v103 fill:#e3dcea,stroke:#7a4baa;
    style v109 fill:#e3dcea,stroke:#7a4baa;
    style v115 fill:#e3dcea,stroke:#7a4baa;
    style v124 fill:#e3dcea,stroke:#7a4baa;
    style v136 fill:#e3dcea,stroke:#7a4baa;
    style v163 fill:#e3dcea,stroke:#7a4baa;
    style v141 fill:#e3dcea,stroke:#7a4baa;
    style v148 fill:#e3dcea,stroke:#7a4baa;
    style v158 fill:#e3dcea,stroke:#7a4baa;
    style v167 fill:#e3dcea,stroke:#7a4baa;
    style v194 fill:#e3dcea,stroke:#7a4baa;
    style v172 fill:#e3dcea,stroke:#7a4baa;
    style v179 fill:#e3dcea,stroke:#7a4baa;
    style v189 fill:#e3dcea,stroke:#7a4baa;
    style v195 fill:#e3dcea,stroke:#7a4baa;
    style v225 fill:#e3dcea,stroke:#7a4baa;
    style v203 fill:#e3dcea,stroke:#7a4baa;
    style v210 fill:#e3dcea,stroke:#7a4baa;
    style v220 fill:#e3dcea,stroke:#7a4baa;
    style v232 fill:#e3dcea,stroke:#7a4baa;
    style v242 fill:#e3dcea,stroke:#7a4baa;
    style v251 fill:#e3dcea,stroke:#7a4baa;
    style v278 fill:#e3dcea,stroke:#7a4baa;
    style v256 fill:#e3dcea,stroke:#7a4baa;
    style v263 fill:#e3dcea,stroke:#7a4baa;
    style v273 fill:#e3dcea,stroke:#7a4baa;
    style v282 fill:#e3dcea,stroke:#7a4baa;
    style v309 fill:#e3dcea,stroke:#7a4baa;
    style v287 fill:#e3dcea,stroke:#7a4baa;
    style v294 fill:#e3dcea,stroke:#7a4baa;
    style v304 fill:#e3dcea,stroke:#7a4baa;
    style v310 fill:#e3dcea,stroke:#7a4baa;
    style v318 fill:#e3dcea,stroke:#7a4baa;
    style v325 fill:#e3dcea,stroke:#7a4baa;
    style v335 fill:#e3dcea,stroke:#7a4baa;
    style v341 fill:#e3dcea,stroke:#7a4baa;
    style v349 fill:#e3dcea,stroke:#7a4baa;
    style v356 fill:#e3dcea,stroke:#7a4baa;
    style v366 fill:#e3dcea,stroke:#7a4baa;
    style v375 fill:#e3dcea,stroke:#7a4baa;
    style v402 fill:#e3dcea,stroke:#7a4baa;
    style v380 fill:#e3dcea,stroke:#7a4baa;
    style v387 fill:#e3dcea,stroke:#7a4baa;
    style v397 fill:#e3dcea,stroke:#7a4baa;
    style v409 fill:#e3dcea,stroke:#7a4baa;
    style v419 fill:#e3dcea,stroke:#7a4baa;
    style v621 fill:#e3dcea,stroke:#7a4baa;
    style v430 fill:#e3dcea,stroke:#7a4baa;
    style v438 fill:#e3dcea,stroke:#7a4baa;
    style v446 fill:#e3dcea,stroke:#7a4baa;
    style v453 fill:#e3dcea,stroke:#7a4baa;
    style v463 fill:#e3dcea,stroke:#7a4baa;
    style v469 fill:#e3dcea,stroke:#7a4baa;
    style v499 fill:#e3dcea,stroke:#7a4baa;
    style v477 fill:#e3dcea,stroke:#7a4baa;
    style v484 fill:#e3dcea,stroke:#7a4baa;
    style v494 fill:#e3dcea,stroke:#7a4baa;
    style v506 fill:#e3dcea,stroke:#7a4baa;
    style v516 fill:#e3dcea,stroke:#7a4baa;
    style v527 fill:#e3dcea,stroke:#7a4baa;
    style v535 fill:#e3dcea,stroke:#7a4baa;
    style v543 fill:#e3dcea,stroke:#7a4baa;
    style v550 fill:#e3dcea,stroke:#7a4baa;
    style v560 fill:#e3dcea,stroke:#7a4baa;
    style v566 fill:#e3dcea,stroke:#7a4baa;
    style v596 fill:#e3dcea,stroke:#7a4baa;
    style v574 fill:#e3dcea,stroke:#7a4baa;
    style v581 fill:#e3dcea,stroke:#7a4baa;
    style v591 fill:#e3dcea,stroke:#7a4baa;
    style v603 fill:#e3dcea,stroke:#7a4baa;
    style v613 fill:#e3dcea,stroke:#7a4baa;
    style v623 fill:#e3dcea,stroke:#7a4baa;
    style v631 fill:#e3dcea,stroke:#7a4baa;
    style v638 fill:#e3dcea,stroke:#7a4baa;
    style v650 fill:#e3dcea,stroke:#7a4baa;
    style v657 fill:#e3dcea,stroke:#7a4baa;
    style v661 fill:#e3dcea,stroke:#7a4baa;

```

