---
title: "Process batches"
namespace: "Workflows/multiomics"
description: "This workflow serves as an entrypoint into the 'full_pipeline' in order to re-run the multisample processing and the integration setup."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `process_batches`  
Namespace: `workflows/multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.1.1/src/workflows/multiomics/process_batches/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::

An input .h5mu file will 
first be split in order to run the multisample processing per modality. Next, the modalities
are merged again and the integration setup pipeline is executed. Please note that this workflow
assumes that samples from multiple pipelines are already concatenated. 


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -main-script target/nextflow/workflows/multiomics/process_batches/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "foo"
input: # please fill in - example: ["input.h5mu"]
# rna_layer: "foo"
# prot_layer: "foo"

# Outputs
# output: "$id.$key.output.h5mu"

# Cross-modality filtering
intersect_obs: false

# Highly variable features detection
highly_variable_features_var_output: "filter_with_hvg"
highly_variable_features_obs_batch_key: "sample_id"
# highly_variable_features_features_to_exclude: ["MT-CO1", "MT-CO2", "MT-ND1"]

# QC metrics calculation options
var_qc_metrics: ["filter_with_hvg"]
top_n_vars: [50, 100, 200, 500]

# PCA options
pca_overwrite: false

# CLR options
clr_axis: 0

# RNA Scaling options
rna_enable_scaling: false
rna_scaling_output_layer: "scaled"
rna_scaling_pca_obsm_output: "scaled_pca"
rna_scaling_pca_loadings_varm_output: "scaled_pca_loadings"
rna_scaling_pca_variance_uns_output: "scaled_pca_variance"
rna_scaling_umap_obsm_output: "scaled_umap"
# rna_scaling_max_value: 123.0
rna_scaling_zero_center: true

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.1 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/multiomics/process_batches/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name           |Description                                                                  |Attributes                                                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`         |ID of the sample.                                                            |`string`, required, example: `"foo"`                                   |
|`--input`      |Path to the sample.                                                          |List of `file`, required, example: `"input.h5mu"`, multiple_sep: `";"` |
|`--rna_layer`  |Input layer for the gene expression modality. If not specified, .X is used.  |`string`                                                               |
|`--prot_layer` |Input layer for the antibody capture modality. If not specified, .X is used. |`string`                                                               |


### Outputs

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### Cross-modality filtering

|Name              |Description                                                                                                                                                         |Attributes     |
|:----------|:--------------------------------------------------|:--------------------|
|`--intersect_obs` |After per-modality multisample processing, remove observations that are not present in all processed modalities so that each modality shares the same set of cells. |`boolean_true` |


### Highly variable features detection

|Name                                             |Description                                                                                                                                                                                                    |Attributes                                                                     |
|:----------|:--------------------------------------------------|:--------------------|
|`--highly_variable_features_var_output`          |In which .var slot to store a boolean array corresponding to the highly variable genes.                                                                                                                        |`string`, default: `"filter_with_hvg"`                                         |
|`--highly_variable_features_obs_batch_key`       |If specified, highly-variable genes are selected within each batch separately and merged. This simple  process avoids the selection of batch-specific genes and acts as a lightweight batch correction method. |`string`, default: `"sample_id"`                                               |
|`--highly_variable_features_features_to_exclude` |User-defined list of feature names to exclude from HVG calculation. These features will be excluded from HVG selection but will remain in the output data.                                                     |List of `string`, example: `"MT-CO1", "MT-CO2", "MT-ND1"`, multiple_sep: `";"` |


### QC metrics calculation options

|Name               |Description                                                                                                                                                                                                                    |Attributes                                                                                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--var_qc_metrics` |Keys to select a boolean (containing only True or False) column from .var. For each cell, calculate the proportion of total values for genes which are labeled 'True',  compared to the total sum of the values for all genes. |List of `string`, default: `"filter_with_hvg"`, example: `"ercc,highly_variable"`, multiple_sep: `","` |
|`--top_n_vars`     |Number of top vars to be used to calculate cumulative proportions. If not specified, proportions are not calculated. `--top_n_vars 20,50` finds cumulative proportion to the 20th and 50th most expressed vars.                |List of `integer`, default: `50, 100, 200, 500`, multiple_sep: `","`                                   |


### PCA options

|Name              |Description                             |Attributes     |
|:----------|:--------------------------------------------------|:--------------------|
|`--pca_overwrite` |Allow overwriting slots for PCA output. |`boolean_true` |


### CLR options

|Name         |Description                                |Attributes              |
|:----------|:--------------------------------------------------|:--------------------|
|`--clr_axis` |Axis to perform the CLR transformation on. |`integer`, default: `0` |


### RNA Scaling options

Options for enabling scaling of the log-normalized data to unit variance and zero mean.
The scaled data will be output a different layer and representation with reduced dimensions
will be created and stored in addition to the non-scaled data.



|Name                                     |Description                                                                                                                                                  |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--rna_enable_scaling`                   |Enable scaling for the RNA modality.                                                                                                                         |`boolean_true`                             |
|`--rna_scaling_output_layer`             |Output layer where the scaled log-normalized data will be stored.                                                                                            |`string`, default: `"scaled"`              |
|`--rna_scaling_pca_obsm_output`          |Name of the .obsm key where the PCA representation of the log-normalized and scaled data is stored.                                                          |`string`, default: `"scaled_pca"`          |
|`--rna_scaling_pca_loadings_varm_output` |Name of the .varm key where the PCA loadings of the log-normalized and scaled data is stored.                                                                |`string`, default: `"scaled_pca_loadings"` |
|`--rna_scaling_pca_variance_uns_output`  |Name of the .uns key where the variance and variance ratio will be stored as a map. The map will contain two keys: variance and variance_ratio respectively. |`string`, default: `"scaled_pca_variance"` |
|`--rna_scaling_umap_obsm_output`         |Name of the .obsm key where the UMAP representation of the log-normalized and scaled data is stored.                                                         |`string`, default: `"scaled_umap"`         |
|`--rna_scaling_max_value`                |Clip (truncate) data to this value after scaling. If not specified, do not clip.                                                                             |`double`                                   |
|`--rna_scaling_zero_center`              |If set, omit zero-centering variables, which allows to handle sparse input efficiently."                                                                     |`boolean_false`                            |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author, maintainer)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v11(filter)
    v22(filter)
    v34(cross)
    v44(cross)
    v54(concat)
    v61(cross)
    v71(cross)
    v77(flatMap)
    v85(filter)
    v93(filter)
    v100(filter)
    v115(cross)
    v125(cross)
    v131(filter)
    v146(cross)
    v156(cross)
    v162(filter)
    v192(concat)
    v177(cross)
    v187(cross)
    v199(cross)
    v209(cross)
    v218(branch)
    v245(concat)
    v230(cross)
    v240(cross)
    v246(filter)
    v261(cross)
    v271(cross)
    v277(filter)
    v400(concat)
    v289(branch)
    v316(concat)
    v301(cross)
    v311(cross)
    v320(branch)
    v347(concat)
    v332(cross)
    v342(cross)
    v348(filter)
    v378(concat)
    v363(cross)
    v373(cross)
    v385(cross)
    v395(cross)
    v407(cross)
    v417(cross)
    v615(mix)
    v428(filter)
    v436(filter)
    v451(cross)
    v461(cross)
    v467(filter)
    v590(concat)
    v479(branch)
    v506(concat)
    v491(cross)
    v501(cross)
    v510(branch)
    v537(concat)
    v522(cross)
    v532(cross)
    v538(filter)
    v568(concat)
    v553(cross)
    v563(cross)
    v575(cross)
    v585(cross)
    v597(cross)
    v607(cross)
    v617(mix)
    v625(filter)
    v633(merge)
    v640(cross)
    v650(cross)
    v660(branch)
    v687(concat)
    v665(intersect_obs)
    v672(cross)
    v682(cross)
    v691(branch)
    v903(concat)
    v696(filter)
    v711(cross)
    v721(cross)
    v727(filter)
    v881(concat)
    v736(filter)
    v751(cross)
    v761(cross)
    v770(branch)
    v797(concat)
    v782(cross)
    v792(cross)
    v801(branch)
    v828(concat)
    v813(cross)
    v823(cross)
    v832(branch)
    v859(concat)
    v844(cross)
    v854(cross)
    v866(cross)
    v876(cross)
    v888(cross)
    v898(cross)
    v907(branch)
    v1119(concat)
    v912(filter)
    v927(cross)
    v937(cross)
    v943(filter)
    v1097(concat)
    v952(filter)
    v967(cross)
    v977(cross)
    v986(branch)
    v1013(concat)
    v998(cross)
    v1008(cross)
    v1017(branch)
    v1044(concat)
    v1029(cross)
    v1039(cross)
    v1048(branch)
    v1075(concat)
    v1060(cross)
    v1070(cross)
    v1082(cross)
    v1092(cross)
    v1104(cross)
    v1114(cross)
    v1123(branch)
    v1335(concat)
    v1128(filter)
    v1143(cross)
    v1153(cross)
    v1159(filter)
    v1313(concat)
    v1168(filter)
    v1183(cross)
    v1193(cross)
    v1202(branch)
    v1229(concat)
    v1214(cross)
    v1224(cross)
    v1233(branch)
    v1260(concat)
    v1245(cross)
    v1255(cross)
    v1264(branch)
    v1291(concat)
    v1276(cross)
    v1286(cross)
    v1298(cross)
    v1308(cross)
    v1320(cross)
    v1330(cross)
    v1342(cross)
    v1349(cross)
    v1361(cross)
    v1368(cross)
    v1372(Output)
    subgraph group_split_modalities_workflow [split_modalities_workflow]
        v27(split_modalities_component)
    end
    subgraph group_rna_multisample [rna_multisample]
        v108(normalize_total)
        v139(log1p)
        v170(delete_layer)
        v223(scale)
        v254(highly_variable_features_scanpy)
        v294(grep_mitochondrial_genes)
        v325(grep_ribosomal_genes)
        v356(calculate_qc_metrics)
    end
    subgraph group_prot_multisample [prot_multisample]
        v444(clr)
        v484(grep_mitochondrial_genes)
        v515(grep_ribosomal_genes)
        v546(calculate_qc_metrics)
    end
    subgraph group_dimensionality_reduction_rna [dimensionality_reduction_rna]
        v704(pca)
        v744(find_neighbors)
        v775(leiden)
        v806(move_obsm_to_obs)
        v837(umap)
    end
    subgraph group_dimensionality_reduction_scaling_rna [dimensionality_reduction_scaling_rna]
        v920(pca)
        v960(find_neighbors)
        v991(leiden)
        v1022(move_obsm_to_obs)
        v1053(umap)
    end
    subgraph group_dimensionality_reduction_prot [dimensionality_reduction_prot]
        v1136(pca)
        v1176(find_neighbors)
        v1207(leiden)
        v1238(move_obsm_to_obs)
        v1269(umap)
    end
    v218-->v245
    v245-->v246
    v289-->v316
    v320-->v347
    v347-->v348
    v479-->v506
    v510-->v537
    v537-->v538
    v615-->v617
    v660-->v687
    v691-->v903
    v770-->v797
    v801-->v828
    v832-->v859
    v907-->v1119
    v986-->v1013
    v1017-->v1044
    v1048-->v1075
    v1123-->v1335
    v1202-->v1229
    v1233-->v1260
    v1264-->v1291
    v0-->v2
    v22-->v27
    v27-->v34
    v22-->v34
    v22-->v44
    v54-->v61
    v11-->v61
    v11-->v71
    v85-->v93
    v93-->v100
    v100-->v108
    v108-->v115
    v100-->v115
    v100-->v125
    v131-->v139
    v139-->v146
    v131-->v146
    v131-->v156
    v162-->v170
    v170-->v177
    v162-->v177
    v162-->v187
    v187-->v192
    v192-->v199
    v93-->v199
    v93-->v209
    v218-->v223
    v223-->v230
    v218-->v230
    v218-->v240
    v240-->v245
    v246-->v254
    v254-->v261
    v246-->v261
    v246-->v271
    v289-->v294
    v294-->v301
    v289-->v301
    v289-->v311
    v311-->v316
    v320-->v325
    v325-->v332
    v320-->v332
    v320-->v342
    v342-->v347
    v348-->v356
    v356-->v363
    v348-->v363
    v348-->v373
    v373-->v378
    v378-->v385
    v277-->v385
    v277-->v395
    v395-->v400
    v400-->v407
    v85-->v407
    v85-->v417
    v428-->v436
    v436-->v444
    v444-->v451
    v436-->v451
    v436-->v461
    v479-->v484
    v484-->v491
    v479-->v491
    v479-->v501
    v501-->v506
    v510-->v515
    v515-->v522
    v510-->v522
    v510-->v532
    v532-->v537
    v538-->v546
    v546-->v553
    v538-->v553
    v538-->v563
    v563-->v568
    v568-->v575
    v467-->v575
    v467-->v585
    v585-->v590
    v590-->v597
    v428-->v597
    v428-->v607
    v625-->v633
    v633-->v640
    v625-->v640
    v625-->v650
    v660-->v665
    v665-->v672
    v660-->v672
    v660-->v682
    v682-->v687
    v691-->v696
    v696-->v704
    v704-->v711
    v696-->v711
    v696-->v721
    v727-->v736
    v736-->v744
    v744-->v751
    v736-->v751
    v736-->v761
    v770-->v775
    v775-->v782
    v770-->v782
    v770-->v792
    v792-->v797
    v801-->v806
    v806-->v813
    v801-->v813
    v801-->v823
    v823-->v828
    v832-->v837
    v837-->v844
    v832-->v844
    v832-->v854
    v854-->v859
    v859-->v866
    v727-->v866
    v727-->v876
    v876-->v881
    v881-->v888
    v691-->v888
    v691-->v898
    v898-->v903
    v907-->v912
    v912-->v920
    v920-->v927
    v912-->v927
    v912-->v937
    v943-->v952
    v952-->v960
    v960-->v967
    v952-->v967
    v952-->v977
    v986-->v991
    v991-->v998
    v986-->v998
    v986-->v1008
    v1008-->v1013
    v1017-->v1022
    v1022-->v1029
    v1017-->v1029
    v1017-->v1039
    v1039-->v1044
    v1048-->v1053
    v1053-->v1060
    v1048-->v1060
    v1048-->v1070
    v1070-->v1075
    v1075-->v1082
    v943-->v1082
    v943-->v1092
    v1092-->v1097
    v1097-->v1104
    v907-->v1104
    v907-->v1114
    v1114-->v1119
    v1123-->v1128
    v1128-->v1136
    v1136-->v1143
    v1128-->v1143
    v1128-->v1153
    v1159-->v1168
    v1168-->v1176
    v1176-->v1183
    v1168-->v1183
    v1168-->v1193
    v1202-->v1207
    v1207-->v1214
    v1202-->v1214
    v1202-->v1224
    v1224-->v1229
    v1233-->v1238
    v1238-->v1245
    v1233-->v1245
    v1233-->v1255
    v1255-->v1260
    v1264-->v1269
    v1269-->v1276
    v1264-->v1276
    v1264-->v1286
    v1286-->v1291
    v1291-->v1298
    v1159-->v1298
    v1159-->v1308
    v1308-->v1313
    v1313-->v1320
    v1123-->v1320
    v1123-->v1330
    v1330-->v1335
    v1335-->v1342
    v2-->v1342
    v1342-->v1349
    v2-->v1349
    v2-->v1361
    v1361-->v1368
    v2-->v1368
    v1368-->v1372
    v2-->v11
    v71-->v77
    v11-->v22
    v44-->v54
    v27-->v44
    v54-->v71
    v77-->v85
    v417-->v615
    v125-->v131
    v108-->v125
    v156-->v162
    v139-->v156
    v170-->v187
    v192-->v209
    v209-->v218
    v223-->v240
    v271-->v277
    v254-->v271
    v277-->v289
    v294-->v311
    v316-->v320
    v325-->v342
    v356-->v373
    v378-->v395
    v400-->v417
    v77-->v428
    v607-->v615
    v461-->v467
    v444-->v461
    v467-->v479
    v484-->v501
    v506-->v510
    v515-->v532
    v546-->v563
    v568-->v585
    v590-->v607
    v77-->v617
    v617-->v625
    v633-->v650
    v650-->v660
    v665-->v682
    v687-->v691
    v721-->v727
    v704-->v721
    v744-->v761
    v761-->v770
    v775-->v792
    v797-->v801
    v806-->v823
    v828-->v832
    v837-->v854
    v859-->v876
    v881-->v898
    v903-->v907
    v937-->v943
    v920-->v937
    v960-->v977
    v977-->v986
    v991-->v1008
    v1013-->v1017
    v1022-->v1039
    v1044-->v1048
    v1053-->v1070
    v1075-->v1092
    v1097-->v1114
    v1119-->v1123
    v1153-->v1159
    v1136-->v1153
    v1176-->v1193
    v1193-->v1202
    v1207-->v1224
    v1229-->v1233
    v1238-->v1255
    v1260-->v1264
    v1269-->v1286
    v1291-->v1308
    v1313-->v1330
    v1335-->v1361
    style group_split_modalities_workflow fill:#F0F0F0,stroke:#969696;
    style group_rna_multisample fill:#F0F0F0,stroke:#969696;
    style group_prot_multisample fill:#F0F0F0,stroke:#969696;
    style group_dimensionality_reduction_rna fill:#F0F0F0,stroke:#969696;
    style group_dimensionality_reduction_scaling_rna fill:#F0F0F0,stroke:#969696;
    style group_dimensionality_reduction_prot fill:#F0F0F0,stroke:#969696;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v11 fill:#e3dcea,stroke:#7a4baa;
    style v22 fill:#e3dcea,stroke:#7a4baa;
    style v27 fill:#e3dcea,stroke:#7a4baa;
    style v34 fill:#e3dcea,stroke:#7a4baa;
    style v44 fill:#e3dcea,stroke:#7a4baa;
    style v54 fill:#e3dcea,stroke:#7a4baa;
    style v61 fill:#e3dcea,stroke:#7a4baa;
    style v71 fill:#e3dcea,stroke:#7a4baa;
    style v77 fill:#e3dcea,stroke:#7a4baa;
    style v85 fill:#e3dcea,stroke:#7a4baa;
    style v93 fill:#e3dcea,stroke:#7a4baa;
    style v100 fill:#e3dcea,stroke:#7a4baa;
    style v108 fill:#e3dcea,stroke:#7a4baa;
    style v115 fill:#e3dcea,stroke:#7a4baa;
    style v125 fill:#e3dcea,stroke:#7a4baa;
    style v131 fill:#e3dcea,stroke:#7a4baa;
    style v139 fill:#e3dcea,stroke:#7a4baa;
    style v146 fill:#e3dcea,stroke:#7a4baa;
    style v156 fill:#e3dcea,stroke:#7a4baa;
    style v162 fill:#e3dcea,stroke:#7a4baa;
    style v192 fill:#e3dcea,stroke:#7a4baa;
    style v170 fill:#e3dcea,stroke:#7a4baa;
    style v177 fill:#e3dcea,stroke:#7a4baa;
    style v187 fill:#e3dcea,stroke:#7a4baa;
    style v199 fill:#e3dcea,stroke:#7a4baa;
    style v209 fill:#e3dcea,stroke:#7a4baa;
    style v218 fill:#e3dcea,stroke:#7a4baa;
    style v245 fill:#e3dcea,stroke:#7a4baa;
    style v223 fill:#e3dcea,stroke:#7a4baa;
    style v230 fill:#e3dcea,stroke:#7a4baa;
    style v240 fill:#e3dcea,stroke:#7a4baa;
    style v246 fill:#e3dcea,stroke:#7a4baa;
    style v254 fill:#e3dcea,stroke:#7a4baa;
    style v261 fill:#e3dcea,stroke:#7a4baa;
    style v271 fill:#e3dcea,stroke:#7a4baa;
    style v277 fill:#e3dcea,stroke:#7a4baa;
    style v400 fill:#e3dcea,stroke:#7a4baa;
    style v289 fill:#e3dcea,stroke:#7a4baa;
    style v316 fill:#e3dcea,stroke:#7a4baa;
    style v294 fill:#e3dcea,stroke:#7a4baa;
    style v301 fill:#e3dcea,stroke:#7a4baa;
    style v311 fill:#e3dcea,stroke:#7a4baa;
    style v320 fill:#e3dcea,stroke:#7a4baa;
    style v347 fill:#e3dcea,stroke:#7a4baa;
    style v325 fill:#e3dcea,stroke:#7a4baa;
    style v332 fill:#e3dcea,stroke:#7a4baa;
    style v342 fill:#e3dcea,stroke:#7a4baa;
    style v348 fill:#e3dcea,stroke:#7a4baa;
    style v378 fill:#e3dcea,stroke:#7a4baa;
    style v356 fill:#e3dcea,stroke:#7a4baa;
    style v363 fill:#e3dcea,stroke:#7a4baa;
    style v373 fill:#e3dcea,stroke:#7a4baa;
    style v385 fill:#e3dcea,stroke:#7a4baa;
    style v395 fill:#e3dcea,stroke:#7a4baa;
    style v407 fill:#e3dcea,stroke:#7a4baa;
    style v417 fill:#e3dcea,stroke:#7a4baa;
    style v615 fill:#e3dcea,stroke:#7a4baa;
    style v428 fill:#e3dcea,stroke:#7a4baa;
    style v436 fill:#e3dcea,stroke:#7a4baa;
    style v444 fill:#e3dcea,stroke:#7a4baa;
    style v451 fill:#e3dcea,stroke:#7a4baa;
    style v461 fill:#e3dcea,stroke:#7a4baa;
    style v467 fill:#e3dcea,stroke:#7a4baa;
    style v590 fill:#e3dcea,stroke:#7a4baa;
    style v479 fill:#e3dcea,stroke:#7a4baa;
    style v506 fill:#e3dcea,stroke:#7a4baa;
    style v484 fill:#e3dcea,stroke:#7a4baa;
    style v491 fill:#e3dcea,stroke:#7a4baa;
    style v501 fill:#e3dcea,stroke:#7a4baa;
    style v510 fill:#e3dcea,stroke:#7a4baa;
    style v537 fill:#e3dcea,stroke:#7a4baa;
    style v515 fill:#e3dcea,stroke:#7a4baa;
    style v522 fill:#e3dcea,stroke:#7a4baa;
    style v532 fill:#e3dcea,stroke:#7a4baa;
    style v538 fill:#e3dcea,stroke:#7a4baa;
    style v568 fill:#e3dcea,stroke:#7a4baa;
    style v546 fill:#e3dcea,stroke:#7a4baa;
    style v553 fill:#e3dcea,stroke:#7a4baa;
    style v563 fill:#e3dcea,stroke:#7a4baa;
    style v575 fill:#e3dcea,stroke:#7a4baa;
    style v585 fill:#e3dcea,stroke:#7a4baa;
    style v597 fill:#e3dcea,stroke:#7a4baa;
    style v607 fill:#e3dcea,stroke:#7a4baa;
    style v617 fill:#e3dcea,stroke:#7a4baa;
    style v625 fill:#e3dcea,stroke:#7a4baa;
    style v633 fill:#e3dcea,stroke:#7a4baa;
    style v640 fill:#e3dcea,stroke:#7a4baa;
    style v650 fill:#e3dcea,stroke:#7a4baa;
    style v660 fill:#e3dcea,stroke:#7a4baa;
    style v687 fill:#e3dcea,stroke:#7a4baa;
    style v665 fill:#e3dcea,stroke:#7a4baa;
    style v672 fill:#e3dcea,stroke:#7a4baa;
    style v682 fill:#e3dcea,stroke:#7a4baa;
    style v691 fill:#e3dcea,stroke:#7a4baa;
    style v903 fill:#e3dcea,stroke:#7a4baa;
    style v696 fill:#e3dcea,stroke:#7a4baa;
    style v704 fill:#e3dcea,stroke:#7a4baa;
    style v711 fill:#e3dcea,stroke:#7a4baa;
    style v721 fill:#e3dcea,stroke:#7a4baa;
    style v727 fill:#e3dcea,stroke:#7a4baa;
    style v881 fill:#e3dcea,stroke:#7a4baa;
    style v736 fill:#e3dcea,stroke:#7a4baa;
    style v744 fill:#e3dcea,stroke:#7a4baa;
    style v751 fill:#e3dcea,stroke:#7a4baa;
    style v761 fill:#e3dcea,stroke:#7a4baa;
    style v770 fill:#e3dcea,stroke:#7a4baa;
    style v797 fill:#e3dcea,stroke:#7a4baa;
    style v775 fill:#e3dcea,stroke:#7a4baa;
    style v782 fill:#e3dcea,stroke:#7a4baa;
    style v792 fill:#e3dcea,stroke:#7a4baa;
    style v801 fill:#e3dcea,stroke:#7a4baa;
    style v828 fill:#e3dcea,stroke:#7a4baa;
    style v806 fill:#e3dcea,stroke:#7a4baa;
    style v813 fill:#e3dcea,stroke:#7a4baa;
    style v823 fill:#e3dcea,stroke:#7a4baa;
    style v832 fill:#e3dcea,stroke:#7a4baa;
    style v859 fill:#e3dcea,stroke:#7a4baa;
    style v837 fill:#e3dcea,stroke:#7a4baa;
    style v844 fill:#e3dcea,stroke:#7a4baa;
    style v854 fill:#e3dcea,stroke:#7a4baa;
    style v866 fill:#e3dcea,stroke:#7a4baa;
    style v876 fill:#e3dcea,stroke:#7a4baa;
    style v888 fill:#e3dcea,stroke:#7a4baa;
    style v898 fill:#e3dcea,stroke:#7a4baa;
    style v907 fill:#e3dcea,stroke:#7a4baa;
    style v1119 fill:#e3dcea,stroke:#7a4baa;
    style v912 fill:#e3dcea,stroke:#7a4baa;
    style v920 fill:#e3dcea,stroke:#7a4baa;
    style v927 fill:#e3dcea,stroke:#7a4baa;
    style v937 fill:#e3dcea,stroke:#7a4baa;
    style v943 fill:#e3dcea,stroke:#7a4baa;
    style v1097 fill:#e3dcea,stroke:#7a4baa;
    style v952 fill:#e3dcea,stroke:#7a4baa;
    style v960 fill:#e3dcea,stroke:#7a4baa;
    style v967 fill:#e3dcea,stroke:#7a4baa;
    style v977 fill:#e3dcea,stroke:#7a4baa;
    style v986 fill:#e3dcea,stroke:#7a4baa;
    style v1013 fill:#e3dcea,stroke:#7a4baa;
    style v991 fill:#e3dcea,stroke:#7a4baa;
    style v998 fill:#e3dcea,stroke:#7a4baa;
    style v1008 fill:#e3dcea,stroke:#7a4baa;
    style v1017 fill:#e3dcea,stroke:#7a4baa;
    style v1044 fill:#e3dcea,stroke:#7a4baa;
    style v1022 fill:#e3dcea,stroke:#7a4baa;
    style v1029 fill:#e3dcea,stroke:#7a4baa;
    style v1039 fill:#e3dcea,stroke:#7a4baa;
    style v1048 fill:#e3dcea,stroke:#7a4baa;
    style v1075 fill:#e3dcea,stroke:#7a4baa;
    style v1053 fill:#e3dcea,stroke:#7a4baa;
    style v1060 fill:#e3dcea,stroke:#7a4baa;
    style v1070 fill:#e3dcea,stroke:#7a4baa;
    style v1082 fill:#e3dcea,stroke:#7a4baa;
    style v1092 fill:#e3dcea,stroke:#7a4baa;
    style v1104 fill:#e3dcea,stroke:#7a4baa;
    style v1114 fill:#e3dcea,stroke:#7a4baa;
    style v1123 fill:#e3dcea,stroke:#7a4baa;
    style v1335 fill:#e3dcea,stroke:#7a4baa;
    style v1128 fill:#e3dcea,stroke:#7a4baa;
    style v1136 fill:#e3dcea,stroke:#7a4baa;
    style v1143 fill:#e3dcea,stroke:#7a4baa;
    style v1153 fill:#e3dcea,stroke:#7a4baa;
    style v1159 fill:#e3dcea,stroke:#7a4baa;
    style v1313 fill:#e3dcea,stroke:#7a4baa;
    style v1168 fill:#e3dcea,stroke:#7a4baa;
    style v1176 fill:#e3dcea,stroke:#7a4baa;
    style v1183 fill:#e3dcea,stroke:#7a4baa;
    style v1193 fill:#e3dcea,stroke:#7a4baa;
    style v1202 fill:#e3dcea,stroke:#7a4baa;
    style v1229 fill:#e3dcea,stroke:#7a4baa;
    style v1207 fill:#e3dcea,stroke:#7a4baa;
    style v1214 fill:#e3dcea,stroke:#7a4baa;
    style v1224 fill:#e3dcea,stroke:#7a4baa;
    style v1233 fill:#e3dcea,stroke:#7a4baa;
    style v1260 fill:#e3dcea,stroke:#7a4baa;
    style v1238 fill:#e3dcea,stroke:#7a4baa;
    style v1245 fill:#e3dcea,stroke:#7a4baa;
    style v1255 fill:#e3dcea,stroke:#7a4baa;
    style v1264 fill:#e3dcea,stroke:#7a4baa;
    style v1291 fill:#e3dcea,stroke:#7a4baa;
    style v1269 fill:#e3dcea,stroke:#7a4baa;
    style v1276 fill:#e3dcea,stroke:#7a4baa;
    style v1286 fill:#e3dcea,stroke:#7a4baa;
    style v1298 fill:#e3dcea,stroke:#7a4baa;
    style v1308 fill:#e3dcea,stroke:#7a4baa;
    style v1320 fill:#e3dcea,stroke:#7a4baa;
    style v1330 fill:#e3dcea,stroke:#7a4baa;
    style v1342 fill:#e3dcea,stroke:#7a4baa;
    style v1349 fill:#e3dcea,stroke:#7a4baa;
    style v1361 fill:#e3dcea,stroke:#7a4baa;
    style v1368 fill:#e3dcea,stroke:#7a4baa;
    style v1372 fill:#e3dcea,stroke:#7a4baa;

```

