---
title: "Process samples"
namespace: "Workflows/multiomics"
description: "A pipeline to analyse multiple multiomics samples."
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `process_samples`  
Namespace: `workflows/multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v4.1.0/src/workflows/multiomics/process_samples/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.0 -latest \
  -main-script target/nextflow/workflows/multiomics/process_samples/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"
# rna_layer: "foo"
# prot_layer: "foo"
# gdo_layer: "foo"

# Outputs
# output: "$id.$key.output.h5mu"

# Sample ID options
add_id_to_obs: true
add_id_obs_output: "sample_id"
add_id_make_observation_keys_unique: true

# RNA filtering options
# rna_min_counts: 200
# rna_max_counts: 5000000
# rna_min_genes_per_cell: 200
# rna_max_genes_per_cell: 1500000
# rna_min_cells_per_gene: 3
# rna_min_fraction_mito: 0.0
# rna_max_fraction_mito: 0.2
# rna_min_fraction_ribo: 0.0
# rna_max_fraction_ribo: 0.2
skip_scrublet_doublet_detection: false

# CITE-seq filtering options
# prot_min_counts: 3
# prot_max_counts: 5000000
# prot_min_proteins_per_cell: 200
# prot_max_proteins_per_cell: 100000000
# prot_min_cells_per_protein: 3

# GDO filtering options
# gdo_min_counts: 3
# gdo_max_counts: 5000000
# gdo_min_guides_per_cell: 200
# gdo_max_guides_per_cell: 100000000
# gdo_min_cells_per_guide: 3

# Cross-modality filtering
intersect_obs: false

# Highly variable features detection
highly_variable_features_var_output: "filter_with_hvg"
highly_variable_features_obs_batch_key: "sample_id"

# Mitochondrial & Ribosomal Gene Detection
# var_gene_names: "gene_symbol"
# var_name_mitochondrial_genes: "foo"
# obs_name_mitochondrial_fraction: "foo"
mitochondrial_gene_regex: "^[mM][tT]-"
# var_name_ribosomal_genes: "foo"
# obs_name_ribosomal_fraction: "foo"
ribosomal_gene_regex: "^[Mm]?[Rr][Pp][LlSs]"

# QC metrics calculation options
# var_qc_metrics: ["ercc,highly_variable"]
top_n_vars: [50, 100, 200, 500]

# PCA options
pca_overwrite: false

# CLR options
clr_axis: 0

# RNA Scaling options
rna_enable_scaling: false
rna_scaling_output_layer: "scaled"
rna_scaling_pca_obsm_output: "scaled_pca"
rna_scaling_pca_loadings_varm_output: "scaled_pca_loadings"
rna_scaling_pca_variance_uns_output: "scaled_pca_variance"
rna_scaling_umap_obsm_output: "scaled_umap"
# rna_scaling_max_value: 123.0
rna_scaling_zero_center: true

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v4.1.0 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/multiomics/process_samples/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name           |Description                                                                                 |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--id`         |ID of the sample.                                                                           |`string`, required, example: `"foo"`      |
|`--input`      |Path to the sample.                                                                         |`file`, required, example: `"input.h5mu"` |
|`--rna_layer`  |Input layer for the gene expression modality. If not specified, .X is used.                 |`string`                                  |
|`--prot_layer` |Input layer for the antibody capture modality. If not specified, .X is used.                |`string`                                  |
|`--gdo_layer`  |Input layer for the guide-derived oligonucleotide (GDO) data. If not specified, .X is used. |`string`                                  |


### Outputs

|Name       |Description                     |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--output` |Destination path to the output. |`file`, required, example: `"output.h5mu"` |


### Sample ID options

Options for adding the id to .obs on the MuData object. Having a sample 
id present in a requirement of several components for this pipeline.



|Name                                    |Description                                                                                         |Attributes                       |
|:----------|:--------------------------------------------------|:--------------------|
|`--add_id_to_obs`                       |Add the value passed with --id to .obs.                                                             |`boolean`, default: `TRUE`       |
|`--add_id_obs_output`                   |.Obs column to add the sample IDs to. Required and only used when  --add_id_to_obs is set to 'true' |`string`, default: `"sample_id"` |
|`--add_id_make_observation_keys_unique` |Join the id to the .obs index (.obs_names).  Only used when --add_id_to_obs is set to 'true'.       |`boolean`, default: `TRUE`       |


### RNA filtering options

|Name                                |Description                                      |Attributes                    |
|:----------|:--------------------------------------------------|:--------------------|
|`--rna_min_counts`                  |Minimum number of counts captured per cell.      |`integer`, example: `200`     |
|`--rna_max_counts`                  |Maximum number of counts captured per cell.      |`integer`, example: `5000000` |
|`--rna_min_genes_per_cell`          |Minimum of non-zero values per cell.             |`integer`, example: `200`     |
|`--rna_max_genes_per_cell`          |Maximum of non-zero values per cell.             |`integer`, example: `1500000` |
|`--rna_min_cells_per_gene`          |Minimum of non-zero values per gene.             |`integer`, example: `3`       |
|`--rna_min_fraction_mito`           |Minimum fraction of UMIs that are mitochondrial. |`double`, example: `0`        |
|`--rna_max_fraction_mito`           |Maximum fraction of UMIs that are mitochondrial. |`double`, example: `0.2`      |
|`--rna_min_fraction_ribo`           |Minimum fraction of UMIs that are mitochondrial. |`double`, example: `0`        |
|`--rna_max_fraction_ribo`           |Maximum fraction of UMIs that are mitochondrial. |`double`, example: `0.2`      |
|`--skip_scrublet_doublet_detection` |Skip the scrublet doublet detection step.        |`boolean_true`                |


### CITE-seq filtering options

|Name                           |Description                             |Attributes                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--prot_min_counts`            |Minimum number of counts per cell.      |`integer`, example: `3`         |
|`--prot_max_counts`            |Minimum number of counts per cell.      |`integer`, example: `5000000`   |
|`--prot_min_proteins_per_cell` |Minimum of non-zero values per cell.    |`integer`, example: `200`       |
|`--prot_max_proteins_per_cell` |Maximum of non-zero values per cell.    |`integer`, example: `100000000` |
|`--prot_min_cells_per_protein` |Minimum of non-zero values per protein. |`integer`, example: `3`         |


### GDO filtering options

|Name                        |Description                           |Attributes                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--gdo_min_counts`          |Minimum number of counts per cell.    |`integer`, example: `3`         |
|`--gdo_max_counts`          |Minimum number of counts per cell.    |`integer`, example: `5000000`   |
|`--gdo_min_guides_per_cell` |Minimum of non-zero values per cell.  |`integer`, example: `200`       |
|`--gdo_max_guides_per_cell` |Maximum of non-zero values per cell.  |`integer`, example: `100000000` |
|`--gdo_min_cells_per_guide` |Minimum of non-zero values per guide. |`integer`, example: `3`         |


### Cross-modality filtering

|Name              |Description                                                                                                                                                                       |Attributes     |
|:----------|:--------------------------------------------------|:--------------------|
|`--intersect_obs` |After per-modality filtering and multisample processing, remove observations that are not present in all processed modalities so that each modality shares the same set of cells. |`boolean_true` |


### Highly variable features detection

|Name                                       |Description                                                                                                                                                                                                    |Attributes                             |
|:----------|:--------------------------------------------------|:--------------------|
|`--highly_variable_features_var_output`    |In which .var slot to store a boolean array corresponding to the highly variable genes.                                                                                                                        |`string`, default: `"filter_with_hvg"` |
|`--highly_variable_features_obs_batch_key` |If specified, highly-variable genes are selected within each batch separately and merged. This simple  process avoids the selection of batch-specific genes and acts as a lightweight batch correction method. |`string`, default: `"sample_id"`       |


### Mitochondrial & Ribosomal Gene Detection

|Name                                |Description                                                                                                                                                                                                                                                                               |Attributes                                  |
|:----------|:--------------------------------------------------|:--------------------|
|`--var_gene_names`                  |.var column name to be used to detect mitochondrial/ribosomal genes instead of .var_names (default if not set). Gene names matching with the regex value from --mitochondrial_gene_regex or --ribosomal_gene_regex will be  identified as mitochondrial or ribosomal genes, respectively. |`string`, example: `"gene_symbol"`          |
|`--var_name_mitochondrial_genes`    |In which .var slot to store a boolean array corresponding the mitochondrial genes.                                                                                                                                                                                                        |`string`                                    |
|`--obs_name_mitochondrial_fraction` |When specified, write the fraction of counts originating from mitochondrial genes  (based on --mitochondrial_gene_regex) to an .obs column with the specified name. Requires --var_name_mitochondrial_genes.                                                                              |`string`                                    |
|`--mitochondrial_gene_regex`        |Regex string that identifies mitochondrial genes from --var_gene_names. By default will detect human and mouse mitochondrial genes from a gene symbol.                                                                                                                                    |`string`, default: `"^[mM][tT]-"`           |
|`--var_name_ribosomal_genes`        |In which .var slot to store a boolean array corresponding the ribosomal genes.                                                                                                                                                                                                            |`string`                                    |
|`--obs_name_ribosomal_fraction`     |When specified, write the fraction of counts originating from ribosomal genes  (based on --ribosomal_gene_regex) to an .obs column with the specified name. Requires --var_name_ribosomal_genes.                                                                                          |`string`                                    |
|`--ribosomal_gene_regex`            |Regex string that identifies ribosomal genes from --var_gene_names. By default will detect human and mouse ribosomal genes from a gene symbol.                                                                                                                                            |`string`, default: `"^[Mm]?[Rr][Pp][LlSs]"` |


### QC metrics calculation options

|Name               |Description                                                                                                                                                                                                                                                                                                                                            |Attributes                                                               |
|:----------|:--------------------------------------------------|:--------------------|
|`--var_qc_metrics` |Keys to select a boolean (containing only True or False) column from .var. For each cell, calculate the proportion of total values for genes which are labeled 'True',  compared to the total sum of the values for all genes. Defaults to the combined values specified for --var_name_mitochondrial_genes and --highly_variable_features_var_output. |List of `string`, example: `"ercc,highly_variable"`, multiple_sep: `","` |
|`--top_n_vars`     |Number of top vars to be used to calculate cumulative proportions. If not specified, proportions are not calculated. `--top_n_vars 20,50` finds cumulative proportion to the 20th and 50th most expressed vars.                                                                                                                                        |List of `integer`, default: `50, 100, 200, 500`, multiple_sep: `","`     |


### PCA options

|Name              |Description                             |Attributes     |
|:----------|:--------------------------------------------------|:--------------------|
|`--pca_overwrite` |Allow overwriting slots for PCA output. |`boolean_true` |


### CLR options

|Name         |Description                                |Attributes              |
|:----------|:--------------------------------------------------|:--------------------|
|`--clr_axis` |Axis to perform the CLR transformation on. |`integer`, default: `0` |


### RNA Scaling options

Options for enabling scaling of the log-normalized data to unit variance and zero mean.
The scaled data will be output a different layer and representation with reduced dimensions
will be created and stored in addition to the non-scaled data.



|Name                                     |Description                                                                                                                                                  |Attributes                                 |
|:----------|:--------------------------------------------------|:--------------------|
|`--rna_enable_scaling`                   |Enable scaling for the RNA modality.                                                                                                                         |`boolean_true`                             |
|`--rna_scaling_output_layer`             |Output layer where the scaled log-normalized data will be stored.                                                                                            |`string`, default: `"scaled"`              |
|`--rna_scaling_pca_obsm_output`          |Name of the .obsm key where the PCA representation of the log-normalized and scaled data is stored.                                                          |`string`, default: `"scaled_pca"`          |
|`--rna_scaling_pca_loadings_varm_output` |Name of the .varm key where the PCA loadings of the log-normalized and scaled data is stored.                                                                |`string`, default: `"scaled_pca_loadings"` |
|`--rna_scaling_pca_variance_uns_output`  |Name of the .uns key where the variance and variance ratio will be stored as a map. The map will contain two keys: variance and variance_ratio respectively. |`string`, default: `"scaled_pca_variance"` |
|`--rna_scaling_umap_obsm_output`         |Name of the .obsm key where the UMAP representation of the log-normalized and scaled data is stored.                                                         |`string`, default: `"scaled_umap"`         |
|`--rna_scaling_max_value`                |Clip (truncate) data to this value after scaling. If not specified, do not clip.                                                                             |`double`                                   |
|`--rna_scaling_zero_center`              |If set, omit zero-centering variables, which allows to handle sparse input efficiently."                                                                     |`boolean_false`                            |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author, maintainer)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v11(filter)
    v24(filter)
    v36(cross)
    v46(cross)
    v118(flatMap)
    v632(mix)
    v640(cross)
    v650(cross)
    v661(filter)
    v669(concatenate_h5mu)
    v676(cross)
    v686(cross)
    v695(filter)
    v2050(concat)
    v704(filter)
    v715(filter)
    v727(cross)
    v737(cross)
    v747(concat)
    v754(cross)
    v764(cross)
    v770(flatMap)
    v778(filter)
    v786(filter)
    v793(filter)
    v808(cross)
    v818(cross)
    v824(filter)
    v839(cross)
    v849(cross)
    v855(filter)
    v885(concat)
    v870(cross)
    v880(cross)
    v892(cross)
    v902(cross)
    v911(branch)
    v938(concat)
    v923(cross)
    v933(cross)
    v939(filter)
    v954(cross)
    v964(cross)
    v970(filter)
    v1093(concat)
    v982(branch)
    v1009(concat)
    v994(cross)
    v1004(cross)
    v1013(branch)
    v1040(concat)
    v1025(cross)
    v1035(cross)
    v1041(filter)
    v1071(concat)
    v1056(cross)
    v1066(cross)
    v1078(cross)
    v1088(cross)
    v1100(cross)
    v1110(cross)
    v1308(mix)
    v1121(filter)
    v1129(filter)
    v1144(cross)
    v1154(cross)
    v1160(filter)
    v1283(concat)
    v1172(branch)
    v1199(concat)
    v1184(cross)
    v1194(cross)
    v1203(branch)
    v1230(concat)
    v1215(cross)
    v1225(cross)
    v1231(filter)
    v1261(concat)
    v1246(cross)
    v1256(cross)
    v1268(cross)
    v1278(cross)
    v1290(cross)
    v1300(cross)
    v1310(mix)
    v1318(filter)
    v1333(cross)
    v1343(cross)
    v1353(branch)
    v1380(concat)
    v1365(cross)
    v1375(cross)
    v1384(branch)
    v1596(concat)
    v1389(filter)
    v1404(cross)
    v1414(cross)
    v1420(filter)
    v1574(concat)
    v1429(filter)
    v1444(cross)
    v1454(cross)
    v1463(branch)
    v1490(concat)
    v1475(cross)
    v1485(cross)
    v1494(branch)
    v1521(concat)
    v1506(cross)
    v1516(cross)
    v1525(branch)
    v1552(concat)
    v1537(cross)
    v1547(cross)
    v1559(cross)
    v1569(cross)
    v1581(cross)
    v1591(cross)
    v1600(branch)
    v1812(concat)
    v1605(filter)
    v1620(cross)
    v1630(cross)
    v1636(filter)
    v1790(concat)
    v1645(filter)
    v1660(cross)
    v1670(cross)
    v1679(branch)
    v1706(concat)
    v1691(cross)
    v1701(cross)
    v1710(branch)
    v1737(concat)
    v1722(cross)
    v1732(cross)
    v1741(branch)
    v1768(concat)
    v1753(cross)
    v1763(cross)
    v1775(cross)
    v1785(cross)
    v1797(cross)
    v1807(cross)
    v1816(branch)
    v2028(concat)
    v1821(filter)
    v1836(cross)
    v1846(cross)
    v1852(filter)
    v2006(concat)
    v1861(filter)
    v1876(cross)
    v1886(cross)
    v1895(branch)
    v1922(concat)
    v1907(cross)
    v1917(cross)
    v1926(branch)
    v1953(concat)
    v1938(cross)
    v1948(cross)
    v1957(branch)
    v1984(concat)
    v1969(cross)
    v1979(cross)
    v1991(cross)
    v2001(cross)
    v2013(cross)
    v2023(cross)
    v2035(cross)
    v2045(cross)
    v2057(cross)
    v2064(cross)
    v2076(cross)
    v2083(cross)
    v2087(Output)
    subgraph group_process_singlesample_base [process_singlesample_base]
        v29(add_id)
        v52(filter)
        v63(filter)
        v68(split_modalities_component)
        v75(cross)
        v85(cross)
        v95(concat)
        v102(cross)
        v112(cross)
        v124(filter)
        v133(filter)
        v145(branch)
        v172(concat)
        v157(cross)
        v167(cross)
        v176(branch)
        v203(concat)
        v188(cross)
        v198(cross)
        v204(filter)
        v234(concat)
        v219(cross)
        v229(cross)
        v241(cross)
        v251(cross)
        v260(branch)
        v287(concat)
        v272(cross)
        v282(cross)
        v291(branch)
        v318(concat)
        v303(cross)
        v313(cross)
        v319(filter)
        v334(cross)
        v344(cross)
        v350(filter)
        v365(cross)
        v375(cross)
        v384(branch)
        v411(concat)
        v396(cross)
        v406(cross)
        v418(cross)
        v428(cross)
        v630(mix)
        v439(filter)
        v447(filter)
        v462(cross)
        v472(cross)
        v478(filter)
        v508(concat)
        v493(cross)
        v503(cross)
        v515(cross)
        v525(cross)
        v536(filter)
        v544(filter)
        v559(cross)
        v569(cross)
        v575(filter)
        v605(concat)
        v590(cross)
        v600(cross)
        v612(cross)
        v622(cross)
        subgraph group_rna_singlesample [rna_singlesample]
            v150(grep_mitochondrial_genes)
            v181(grep_ribosomal_genes)
            v212(calculate_qc_metrics)
            v265(delimit_fraction)
            v296(delimit_fraction)
            v327(rna_filter_with_counts)
            v358(rna_do_filter)
            v389(filter_with_scrublet)
        end
        subgraph group_prot_singlesample [prot_singlesample]
            v455(prot_filter_with_counts)
            v486(prot_do_filter)
        end
        subgraph group_gdo_singlesample [gdo_singlesample]
            v552(gdo_filter_with_counts)
            v583(gdo_do_filter)
        end
    end
    subgraph group_process_batches [process_batches]
        v720(split_modalities_component)
        v1326(merge)
        v1358(intersect_obs)
        v1397(pca)
        v1613(pca)
        v1829(pca)
        subgraph group_rna_multisample [rna_multisample]
            v801(normalize_total)
            v832(log1p)
            v863(delete_layer)
            v916(scale)
            v947(highly_variable_features_scanpy)
            v987(grep_mitochondrial_genes)
            v1018(grep_ribosomal_genes)
            v1049(calculate_qc_metrics)
        end
        subgraph group_prot_multisample [prot_multisample]
            v1137(clr)
            v1177(grep_mitochondrial_genes)
            v1208(grep_ribosomal_genes)
            v1239(calculate_qc_metrics)
        end
        subgraph group_neighbors_leiden_umap [neighbors_leiden_umap]
            v1437(find_neighbors)
            v1468(leiden)
            v1499(move_obsm_to_obs)
            v1530(umap)
            v1653(find_neighbors)
            v1684(leiden)
            v1715(move_obsm_to_obs)
            v1746(umap)
            v1869(find_neighbors)
            v1900(leiden)
            v1931(move_obsm_to_obs)
            v1962(umap)
        end
    end
    v145-->v172
    v176-->v203
    v203-->v204
    v260-->v287
    v291-->v318
    v318-->v319
    v384-->v411
    v630-->v632
    v911-->v938
    v938-->v939
    v982-->v1009
    v1013-->v1040
    v1040-->v1041
    v1172-->v1199
    v1203-->v1230
    v1230-->v1231
    v1308-->v1310
    v1353-->v1380
    v1384-->v1596
    v1463-->v1490
    v1494-->v1521
    v1525-->v1552
    v1600-->v1812
    v1679-->v1706
    v1710-->v1737
    v1741-->v1768
    v1816-->v2028
    v1895-->v1922
    v1926-->v1953
    v1957-->v1984
    v0-->v2
    v2-->v11
    v24-->v29
    v29-->v36
    v24-->v36
    v24-->v46
    v63-->v68
    v68-->v75
    v63-->v75
    v63-->v85
    v95-->v102
    v52-->v102
    v52-->v112
    v124-->v133
    v145-->v150
    v150-->v157
    v145-->v157
    v145-->v167
    v167-->v172
    v176-->v181
    v181-->v188
    v176-->v188
    v176-->v198
    v198-->v203
    v204-->v212
    v212-->v219
    v204-->v219
    v204-->v229
    v229-->v234
    v234-->v241
    v133-->v241
    v133-->v251
    v260-->v265
    v265-->v272
    v260-->v272
    v260-->v282
    v282-->v287
    v291-->v296
    v296-->v303
    v291-->v303
    v291-->v313
    v313-->v318
    v319-->v327
    v327-->v334
    v319-->v334
    v319-->v344
    v350-->v358
    v358-->v365
    v350-->v365
    v350-->v375
    v384-->v389
    v389-->v396
    v384-->v396
    v384-->v406
    v406-->v411
    v411-->v418
    v124-->v418
    v124-->v428
    v439-->v447
    v447-->v455
    v455-->v462
    v447-->v462
    v447-->v472
    v478-->v486
    v486-->v493
    v478-->v493
    v478-->v503
    v503-->v508
    v508-->v515
    v439-->v515
    v439-->v525
    v536-->v544
    v544-->v552
    v552-->v559
    v544-->v559
    v544-->v569
    v575-->v583
    v583-->v590
    v575-->v590
    v575-->v600
    v600-->v605
    v605-->v612
    v536-->v612
    v536-->v622
    v632-->v640
    v11-->v640
    v11-->v650
    v661-->v669
    v669-->v676
    v661-->v676
    v661-->v686
    v715-->v720
    v720-->v727
    v715-->v727
    v715-->v737
    v747-->v754
    v704-->v754
    v704-->v764
    v778-->v786
    v786-->v793
    v793-->v801
    v801-->v808
    v793-->v808
    v793-->v818
    v824-->v832
    v832-->v839
    v824-->v839
    v824-->v849
    v855-->v863
    v863-->v870
    v855-->v870
    v855-->v880
    v880-->v885
    v885-->v892
    v786-->v892
    v786-->v902
    v911-->v916
    v916-->v923
    v911-->v923
    v911-->v933
    v933-->v938
    v939-->v947
    v947-->v954
    v939-->v954
    v939-->v964
    v982-->v987
    v987-->v994
    v982-->v994
    v982-->v1004
    v1004-->v1009
    v1013-->v1018
    v1018-->v1025
    v1013-->v1025
    v1013-->v1035
    v1035-->v1040
    v1041-->v1049
    v1049-->v1056
    v1041-->v1056
    v1041-->v1066
    v1066-->v1071
    v1071-->v1078
    v970-->v1078
    v970-->v1088
    v1088-->v1093
    v1093-->v1100
    v778-->v1100
    v778-->v1110
    v1121-->v1129
    v1129-->v1137
    v1137-->v1144
    v1129-->v1144
    v1129-->v1154
    v1172-->v1177
    v1177-->v1184
    v1172-->v1184
    v1172-->v1194
    v1194-->v1199
    v1203-->v1208
    v1208-->v1215
    v1203-->v1215
    v1203-->v1225
    v1225-->v1230
    v1231-->v1239
    v1239-->v1246
    v1231-->v1246
    v1231-->v1256
    v1256-->v1261
    v1261-->v1268
    v1160-->v1268
    v1160-->v1278
    v1278-->v1283
    v1283-->v1290
    v1121-->v1290
    v1121-->v1300
    v1318-->v1326
    v1326-->v1333
    v1318-->v1333
    v1318-->v1343
    v1353-->v1358
    v1358-->v1365
    v1353-->v1365
    v1353-->v1375
    v1375-->v1380
    v1384-->v1389
    v1389-->v1397
    v1397-->v1404
    v1389-->v1404
    v1389-->v1414
    v1420-->v1429
    v1429-->v1437
    v1437-->v1444
    v1429-->v1444
    v1429-->v1454
    v1463-->v1468
    v1468-->v1475
    v1463-->v1475
    v1463-->v1485
    v1485-->v1490
    v1494-->v1499
    v1499-->v1506
    v1494-->v1506
    v1494-->v1516
    v1516-->v1521
    v1525-->v1530
    v1530-->v1537
    v1525-->v1537
    v1525-->v1547
    v1547-->v1552
    v1552-->v1559
    v1420-->v1559
    v1420-->v1569
    v1569-->v1574
    v1574-->v1581
    v1384-->v1581
    v1384-->v1591
    v1591-->v1596
    v1600-->v1605
    v1605-->v1613
    v1613-->v1620
    v1605-->v1620
    v1605-->v1630
    v1636-->v1645
    v1645-->v1653
    v1653-->v1660
    v1645-->v1660
    v1645-->v1670
    v1679-->v1684
    v1684-->v1691
    v1679-->v1691
    v1679-->v1701
    v1701-->v1706
    v1710-->v1715
    v1715-->v1722
    v1710-->v1722
    v1710-->v1732
    v1732-->v1737
    v1741-->v1746
    v1746-->v1753
    v1741-->v1753
    v1741-->v1763
    v1763-->v1768
    v1768-->v1775
    v1636-->v1775
    v1636-->v1785
    v1785-->v1790
    v1790-->v1797
    v1600-->v1797
    v1600-->v1807
    v1807-->v1812
    v1816-->v1821
    v1821-->v1829
    v1829-->v1836
    v1821-->v1836
    v1821-->v1846
    v1852-->v1861
    v1861-->v1869
    v1869-->v1876
    v1861-->v1876
    v1861-->v1886
    v1895-->v1900
    v1900-->v1907
    v1895-->v1907
    v1895-->v1917
    v1917-->v1922
    v1926-->v1931
    v1931-->v1938
    v1926-->v1938
    v1926-->v1948
    v1948-->v1953
    v1957-->v1962
    v1962-->v1969
    v1957-->v1969
    v1957-->v1979
    v1979-->v1984
    v1984-->v1991
    v1852-->v1991
    v1852-->v2001
    v2001-->v2006
    v2006-->v2013
    v1816-->v2013
    v1816-->v2023
    v2023-->v2028
    v2028-->v2035
    v695-->v2035
    v695-->v2045
    v2045-->v2050
    v2050-->v2057
    v2-->v2057
    v2057-->v2064
    v2-->v2064
    v2-->v2076
    v2076-->v2083
    v2-->v2083
    v2083-->v2087
    v11-->v24
    v46-->v52
    v29-->v46
    v112-->v118
    v52-->v63
    v85-->v95
    v68-->v85
    v95-->v112
    v118-->v124
    v428-->v630
    v133-->v145
    v150-->v167
    v172-->v176
    v181-->v198
    v212-->v229
    v234-->v251
    v251-->v260
    v265-->v282
    v287-->v291
    v296-->v313
    v344-->v350
    v327-->v344
    v358-->v375
    v375-->v384
    v389-->v406
    v411-->v428
    v118-->v439
    v525-->v630
    v472-->v478
    v455-->v472
    v486-->v503
    v508-->v525
    v118-->v536
    v622-->v630
    v569-->v575
    v552-->v569
    v583-->v600
    v605-->v622
    v118-->v632
    v632-->v650
    v650-->v661
    v669-->v686
    v686-->v695
    v695-->v704
    v764-->v770
    v704-->v715
    v737-->v747
    v720-->v737
    v747-->v764
    v770-->v778
    v1110-->v1308
    v818-->v824
    v801-->v818
    v849-->v855
    v832-->v849
    v863-->v880
    v885-->v902
    v902-->v911
    v916-->v933
    v964-->v970
    v947-->v964
    v970-->v982
    v987-->v1004
    v1009-->v1013
    v1018-->v1035
    v1049-->v1066
    v1071-->v1088
    v1093-->v1110
    v770-->v1121
    v1300-->v1308
    v1154-->v1160
    v1137-->v1154
    v1160-->v1172
    v1177-->v1194
    v1199-->v1203
    v1208-->v1225
    v1239-->v1256
    v1261-->v1278
    v1283-->v1300
    v770-->v1310
    v1310-->v1318
    v1326-->v1343
    v1343-->v1353
    v1358-->v1375
    v1380-->v1384
    v1414-->v1420
    v1397-->v1414
    v1437-->v1454
    v1454-->v1463
    v1468-->v1485
    v1490-->v1494
    v1499-->v1516
    v1521-->v1525
    v1530-->v1547
    v1552-->v1569
    v1574-->v1591
    v1596-->v1600
    v1630-->v1636
    v1613-->v1630
    v1653-->v1670
    v1670-->v1679
    v1684-->v1701
    v1706-->v1710
    v1715-->v1732
    v1737-->v1741
    v1746-->v1763
    v1768-->v1785
    v1790-->v1807
    v1812-->v1816
    v1846-->v1852
    v1829-->v1846
    v1869-->v1886
    v1886-->v1895
    v1900-->v1917
    v1922-->v1926
    v1931-->v1948
    v1953-->v1957
    v1962-->v1979
    v1984-->v2001
    v2006-->v2023
    v2028-->v2045
    v2050-->v2076
    style group_process_singlesample_base fill:#F0F0F0,stroke:#969696;
    style group_rna_singlesample fill:#D9D9D9,stroke:#737373;
    style group_prot_singlesample fill:#D9D9D9,stroke:#737373;
    style group_gdo_singlesample fill:#D9D9D9,stroke:#737373;
    style group_process_batches fill:#F0F0F0,stroke:#969696;
    style group_rna_multisample fill:#D9D9D9,stroke:#737373;
    style group_prot_multisample fill:#D9D9D9,stroke:#737373;
    style group_neighbors_leiden_umap fill:#D9D9D9,stroke:#737373;
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v11 fill:#e3dcea,stroke:#7a4baa;
    style v24 fill:#e3dcea,stroke:#7a4baa;
    style v29 fill:#e3dcea,stroke:#7a4baa;
    style v36 fill:#e3dcea,stroke:#7a4baa;
    style v46 fill:#e3dcea,stroke:#7a4baa;
    style v52 fill:#e3dcea,stroke:#7a4baa;
    style v63 fill:#e3dcea,stroke:#7a4baa;
    style v68 fill:#e3dcea,stroke:#7a4baa;
    style v75 fill:#e3dcea,stroke:#7a4baa;
    style v85 fill:#e3dcea,stroke:#7a4baa;
    style v95 fill:#e3dcea,stroke:#7a4baa;
    style v102 fill:#e3dcea,stroke:#7a4baa;
    style v112 fill:#e3dcea,stroke:#7a4baa;
    style v118 fill:#e3dcea,stroke:#7a4baa;
    style v124 fill:#e3dcea,stroke:#7a4baa;
    style v133 fill:#e3dcea,stroke:#7a4baa;
    style v145 fill:#e3dcea,stroke:#7a4baa;
    style v172 fill:#e3dcea,stroke:#7a4baa;
    style v150 fill:#e3dcea,stroke:#7a4baa;
    style v157 fill:#e3dcea,stroke:#7a4baa;
    style v167 fill:#e3dcea,stroke:#7a4baa;
    style v176 fill:#e3dcea,stroke:#7a4baa;
    style v203 fill:#e3dcea,stroke:#7a4baa;
    style v181 fill:#e3dcea,stroke:#7a4baa;
    style v188 fill:#e3dcea,stroke:#7a4baa;
    style v198 fill:#e3dcea,stroke:#7a4baa;
    style v204 fill:#e3dcea,stroke:#7a4baa;
    style v234 fill:#e3dcea,stroke:#7a4baa;
    style v212 fill:#e3dcea,stroke:#7a4baa;
    style v219 fill:#e3dcea,stroke:#7a4baa;
    style v229 fill:#e3dcea,stroke:#7a4baa;
    style v241 fill:#e3dcea,stroke:#7a4baa;
    style v251 fill:#e3dcea,stroke:#7a4baa;
    style v260 fill:#e3dcea,stroke:#7a4baa;
    style v287 fill:#e3dcea,stroke:#7a4baa;
    style v265 fill:#e3dcea,stroke:#7a4baa;
    style v272 fill:#e3dcea,stroke:#7a4baa;
    style v282 fill:#e3dcea,stroke:#7a4baa;
    style v291 fill:#e3dcea,stroke:#7a4baa;
    style v318 fill:#e3dcea,stroke:#7a4baa;
    style v296 fill:#e3dcea,stroke:#7a4baa;
    style v303 fill:#e3dcea,stroke:#7a4baa;
    style v313 fill:#e3dcea,stroke:#7a4baa;
    style v319 fill:#e3dcea,stroke:#7a4baa;
    style v327 fill:#e3dcea,stroke:#7a4baa;
    style v334 fill:#e3dcea,stroke:#7a4baa;
    style v344 fill:#e3dcea,stroke:#7a4baa;
    style v350 fill:#e3dcea,stroke:#7a4baa;
    style v358 fill:#e3dcea,stroke:#7a4baa;
    style v365 fill:#e3dcea,stroke:#7a4baa;
    style v375 fill:#e3dcea,stroke:#7a4baa;
    style v384 fill:#e3dcea,stroke:#7a4baa;
    style v411 fill:#e3dcea,stroke:#7a4baa;
    style v389 fill:#e3dcea,stroke:#7a4baa;
    style v396 fill:#e3dcea,stroke:#7a4baa;
    style v406 fill:#e3dcea,stroke:#7a4baa;
    style v418 fill:#e3dcea,stroke:#7a4baa;
    style v428 fill:#e3dcea,stroke:#7a4baa;
    style v630 fill:#e3dcea,stroke:#7a4baa;
    style v439 fill:#e3dcea,stroke:#7a4baa;
    style v447 fill:#e3dcea,stroke:#7a4baa;
    style v455 fill:#e3dcea,stroke:#7a4baa;
    style v462 fill:#e3dcea,stroke:#7a4baa;
    style v472 fill:#e3dcea,stroke:#7a4baa;
    style v478 fill:#e3dcea,stroke:#7a4baa;
    style v508 fill:#e3dcea,stroke:#7a4baa;
    style v486 fill:#e3dcea,stroke:#7a4baa;
    style v493 fill:#e3dcea,stroke:#7a4baa;
    style v503 fill:#e3dcea,stroke:#7a4baa;
    style v515 fill:#e3dcea,stroke:#7a4baa;
    style v525 fill:#e3dcea,stroke:#7a4baa;
    style v536 fill:#e3dcea,stroke:#7a4baa;
    style v544 fill:#e3dcea,stroke:#7a4baa;
    style v552 fill:#e3dcea,stroke:#7a4baa;
    style v559 fill:#e3dcea,stroke:#7a4baa;
    style v569 fill:#e3dcea,stroke:#7a4baa;
    style v575 fill:#e3dcea,stroke:#7a4baa;
    style v605 fill:#e3dcea,stroke:#7a4baa;
    style v583 fill:#e3dcea,stroke:#7a4baa;
    style v590 fill:#e3dcea,stroke:#7a4baa;
    style v600 fill:#e3dcea,stroke:#7a4baa;
    style v612 fill:#e3dcea,stroke:#7a4baa;
    style v622 fill:#e3dcea,stroke:#7a4baa;
    style v632 fill:#e3dcea,stroke:#7a4baa;
    style v640 fill:#e3dcea,stroke:#7a4baa;
    style v650 fill:#e3dcea,stroke:#7a4baa;
    style v661 fill:#e3dcea,stroke:#7a4baa;
    style v669 fill:#e3dcea,stroke:#7a4baa;
    style v676 fill:#e3dcea,stroke:#7a4baa;
    style v686 fill:#e3dcea,stroke:#7a4baa;
    style v695 fill:#e3dcea,stroke:#7a4baa;
    style v2050 fill:#e3dcea,stroke:#7a4baa;
    style v704 fill:#e3dcea,stroke:#7a4baa;
    style v715 fill:#e3dcea,stroke:#7a4baa;
    style v720 fill:#e3dcea,stroke:#7a4baa;
    style v727 fill:#e3dcea,stroke:#7a4baa;
    style v737 fill:#e3dcea,stroke:#7a4baa;
    style v747 fill:#e3dcea,stroke:#7a4baa;
    style v754 fill:#e3dcea,stroke:#7a4baa;
    style v764 fill:#e3dcea,stroke:#7a4baa;
    style v770 fill:#e3dcea,stroke:#7a4baa;
    style v778 fill:#e3dcea,stroke:#7a4baa;
    style v786 fill:#e3dcea,stroke:#7a4baa;
    style v793 fill:#e3dcea,stroke:#7a4baa;
    style v801 fill:#e3dcea,stroke:#7a4baa;
    style v808 fill:#e3dcea,stroke:#7a4baa;
    style v818 fill:#e3dcea,stroke:#7a4baa;
    style v824 fill:#e3dcea,stroke:#7a4baa;
    style v832 fill:#e3dcea,stroke:#7a4baa;
    style v839 fill:#e3dcea,stroke:#7a4baa;
    style v849 fill:#e3dcea,stroke:#7a4baa;
    style v855 fill:#e3dcea,stroke:#7a4baa;
    style v885 fill:#e3dcea,stroke:#7a4baa;
    style v863 fill:#e3dcea,stroke:#7a4baa;
    style v870 fill:#e3dcea,stroke:#7a4baa;
    style v880 fill:#e3dcea,stroke:#7a4baa;
    style v892 fill:#e3dcea,stroke:#7a4baa;
    style v902 fill:#e3dcea,stroke:#7a4baa;
    style v911 fill:#e3dcea,stroke:#7a4baa;
    style v938 fill:#e3dcea,stroke:#7a4baa;
    style v916 fill:#e3dcea,stroke:#7a4baa;
    style v923 fill:#e3dcea,stroke:#7a4baa;
    style v933 fill:#e3dcea,stroke:#7a4baa;
    style v939 fill:#e3dcea,stroke:#7a4baa;
    style v947 fill:#e3dcea,stroke:#7a4baa;
    style v954 fill:#e3dcea,stroke:#7a4baa;
    style v964 fill:#e3dcea,stroke:#7a4baa;
    style v970 fill:#e3dcea,stroke:#7a4baa;
    style v1093 fill:#e3dcea,stroke:#7a4baa;
    style v982 fill:#e3dcea,stroke:#7a4baa;
    style v1009 fill:#e3dcea,stroke:#7a4baa;
    style v987 fill:#e3dcea,stroke:#7a4baa;
    style v994 fill:#e3dcea,stroke:#7a4baa;
    style v1004 fill:#e3dcea,stroke:#7a4baa;
    style v1013 fill:#e3dcea,stroke:#7a4baa;
    style v1040 fill:#e3dcea,stroke:#7a4baa;
    style v1018 fill:#e3dcea,stroke:#7a4baa;
    style v1025 fill:#e3dcea,stroke:#7a4baa;
    style v1035 fill:#e3dcea,stroke:#7a4baa;
    style v1041 fill:#e3dcea,stroke:#7a4baa;
    style v1071 fill:#e3dcea,stroke:#7a4baa;
    style v1049 fill:#e3dcea,stroke:#7a4baa;
    style v1056 fill:#e3dcea,stroke:#7a4baa;
    style v1066 fill:#e3dcea,stroke:#7a4baa;
    style v1078 fill:#e3dcea,stroke:#7a4baa;
    style v1088 fill:#e3dcea,stroke:#7a4baa;
    style v1100 fill:#e3dcea,stroke:#7a4baa;
    style v1110 fill:#e3dcea,stroke:#7a4baa;
    style v1308 fill:#e3dcea,stroke:#7a4baa;
    style v1121 fill:#e3dcea,stroke:#7a4baa;
    style v1129 fill:#e3dcea,stroke:#7a4baa;
    style v1137 fill:#e3dcea,stroke:#7a4baa;
    style v1144 fill:#e3dcea,stroke:#7a4baa;
    style v1154 fill:#e3dcea,stroke:#7a4baa;
    style v1160 fill:#e3dcea,stroke:#7a4baa;
    style v1283 fill:#e3dcea,stroke:#7a4baa;
    style v1172 fill:#e3dcea,stroke:#7a4baa;
    style v1199 fill:#e3dcea,stroke:#7a4baa;
    style v1177 fill:#e3dcea,stroke:#7a4baa;
    style v1184 fill:#e3dcea,stroke:#7a4baa;
    style v1194 fill:#e3dcea,stroke:#7a4baa;
    style v1203 fill:#e3dcea,stroke:#7a4baa;
    style v1230 fill:#e3dcea,stroke:#7a4baa;
    style v1208 fill:#e3dcea,stroke:#7a4baa;
    style v1215 fill:#e3dcea,stroke:#7a4baa;
    style v1225 fill:#e3dcea,stroke:#7a4baa;
    style v1231 fill:#e3dcea,stroke:#7a4baa;
    style v1261 fill:#e3dcea,stroke:#7a4baa;
    style v1239 fill:#e3dcea,stroke:#7a4baa;
    style v1246 fill:#e3dcea,stroke:#7a4baa;
    style v1256 fill:#e3dcea,stroke:#7a4baa;
    style v1268 fill:#e3dcea,stroke:#7a4baa;
    style v1278 fill:#e3dcea,stroke:#7a4baa;
    style v1290 fill:#e3dcea,stroke:#7a4baa;
    style v1300 fill:#e3dcea,stroke:#7a4baa;
    style v1310 fill:#e3dcea,stroke:#7a4baa;
    style v1318 fill:#e3dcea,stroke:#7a4baa;
    style v1326 fill:#e3dcea,stroke:#7a4baa;
    style v1333 fill:#e3dcea,stroke:#7a4baa;
    style v1343 fill:#e3dcea,stroke:#7a4baa;
    style v1353 fill:#e3dcea,stroke:#7a4baa;
    style v1380 fill:#e3dcea,stroke:#7a4baa;
    style v1358 fill:#e3dcea,stroke:#7a4baa;
    style v1365 fill:#e3dcea,stroke:#7a4baa;
    style v1375 fill:#e3dcea,stroke:#7a4baa;
    style v1384 fill:#e3dcea,stroke:#7a4baa;
    style v1596 fill:#e3dcea,stroke:#7a4baa;
    style v1389 fill:#e3dcea,stroke:#7a4baa;
    style v1397 fill:#e3dcea,stroke:#7a4baa;
    style v1404 fill:#e3dcea,stroke:#7a4baa;
    style v1414 fill:#e3dcea,stroke:#7a4baa;
    style v1420 fill:#e3dcea,stroke:#7a4baa;
    style v1574 fill:#e3dcea,stroke:#7a4baa;
    style v1429 fill:#e3dcea,stroke:#7a4baa;
    style v1437 fill:#e3dcea,stroke:#7a4baa;
    style v1444 fill:#e3dcea,stroke:#7a4baa;
    style v1454 fill:#e3dcea,stroke:#7a4baa;
    style v1463 fill:#e3dcea,stroke:#7a4baa;
    style v1490 fill:#e3dcea,stroke:#7a4baa;
    style v1468 fill:#e3dcea,stroke:#7a4baa;
    style v1475 fill:#e3dcea,stroke:#7a4baa;
    style v1485 fill:#e3dcea,stroke:#7a4baa;
    style v1494 fill:#e3dcea,stroke:#7a4baa;
    style v1521 fill:#e3dcea,stroke:#7a4baa;
    style v1499 fill:#e3dcea,stroke:#7a4baa;
    style v1506 fill:#e3dcea,stroke:#7a4baa;
    style v1516 fill:#e3dcea,stroke:#7a4baa;
    style v1525 fill:#e3dcea,stroke:#7a4baa;
    style v1552 fill:#e3dcea,stroke:#7a4baa;
    style v1530 fill:#e3dcea,stroke:#7a4baa;
    style v1537 fill:#e3dcea,stroke:#7a4baa;
    style v1547 fill:#e3dcea,stroke:#7a4baa;
    style v1559 fill:#e3dcea,stroke:#7a4baa;
    style v1569 fill:#e3dcea,stroke:#7a4baa;
    style v1581 fill:#e3dcea,stroke:#7a4baa;
    style v1591 fill:#e3dcea,stroke:#7a4baa;
    style v1600 fill:#e3dcea,stroke:#7a4baa;
    style v1812 fill:#e3dcea,stroke:#7a4baa;
    style v1605 fill:#e3dcea,stroke:#7a4baa;
    style v1613 fill:#e3dcea,stroke:#7a4baa;
    style v1620 fill:#e3dcea,stroke:#7a4baa;
    style v1630 fill:#e3dcea,stroke:#7a4baa;
    style v1636 fill:#e3dcea,stroke:#7a4baa;
    style v1790 fill:#e3dcea,stroke:#7a4baa;
    style v1645 fill:#e3dcea,stroke:#7a4baa;
    style v1653 fill:#e3dcea,stroke:#7a4baa;
    style v1660 fill:#e3dcea,stroke:#7a4baa;
    style v1670 fill:#e3dcea,stroke:#7a4baa;
    style v1679 fill:#e3dcea,stroke:#7a4baa;
    style v1706 fill:#e3dcea,stroke:#7a4baa;
    style v1684 fill:#e3dcea,stroke:#7a4baa;
    style v1691 fill:#e3dcea,stroke:#7a4baa;
    style v1701 fill:#e3dcea,stroke:#7a4baa;
    style v1710 fill:#e3dcea,stroke:#7a4baa;
    style v1737 fill:#e3dcea,stroke:#7a4baa;
    style v1715 fill:#e3dcea,stroke:#7a4baa;
    style v1722 fill:#e3dcea,stroke:#7a4baa;
    style v1732 fill:#e3dcea,stroke:#7a4baa;
    style v1741 fill:#e3dcea,stroke:#7a4baa;
    style v1768 fill:#e3dcea,stroke:#7a4baa;
    style v1746 fill:#e3dcea,stroke:#7a4baa;
    style v1753 fill:#e3dcea,stroke:#7a4baa;
    style v1763 fill:#e3dcea,stroke:#7a4baa;
    style v1775 fill:#e3dcea,stroke:#7a4baa;
    style v1785 fill:#e3dcea,stroke:#7a4baa;
    style v1797 fill:#e3dcea,stroke:#7a4baa;
    style v1807 fill:#e3dcea,stroke:#7a4baa;
    style v1816 fill:#e3dcea,stroke:#7a4baa;
    style v2028 fill:#e3dcea,stroke:#7a4baa;
    style v1821 fill:#e3dcea,stroke:#7a4baa;
    style v1829 fill:#e3dcea,stroke:#7a4baa;
    style v1836 fill:#e3dcea,stroke:#7a4baa;
    style v1846 fill:#e3dcea,stroke:#7a4baa;
    style v1852 fill:#e3dcea,stroke:#7a4baa;
    style v2006 fill:#e3dcea,stroke:#7a4baa;
    style v1861 fill:#e3dcea,stroke:#7a4baa;
    style v1869 fill:#e3dcea,stroke:#7a4baa;
    style v1876 fill:#e3dcea,stroke:#7a4baa;
    style v1886 fill:#e3dcea,stroke:#7a4baa;
    style v1895 fill:#e3dcea,stroke:#7a4baa;
    style v1922 fill:#e3dcea,stroke:#7a4baa;
    style v1900 fill:#e3dcea,stroke:#7a4baa;
    style v1907 fill:#e3dcea,stroke:#7a4baa;
    style v1917 fill:#e3dcea,stroke:#7a4baa;
    style v1926 fill:#e3dcea,stroke:#7a4baa;
    style v1953 fill:#e3dcea,stroke:#7a4baa;
    style v1931 fill:#e3dcea,stroke:#7a4baa;
    style v1938 fill:#e3dcea,stroke:#7a4baa;
    style v1948 fill:#e3dcea,stroke:#7a4baa;
    style v1957 fill:#e3dcea,stroke:#7a4baa;
    style v1984 fill:#e3dcea,stroke:#7a4baa;
    style v1962 fill:#e3dcea,stroke:#7a4baa;
    style v1969 fill:#e3dcea,stroke:#7a4baa;
    style v1979 fill:#e3dcea,stroke:#7a4baa;
    style v1991 fill:#e3dcea,stroke:#7a4baa;
    style v2001 fill:#e3dcea,stroke:#7a4baa;
    style v2013 fill:#e3dcea,stroke:#7a4baa;
    style v2023 fill:#e3dcea,stroke:#7a4baa;
    style v2035 fill:#e3dcea,stroke:#7a4baa;
    style v2045 fill:#e3dcea,stroke:#7a4baa;
    style v2057 fill:#e3dcea,stroke:#7a4baa;
    style v2064 fill:#e3dcea,stroke:#7a4baa;
    style v2076 fill:#e3dcea,stroke:#7a4baa;
    style v2083 fill:#e3dcea,stroke:#7a4baa;
    style v2087 fill:#e3dcea,stroke:#7a4baa;

```

