---
title: "Split h5mu"
namespace: "Workflows/multiomics"
description: "Split the samples of a single modality from a .h5mu (multimodal) sample into seperate .h5mu files based on the values of an .obs column of this modality"
type: "workflow"
toc: false
---

::: {.column-margin}

### Info

ID: `split_h5mu`  
Namespace: `workflows/multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/v2.1.0-rc.2/src/workflows/multiomics/split_h5mu/config.vsh.yaml){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v2.1.0-rc.2 -latest \
  -main-script target/nextflow/workflows/multiomics/split_h5mu/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Input & specifications
input: # please fill in - example: "path/to/file"
modality: "rna"
obs_feature: # please fill in - example: "celltype"
drop_obs_nan: false
ensure_unique_filenames: false

# Outputs
# output: "$id.$key.output"
# output_compression: "gzip"
# output_files: "$id.$key.output_files.csv"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"

# Arguments
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r v2.1.0-rc.2 -latest \
  -profile docker \
  -main-script target/nextflow/workflows/multiomics/split_h5mu/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Input & specifications

|Name                        |Description                                                                            |Attributes                                |
|:----------|:--------------------------------------------------|:--------------------|
|`--input`                   |Path to a single .h5mu file.                                                           |`file`, required                          |
|`--modality`                |                                                                                       |`string`, default: `"rna"`                |
|`--obs_feature`             |The .obs column to split the mudata on.                                                |`string`, required, example: `"celltype"` |
|`--drop_obs_nan`            |Whether to drop all .obs columns that contain only nan values after splitting.         |`boolean_true`                            |
|`--ensure_unique_filenames` |Append number suffixes to ensure unique filenames after sanitizing obs feature values. |`boolean_true`                            |


### Outputs

|Name                   |Description                                                               |Attributes                                      |
|:----------|:--------------------------------------------------|:--------------------|
|`--output`             |Output directory containing multiple h5mu files.                          |`file`, required, example: `"/path/to/output"`  |
|`--output_compression` |The compression format to be used on the output h5mu object.              |`string`, example: `"gzip"`                     |
|`--output_files`       |A csv containing the base filename and obs feature by which it was split. |`file`, required, example: `"sample_files.csv"` |

## Authors


  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) [{{< fa brands linkedin >}}](https://linkedin.com/in/dries-schaumont) (author, maintainer)

## Visualisation

```{mermaid}
flowchart TB
    v0(Channel.fromList)
    v2(filter)
    v13(filter)
    v18(split_h5mu_component)
    v25(cross)
    v35(cross)
    v45(concat)
    v52(cross)
    v59(cross)
    v71(cross)
    v78(cross)
    v82(Output)
    v0-->v2
    v13-->v18
    v18-->v25
    v13-->v25
    v13-->v35
    v45-->v52
    v2-->v52
    v52-->v59
    v2-->v59
    v2-->v71
    v71-->v78
    v2-->v78
    v78-->v82
    v2-->v13
    v35-->v45
    v18-->v35
    v45-->v71
    style v0 fill:#e3dcea,stroke:#7a4baa;
    style v2 fill:#e3dcea,stroke:#7a4baa;
    style v13 fill:#e3dcea,stroke:#7a4baa;
    style v18 fill:#e3dcea,stroke:#7a4baa;
    style v25 fill:#e3dcea,stroke:#7a4baa;
    style v35 fill:#e3dcea,stroke:#7a4baa;
    style v45 fill:#e3dcea,stroke:#7a4baa;
    style v52 fill:#e3dcea,stroke:#7a4baa;
    style v59 fill:#e3dcea,stroke:#7a4baa;
    style v71 fill:#e3dcea,stroke:#7a4baa;
    style v78 fill:#e3dcea,stroke:#7a4baa;
    style v82 fill:#e3dcea,stroke:#7a4baa;

```

