---
title: Getting started
---

# Forking the code and cloning the repository
The openpipelines code is hosted on GitHub. To start working on openpipeline, you should create your own copy of the repository by forking it. Visit the openpipeline repository [here](https://github.com/openpipelines-bio/openpipeline) and use the 'Fork' button on the top right hand side of the page. After you are done forking, you can clone the repository to a local directory on your computer using `git clone`. You can choose between using an SSH key to log in to GitHub or username and password (HTTPS) to connect to github.

::: {.panel-tabset}

# HTTPS 
```bash
git clone https://github.com/<YOUR USERNAME>/openpipeline.git
cd openpipeline
git remote add upstream https://github.com/openpipeline-bio/openpipeline.git
```

# SSH
```bash
git clone git@github.com:<YOUR USERNAME>/openpipeline.git
cd openpipeline
git remote add upstream https://github.com/openpipeline-bio/openpipeline.git
```

:::

# Installing `viash` and `nextflow` {#sec-install-viash-nextflow}
Openpipelines is being developed in Viash and Nextflow. If you are unfamiliar with either one of these platforms, you can check out their respective documentations [here](https://viash.io/guides/getting_started/introduction/) and [here](https://www.nextflow.io/docs/latest/index.html). To start contributing to openpipelines, you will need at least a working version of Java 11, OpenJDK 11, or a later version (up to Java 18). Additionally, by using [Docker](https://www.docker.com/),you can build and test pipeline components and pipelines without needing to manually install dependencies for these components on your machine.

Viash and Nextflow can be installed by following the guides in the documentation for both of these tools. Make sure the `viash` and `nextflow` binaries are located in an existing directory that is listed in your `$PATH`. You can check if everything worked by running the following two commands and see if they output the correct location of the executables.

```bash
which viash
which nextflow
```